ACADOBRE_QUESTIONS.push({
  id: 'dns',
    topic: 'DNS',
    questions: [
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru DNS?',
        acceptedAnswers: ['53 TCP UDP', '53 UDP TCP', '53 tcp udp', '53 udp tcp'],
        hint: 'Exemplu de raspuns: "12 DBR URS".',
      },
      {
      type: 'open-ended',
      text: 'Care este comanda pentru a dezactiva cautarea de domeniu pentru dispozitivele cisco?',
      acceptedAnswers: ['no ip domain-lookup'],
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca putem configura un router drept server DNS?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Care este tipul de inregistrare DNS pentru adrese IPv4?',
      options: ['A',
                'AAAA',
                'MX',
                'NS',
                'CNAME',
                'HP',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care este tipul de inregistrare DNS pentru adrese IPv6?',
      options: ['A',
                'AAAA',
                'MX',
                'NS',
                'CNAME',
                'HP',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Care este tipul de inregistrare DNS pentru mail exchange?',
      options: ['A',
                'AAAA',
                'MX',
                'NS',
                'CNAME',
                'HP',
               ],
      correctIndex: 2,
      },
      {
      type: 'multiple-choice',
      text: 'Care este tipul de inregistrare DNS pentru serverele de nume autoritare?',
      options: ['A',
                'AAAA',
                'MX',
                'NS',
                'CNAME',
                'HP',
               ],
      correctIndex: 3,
      },
      {
      type: 'multiple-choice',
      text: 'Dupa ce se alege daca DNS foloseste TCP sau UDP?',
      options: ['Dimensiunea pachetului',
                'Lungimea numelui de host',
                'Daca serverul DNS se afla in alta retea',
                'Hostname-ul dispozitivului',
                'Latenta pentru trimiterea mesajelor',
                'Congestie in retea',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Unde se salveaza local cautarile prin DNS?',
      options: ['DNS Table',
                'DNS Cache',
                'Translation table',
                'DNS Query',
                'Domain mapping table',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Cum se numesc mesajele de cautare prin DNS?',
      options: ['DNS Table',
                'DNS Cache',
                'Translation table',
                'DNS Query',
                'Domain mapping table',
               ],
      correctIndex: 3,
      },
    ]
});