ACADOBRE_QUESTIONS.push({
  id: 'eigrp',
    topic: 'EIGRP',
    questions: [
    {
        type: 'header-fill',
        text: 'Identifica campurile antetului mesajelor EIGRP in ordine:',
         images: [
                   'questions/images/eigrp_header/eigrp_header_blank.png',
                   'questions/images/eigrp_header/eigrp_header_01.png',
                   'questions/images/eigrp_header/eigrp_header_02.png',
                   'questions/images/eigrp_header/eigrp_header_03.png',
                   'questions/images/eigrp_header/eigrp_header_04.png',
                   'questions/images/eigrp_header/eigrp_header_05.png',
                   'questions/images/eigrp_header/eigrp_header_06.png',
                   'questions/images/eigrp_header/eigrp_header_complete.png',
                ],

        fields: [
                  { names: ['Version','Ver'],                   bits: 8  },
                  { names: ['Opcode'],                          bits: 8  },
                  { names: ['Checksum'],                        bits: 16 },
                  { names: ['Flags'],                           bits: 32 },
                  { names: ['Sequence Number', 'Seq'],          bits: 32 },
                  { names: ['Acknowledgement Number', 'ACK'],   bits: 32 },
                  { names: ['Autonomous System Number', 'ASN'], bits: 32 },
                ],
    },
    {
        type: 'header-fill',
        text: 'Identifica campurile EIGRP Internal Type Length Value in ordine:',
         images: [
                   'questions/images/eigrp_internal_tlv/eigrp_internal_tlv_blank.png',
                   'questions/images/eigrp_internal_tlv/eigrp_internal_tlv_00.png',
                   'questions/images/eigrp_internal_tlv/eigrp_internal_tlv_01.png',
                   'questions/images/eigrp_internal_tlv/eigrp_internal_tlv_02.png',
                   'questions/images/eigrp_internal_tlv/eigrp_internal_tlv_03.png',
                   'questions/images/eigrp_internal_tlv/eigrp_internal_tlv_04.png',
                   'questions/images/eigrp_internal_tlv/eigrp_internal_tlv_05.png',
                   'questions/images/eigrp_internal_tlv/eigrp_internal_tlv_06.png',
                   'questions/images/eigrp_internal_tlv/eigrp_internal_tlv_07.png',
                   'questions/images/eigrp_internal_tlv/eigrp_internal_tlv_08.png',
                   'questions/images/eigrp_internal_tlv/eigrp_internal_tlv_09.png',
                   'questions/images/eigrp_internal_tlv/eigrp_internal_tlv_10.png',
                   'questions/images/eigrp_internal_tlv/eigrp_internal_tlv_complete.png',
                ],

        fields: [
                  { names: ['Type'],           bits: 16 },
                  { names: ['Length', 'Len'],   bits: 16  },
                  { names: ['Next Hop', 'NH'],  bits: 32  },
                  { names: ['Delay'],           bits: 32  },
                  { names: ['Bandwidth', 'Bw'], bits: 32  },
                  { names: ['MTU'],             bits: 24 },
                  { names: ['Hop Count'],       bits: 8 },
                  { names: ['Reliability', `Fiabil`],     bits: 8 },
                  { names: ['Load'],            bits: 8  },
                  { names: ['Reserved', `Res`],        bits: 16 },
                  { names: ['Prefix Length', `pr len`],   bits: 8 },
                  { names: ['Destination', `dest`],     bits: 24 },
                ],
    },
    {
        type: 'header-fill',
        text: 'Identifica campurile EIGRP External Type Length Value in ordine:',
         images: [
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_blank.png',
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_01.png',
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_02.png',
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_03.png',
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_04.png',
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_05.png',
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_06.png',
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_07.png',
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_08.png',
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_09.png',
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_10.png',
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_11.png',
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_12.png',
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_13.png',
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_14.png',
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_15.png',
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_16.png',
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_17.png',
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_18.png',
                   'questions/images/eigrp_external_tlv/eigrp_external_tlv_complete.png',
                ],

        fields: [
                  { names: ['Type',],                                       bits: 16 },
                  { names: ['Length', 'Len'],                               bits: 16  },
                  { names: ['Next Hop', 'NH'],                              bits: 32  },
                  { names: ['Originating Routers', 'OG router'],                         bits: 32  },
                  { names: ['Originating ASN', 'OG ASN'],                             bits: 32  },
                  { names: ['Arbitrary Tag'],                               bits: 32 },
                  { names: ['External Protocol Metric', 'EX Prot metric', 'Ex Metric'],  bits: 32 },
                  { names: ['Reserved', 'Res'],                                    bits: 16 },
                  { names: ['External Protocol ID', 'Ex PID'],              bits: 8 },
                  { names: ['Flags'],                                       bits: 8 },
                  { names: ['Delay'],                                       bits: 32  },
                  { names: ['Bandwidth', 'Bw'],                             bits: 32  },
                  { names: ['MTU'],                                         bits: 24 },
                  { names: ['Hop Count'],                                   bits: 8 },
                  { names: ['Reliability', 'Fiabil'],                                 bits: 8 },
                  { names: ['Load'],                                        bits: 8  },
                  { names: ['Reserved', 'Res'],                                    bits: 16 },
                  { names: ['Prefix Length', 'PR len'],                               bits: 8 },
                  { names: ['Destination', 'Dest'],                                 bits: 24 },
                ],
    },
    {
      type: 'open-ended',
      text: 'Cat de des sunt trimise mesajele de hello prin EIGRP pe o legatura cu latime de banda <= 1.544 Mbps? (secunde)',
      acceptedAnswers: ['60'],
    },
    {
      type: 'open-ended',
      text: 'Pentru cat timp sunt pastrati vecinii prin EIGRP pe o legatura cu latime de banda <= 1.544 Mbps fara a primi hello (hold timer)? (secunde)',
      acceptedAnswers: ['180'],
    },
    {
      type: 'open-ended',
      text: 'Cat de des sunt trimise mesajele de hello prin EIGRP pe o legatura cu latime de banda > 1.544 Mbps? (secunde)',
      acceptedAnswers: ['5'],
    },
    {
      type: 'open-ended',
      text: 'Pentru cat timp sunt pastrati vecinii prin EIGRP pe o legatura cu latime de banda > 1.544 Mbps fara a primi hello (hold timer)? (secunde)',
      acceptedAnswers: ['15'],
    },
    {
      type: 'open-ended',
      text: 'Care este adresa IPv6 Multicast pentru routerele EIGRP?',
      acceptedAnswers: ['ff02::a'],
    },
    {
      type: 'open-ended',
      text: 'Care este adresa IPv4 Multicast pentru routerele EIGRP?',
      acceptedAnswers: ['224.0.0.10'],
    },
    {
      type: 'open-ended',
      text: 'Ce numar indica protocolul EIGRP in campul IPv4 Protocol?',
      acceptedAnswers: ['88'],
    },
    {
      type: 'open-ended',
      text: 'Care este distanta administrativa pentru protocolul EIGRP intern?',
      acceptedAnswers: ['90'],
    },
    {
      type: 'open-ended',
      text: 'Care este distanta administrativa pentru protocolul EIGRP extern?',
      acceptedAnswers: ['170'],
    },
    {
      type: 'open-ended',
      text: 'Ce cod are o ruta invatata prin EIGRP in tabela de rutare?',
      acceptedAnswers: ['D'],
    },
    {
      type: 'multiple-choice',
      text: 'In ce zona de memorie se salveaza structurile de date EIGRP?',
      options: ['RAM', 'NVRAM', 'Flash', 'ROM', 'CPU', 'SSD'],
      correctIndex: 0,
    },
    {
        type: 'multiple-choice',
        text: 'Ce protocol de nivel 4 folosesc mesajele EIGRP?',
        options: [
          'TCP',
          'RTP',
          'UDP',
          'Real-time Protocol',
          'ETP',
        ],
        correctIndex: 1
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca EIGRP este considerat un protocol hibrid deoarece prezinta trasaturi atat Distance Vector cat si Link-State?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca EIGRP nu poate realiza Unequal Cost Load Balancing?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 1,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca exista versiuni diferite de EIGRP pentru IPv4 si IPv6?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 1,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca 2 rutere pot sa nu aiba acelasi Autonomous System Number (ASN) pentru a deveni vecini EIGRP?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 1,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca 2 rutere trebuie sa aiba interfetele in acelasi subnet pentru a deveni vecini EIGRP?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca 2 rutere pot deveni vecini EIGRP daca au acelasi RID?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 1,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca 2 rutere pot deveni vecini EIGRP daca nu au aceiasi parametri pentru metrica (K values)?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 1,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca 2 rutere pot deveni vecini EIGRP daca nu au aceleasi timere pentru Hello si Hold?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca EIGRP poate realiza sumarizarea rutelor?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca 2 rutere nu pot deveni vecini EIGRP daca nu au aceleasi setari de autentificare?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numesc interfetele pe care ruterele nu mai trimit doar mesaje specifice de rutare EIGRP?',
      options: ['Interfete pasive', 'Interfete auto', 'Interfete down', 'Interfete trunk', 'Interfete acces'],
      correctIndex: 0, 
    },
    {
      type: 'multiple-choice',
      text: 'Care este algoritmul de rutare folosit de protocolul EIGRP?',
      options: ['Diffusing Update Algorithm (DUAL)', 'Djikstra', 'Bellman-Ford', 'Diffie-Hellman', 'Message-Digest5 ', 'Distance Vector', 'Link-State'],
      correctIndex: 0, 
    },
    {
      type: 'multiple-choice',
      text: 'Ce tip de protocol de rutare dinamica este EIGRP?',
      options: ['Link-State', 'Djikstra', 'Path Vector', 'Message-Digest5', 'Distance Vector', 'Shortest Path First'],
      correctIndex: 4, 
    },
    {
        type: 'multiple-choice',
        text: 'Cum se numeste metrica unui router EIGRP catre o destinatie asa cum este provenita de la un vecin?',
        options: [
          'Reported Distance',
          'Feasible Distance',
          'Successor',
          'Feasible Successor',
          'Feasible Condition',
        ],
        correctIndex: 0
    },
    {
        type: 'multiple-choice',
        text: 'Cum se numeste metrica unui router EIGRP catre o destinatie?',
        options: [
          'Reported Distance',
          'Feasible Distance',
          'Successor',
          'Feasible Successor',
          'Feasible Condition',
        ],
        correctIndex: 1
    },
    {
        type: 'multiple-choice',
        text: 'Cum se numeste ruta catre o destinatie a unui router EIGRP cu metrica cea mai mica?',
        options: [
          'Reported Distance',
          'Feasible Distance',
          'Successor',
          'Feasible Successor',
          'Feasible Condition',
        ],
        correctIndex: 2
    },
    {
        type: 'multiple-choice',
        text: 'Cum se numesc rutele alternative ale unui router EIGRP?',
        options: [
          'Reported Distance',
          'Feasible Distance',
          'Successor',
          'Feasible Successor',
          'Feasible Condition',
        ],
        correctIndex: 3
    },
    {
        type: 'multiple-choice',
        text: 'Ce trebuie indeplinit ca o cale alternativa EIGRP sa devina Feasible Successor?',
        options: [
          'Reported Distance',
          'Feasible Distance',
          'Successor',
          'Feasible Successor',
          'Feasible Condition',
          'Successor Condition'
        ],
        correctIndex: 4
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numesc mesajele EIGRP prin care routerele afla despre vecinii lor?',
      options: ['Hello', 'Ola', 'Query', 'Reply', 'Request', 'Update', 'LSR', 'DBD', 'Acknowledgement'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice-multi',
      text: 'Care sunt toti parametri folositi de EIGRP in calcularea metricii?\nAlegeti 4 variante.',
      options: ['Bandwidth',
                'K values',
                'Delay',
                'Incarcare (Load)',
                'Fiabilitate',
                'Throughput',
                'Goodput',
                'Speed'
              ],
      correctIndices: [0, 2, 3, 4]
    },
    {
      type: 'multiple-choice-multi',
      text: 'Care sunt parametri folositi by default de EIGRP in calcularea metricii?\nAlegeti 2 variante.',
      options: ['Bandwidth',
                'K values',
                'Delay',
                'Incarcare (Load)',
                'Fiabilitate',
                'Throughput',
                'Goodput',
                'Speed'
              ],
      correctIndices: [0, 2]
    },
        {
      type: 'matching',
      text: 'Asociati tipul de mesaj EIGRP cu functia pe care o au:',
      subQuestions: [
        { text: 'Hello', answer: 'Stabilirea adiacentelor' },
        { text: 'Update', answer: 'Trimiterea informatiilor de rutare' },
        { text: 'Acknowledgement', answer: 'Raspuns la mesajele Update' },
        { text: 'Query', answer: 'Cautarea rutelor alternative' },
        { text: 'Reply', answer: 'Raspuns la mesajele Query' },
      ],
      options: ['Stabilirea adiacentelor', 'Trimiterea informatiilor de rutare', 'Raspuns la mesajele Update', 'Raspuns la mesajele Query', 'Cautarea rutelor alternative'],
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numesc mesajele EIGRP prin care routerele trimit informatii despre rutele pe care le au?',
      options: ['Hello', 'Ola', 'Query', 'Reply', 'Request', 'Update', 'LSR', 'DBD', 'Acknowledgement'],
      correctIndex: 5,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numesc mesajele EIGRP prin care ruterele confirma ca au primit Update?',
      options: ['Hello', 'Ola', 'Query', 'Reply', 'Request', 'Update', 'LSR', 'DBD', 'Acknowledgement'],
      correctIndex: 8,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numesc mesajele EIGRP prin care ruterele cauta cai alternative catre o destinatie?',
      options: ['Hello', 'Ola', 'Query', 'Reply', 'Request', 'Update', 'LSR', 'DBD', 'Acknowledgement'],
      correctIndex: 2,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numesc mesajele EIGRP trimise ca raspuns la un Query?',
      options: ['Hello', 'Ola', 'Query', 'Reply', 'Request', 'Update', 'LSR', 'DBD', 'Acknowledgement'],
      correctIndex: 3,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca un mesaj Query va primi un Reply chiar daca nu este gasita nicio ruta alternativa?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'La ce nivel pe stiva OSI functioneaza protocolul EIGRP?',
      options: ['Fizic', 'Legatura de Date', 'Retea', 'Transport', 'Sesiune', 'Prezentare', 'Aplicatie'],
      correctIndex: 2,
    },
    {
      type: 'multiple-choice',
      text: 'In ce structura de date isi mentine EIGRP informatiile despre vecini?',
      options: ['Neighbor Table', 'LSDB', 'Topology Table', 'Routing Table', 'EIGRP Table', 'ARP Table'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'In ce structura de date isi mentine EIGRP informatiile despre toate rutele cunoscute?',
      options: ['Neighbor Table', 'LSDB', 'Topology Table', 'Routing Table', 'EIGRP Table', 'ARP Table'],
      correctIndex: 2,
    },
    {
      type: 'label-order',
      text: 'Ordonati de la stanga la dreapta ordinea dupa care se alege RID-ul unui router EIGRP:',
      labels: ['Cel mai mare RID configurat manual', 'Cea mai mare adresa IP de pe o interfata Loopback', 'Cea mai mare adresa IP de pe o interfata fizica'],
      correctOrder: [0, 1, 2],
    },
    ]
});