ACADOBRE_QUESTIONS.push({
  id: 'ipv4_header',
    topic: 'Headerul IPv4',
    questions: [
      {
        type: 'header-fill',
        text: 'Identifica campurile antetului IPv4 in ordine:',
         images: [
                   'questions/images/ipv4_header/ipv4_blank.png',
                   'questions/images/ipv4_header/ipv4_01.png',
                   'questions/images/ipv4_header/ipv4_02.png',
                   'questions/images/ipv4_header/ipv4_03.png',
                   'questions/images/ipv4_header/ipv4_04.png',
                   'questions/images/ipv4_header/ipv4_05.png',
                   'questions/images/ipv4_header/ipv4_06.png',
                   'questions/images/ipv4_header/ipv4_07.png',
                   'questions/images/ipv4_header/ipv4_08.png',
                   'questions/images/ipv4_header/ipv4_09.png',
                   'questions/images/ipv4_header/ipv4_10.png',
                   'questions/images/ipv4_header/ipv4_11.png',
                   'questions/images/ipv4_header/ipv4_12.png',
                   'questions/images/ipv4_header/ipv4_13.png',
                   'questions/images/ipv4_header/ipv4_14.png',
                   'questions/images/ipv4_header/ipv4_complete.png',
                ],

        fields: [
                  { names: ['Version','Ver'],                                                       bits: 4  },
                  { names: ['Internet Header Length','IHL'],                                        bits: 4  },
                  { names: ['Differentiated Services', 'Type of service', 'DS', 'TOS', 'DiffServ'], bits: 8  },
                  { names: ['DSCP','DS Code Point', 'DiffServCP', 'DiffServ Code Point'],           bits: 6  },
                  { names: ['ECN','Explicit Congestion Notification'],                              bits: 2  },
                  { names: ['Total Len','Total Length'],                                            bits: 16 },
                  { names: ['Identification','ID'],                                                 bits: 16 },
                  { name:  'Flags',                                                                 bits: 3  },
                  { names: ['Fragment Offset','Fragoff'],                                           bits: 13 },
                  { names: ['TTL', 'Time to live'],                                                 bits: 8  },
                  { names: ['Protocol'],                                                            bits: 8  },
                  { names: ['Header Checksum','Checksum'],                                          bits: 16 },
                  { names: ['Source IP', 'Src IP'],                                                 bits: 32 },
                  { names: ['Destination IP', 'Dest IP'],                                           bits: 32 },
                  { name:  'Options',                                                               bits: 40 },
                ],
      },
      {
      type: 'multiple-choice',
      text: 'Ce functie are campul "Version" din headerul IPv4?',
      options: ['Indica versiunea protocolului IP', 'Indica lungimea headerului', 'Indica adresa sursa', 'Indica tipul protocolului de nivel superior', 'Indica totalul lungimii pachetului'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce indica campul "Header Length" din headerul IPv4?',
      options: ['Dimensiunea headerului', 'Tipul protocolului', 'TTL-ul pachetului', 'Adresa destinatie', 'Checksum-ul headerului'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care este rolul campului "Type Of Service / DiffServ"?',
      options: ['Indica prioritatea / QoS', 'Indica versiunea IP', 'Indica adresa sursa', 'Indica totalul lungimii pachetului', 'Indica protocolul nivel superior'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce reprezinta campul "Total Length" din headerul IPv4?',
      options: ['Dimensiunea totala a pachetului', 'Dimensiunea headerului', 'TTL-ul pachetului', 'Checksum-ul headerului', 'Adresa sursa'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce functie are campul "Identification" din headerul IPv4?',
      options: ['Reasamblarea pachetelor fragmentate', 'Indica prioritatea QoS', 'Indica protocolul nivel superior', 'Dimensiunea totala a pachetului', 'Verifica erorile headerului'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care este rolul campului "Flags" din headerul IPv4?',
      options: ['Controlul fragmentarii', 'Indica lungimea headerului', 'Indica adresa sursa', 'Indica TTL-ul', 'Dimensiunea totala a pachetului'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce indica campul "Fragment Offset" din headerul IPv4?',
      options: ['Ordinea fragmentelor', 'Lungimea headerului', 'Prioritatea QoS', 'Adresa destinatie', 'TTL-ul pachetului'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce functie are campul "Time To Live" (TTL) din headerul IPv4?',
      options: ['Previne buclele in retea', 'Indica adresa sursa', 'Verifica integritatea pachetului', 'Indica protocolul nivel superior', 'Indica dimensiunea payload-ului'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce indica campul "Protocol" din headerul IPv4?',
      options: ['Protocolul nivelului superior', 'Indica prioritatea QoS', 'Ordinea fragmentelor', 'TTL-ul pachetului', 'Checksum-ul headerului'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care este scopul campului "Header Checksum" din headerul IPv4?',
      options: ['Verifica erorile headerului', 'Indica adresa destinatie', 'Indica protocolul nivel superior', 'Indica dimensiunea totala a pachetului', 'Ordinea fragmentelor'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce reprezinta campul "Source Address" din headerul IPv4?',
      options: ['Adresa IP sursa', 'Adresa IP destinatie', 'Dimensiunea headerului', 'Protocolul nivel superior', 'TTL-ul pachetului'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce reprezinta campul "Destination Address" din headerul IPv4?',
      options: ['Adresa IP destinatie', 'Adresa IP sursa', 'Dimensiunea payload-ului', 'Ordinea fragmentelor', 'Checksum header'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce rol are campul "Options" din headerul IPv4?',
      options: ['Setari suplimentare, variabile ca dimensiune', 'TTL-ul pachetului', 'Indica protocolul nivel superior', 'Ordinea fragmentelor', 'Checksum header'],
      correctIndex: 0,
      },
    ]
});