ACADOBRE_QUESTIONS.push({
  id: 'nat',
    topic: 'NAT',
    questions: [
    {
        type: 'open-ended',
        text: 'Care este range-ul de porturi folosite de Dynamic PAT?',
        acceptedAnswers: ['1024-65535'],
        hint: 'Exemplu de raspuns: "x-y".',
    },
    {
      type: 'open-ended',
      text: 'Ce spatiu reprezinta adresele private din clasa A in IPv4?',
      hint: 'Introduceti raspunsul in forma: "a.a.a.a/b" sau "x.x.x.x y.y.y.y". Aveti grija la format!',
      acceptedAnswers: ['10.0.0.0 255.0.0.0', '10.0.0.0/8'],
    },
    {
      type: 'open-ended',
      text: 'Ce spatiu reprezinta adresele private din clasa B in IPv4?',
      hint: 'Introduceti raspunsul in forma: "a.a.a.a/b" sau "x.x.x.x y.y.y.y". Aveti grija la format!',
      acceptedAnswers: ['172.16.0.0 255.240.0.0', '172.16.0.0/12'],
    },
    {
      type: 'open-ended',
      text: 'Ce spatiu reprezinta adresele private din clasa C in IPv4?',
      hint: 'Introduceti raspunsul in forma: "a.a.a.a/b" sau "x.x.x.x y.y.y.y". Aveti grija la format!',
      acceptedAnswers: ['192.168.0.0 255.255.0.0', '192.168.0.0/16'],
    },
    {
      type: 'multiple-choice',
      text: 'La ce nivel OSI opereaza NAT?',
      options: ['Aplicatie', 'Fizic', 'Legatura de Date', 'Prezentare', 'Transport', 'Retea', 'Sesiune'],
      correctIndex: 5,
    },
    {
      type: 'multiple-choice',
      text: 'De la ce vine prescurtarea NAT?',
      options: ['Network Address Translation',
                'Network Address Transit',
                'Network Authentication Translation',
                'Nearby Authorization Transport',
                'Network Access Translation'
              ],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numeste hostul intern din perspectiva retelei interne?',
      options: ['Inside Local',
                'Inside Global',
                'Outside Local',
                'Outside Global',
                'Inside Intern',
                'Outside Extern'
              ],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numeste hostul intern din perspectiva retelei externe?',
      options: ['Inside Local',
                'Inside Global',
                'Outside Local',
                'Outside Global',
                'Inside Intern',
                'Outside Extern'
              ],
      correctIndex: 1,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numeste hostul extern din perspectiva retelei interne?',
      options: ['Inside Local',
                'Inside Global',
                'Outside Local',
                'Outside Global',
                'Inside Intern',
                'Outside Extern'
              ],
      correctIndex: 3,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numeste hostul extern din perspectiva retelei externe?',
      options: ['Inside Local',
                'Inside Global',
                'Outside Local',
                'Outside Global',
                'Inside Intern',
                'Outside Extern'
              ],
      correctIndex: 2,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca adresele private IPv4 pot fi rutate prin Internet?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 1,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca pentru functionarea NAT trebuie sa definim interfetele inside si outside?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca traficul care nu este permis de catre ACL-ul unui router care foloseste Dynamic NAT/PAT va fi aruncat?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 1,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca un router care nu mai are adrese inside global disponbile va pastra pachetul intr-un buffer fara sa il arunce?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 1,
    },
    {
      type: 'multiple-choice',
      text: 'La ce tip de adresa se mapeaza adresa Inside Local in static source NAT?',
      options: ['Inside Local',
                'Inside Global',
                'Outside Local',
                'Outside Global',
                'Inside Intern',
                'Outside Extern'
              ],
      correctIndex: 1,
    },
    {
      type: 'multiple-choice',
      text: 'Ce tip de NAT presupune maparea 1 la 1 dintre adrese IPv4 private si adrese IPv4 publice?',
      options: ['Static NAT',
                'Dynamic NAT',
                'Dynamic NAT Overload',
                'Static PAT',
                'Outside NAT',
                'Routed NAT'
              ],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Ce tip de NAT presupune maparea mai multor adrese IPv4 private la un pool de adrese IPv4 publice?',
      options: ['Static NAT',
                'Dynamic NAT',
                'Dynamic NAT Overload',
                'Static PAT',
                'Outside NAT',
                'Routed NAT'
              ],
      correctIndex: 1,
    },
    {
      type: 'multiple-choice',
      text: 'Ce tip de NAT presupune maparea mai multor adrese IPv4 private la o singura IPv4 publica cu un numar de port variat?',
      options: ['Static NAT',
                'Dynamic NAT',
                'Dynamic NAT Overload',
                'Static PAT',
                'Outside NAT',
                'Routed NAT'
              ],
      correctIndex: 2,
    },
    {
      type: 'multiple-choice',
      text: 'Ce tip de NAT presupune maparea mai multor adrese IPv4 private la o singura IPv4 publica cu un numar de port fixat?',
      options: ['Static NAT',
                'Dynamic NAT',
                'Dynamic NAT Overload',
                'Static PAT',
                'Outside NAT',
                'Routed NAT'
              ],
      correctIndex: 3,
    },
    {
      type: 'multiple-choice',
      text: 'Ce tip de NAT este cel mai eficient pentru a folosi cat mai putine adrese IPv4 publice?',
      options: ['Static NAT',
                'Dynamic NAT',
                'Dynamic NAT Overload',
                'Static PAT',
                'Outside NAT',
                'Routed NAT'
              ],
      correctIndex: 2,
    },
    {
      type: 'multiple-choice',
      text: 'Ce se foloseste pentru a determina care adrese private sa fie traduse folosind Dynamic NAT/PAT?',
      options: ['Access Control List',
                'Subnet Mask',
                'Wildcard Mask',
                'Hostname List',
                'ARP Table',
                'DHCP Snooping Binding Table',
                'NAT Pool'
              ],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Ce se foloseste pentru a determina care adrese publice sa fie utilizate la traducerea Dynamic NAT/PAT?',
      options: ['Access Control List',
                'Subnet Mask',
                'Wildcard Mask',
                'Hostname List',
                'ARP Table',
                'DHCP Snooping Binding Table',
                'NAT Pool'
              ],
      correctIndex: 6,
    },
    {
      type: 'multiple-choice-multi',
      text: 'Folosind strict source NAT, care adrese ne putem astepta sa fie mereu la fel?\nAlegeti 2 variante.',
      options: ['Inside Local',
                'Inside Global',
                'Outside Local',
                'Outside Global',
                'Inside Intern',
                'Outside Extern'
              ],
      correctIndices: [2, 3]
    },
    {
      type: 'multiple-choice-multi',
      text: 'Care dintre urmatoarele reprezinta metode de a incetini epuizarea adreselor IPv4 publice?\nAlegeti 4 variante.',
      options: ['NAT',
                'Dual-Stacking',
                'Tunneling',
                'NAT64',
                'Adaugarea a inca unui octet adreselor IPv4',
                'Folosirea IPv5'
              ],
      correctIndices: [0, 1, 2, 3]
    },
    {
      type: 'matching',
      text: 'Asociati spatiile urmatoare cu subnetul potrivit:',
      subQuestions: [
        { text: 'Clasa A privat', answer: '/8' },
        { text: 'Clasa A',        answer: '/8' },
        { text: 'Clasa B privat', answer: '/12' },
        { text: 'Clasa B',        answer: '/16' },
        { text: 'Clasa C privat', answer: '/16' },
        { text: 'Clasa C',        answer: '/24' },
      ],
      options: ['/8', '/10', '/12', '/16', '/20', '/24'],
    },
    ]
});
