ACADOBRE_QUESTIONS.push({
  id: 'ntp',
    topic: 'NTP',
    questions: [
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru NTP?',
        acceptedAnswers: ['123 UDP', '123 udp'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care sunt valorile posibile de stratum NTP?',
        acceptedAnswers: ['0-15'],
        hint: 'Exemplu de raspuns: "a-b".',
      },
      {
      type: 'multiple-choice',
      text: 'Cum se numesc serverele NTP de stratum 1?',
      options: ['Servere primare',
                'Servere de referinta',
                'Servere secundare',
                'Servere tertiare',
                'Servere relay',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Cum se numesc serverele NTP de stratum 0?',
      options: ['Servere primare',
                'Servere de referinta',
                'Servere secundare',
                'Servere tertiare',
                'Servere relay',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Cum se numesc serverele NTP de stratum 2 sau mai mare?',
      options: ['Servere primare',
                'Servere de referinta',
                'Servere secundare',
                'Servere tertiare',
                'Servere relay',
               ],
      correctIndex: 2,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca un dispozitiv Cisco nu poate fi atat server, cat si client NTP?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca NTP permite autentificare?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 1,
      },
    ]
});
