ACADOBRE_QUESTIONS.push({
  id: 'osi_tcp',
  topic: 'OSI si TCP/IP',
  questions: [
    {
      type: 'multiple-choice-multi',
      text: 'Care dintre urmatoarele nivele OSI reprezinta nivelul Aplicatie in TCP/IP?\nAlegeti 3 variante.',
      options: ['Aplicatie', 'Fizic', 'Legatura de Date', 'Prezentare', 'Transport', 'Retea', 'Sesiune'],
      correctIndices: [0, 3, 6], 
    },
    {
      type: 'multiple-choice-multi',
      text: 'Care dintre urmatoarele nivele OSI reprezinta nivelul Acces la retea in TCP/IP?\nAlegeti 2 variante.',
      options: ['Aplicatie', 'Fizic', 'Legatura de Date', 'Prezentare', 'Transport', 'Retea', 'Sesiune'],
      correctIndices: [1, 2], 
    },
    {
      type: 'multiple-choice',
      text: 'Care nivel TCP/IP reprezinta nivelul Retea pentru OSI?',
      options: ['Aplicatie', 'Acces la retea', 'Transport', 'Internet'],
      correctIndex: 3,
    },
    {
      type: 'multiple-choice-multi',
      text: 'Care dintre urmatoarele reprezinta sublayerele nivelului Legatura de Date in OSI?\nAlegeti 2 variante.',
      options: ['Media Access Control', 'Magical Address Control', 'Logical Link Control', 'Media Address Control', 'Logical Address Control'],
      correctIndices: [0, 2], 
    },
    {
      type: 'multiple-choice',
      text: 'Care nivel TCP/IP reprezinta in nivelul Transport pentru OSI?',
      options: ['Aplicatie', 'Acces la retea', 'Transport', 'Internet'],
      correctIndex: 2,
    },
    {
      type: 'multiple-choice',
      text: 'Care nivel OSI se ocupa cu adresarea logica?',
      options: ['Aplicatie', 'Fizic', 'Legatura de Date', 'Prezentare', 'Transport', 'Retea', 'Sesiune'],
      correctIndex: 5,
    },
    {
      type: 'multiple-choice',
      text: 'Care nivel OSI se ocupa cu adresarea fizica?',
      options: ['Aplicatie', 'Fizic', 'Legatura de Date', 'Prezentare', 'Transport', 'Retea', 'Sesiune'],
      correctIndex: 2,
    },
    {
      type: 'multiple-choice-multi',
      text: 'Care dintre urmatoarele nivele OSI adauga un header mesajelor primite?\nAlegeti 6 variante.',
      options: ['Aplicatie', 'Fizic', 'Legatura de Date', 'Prezentare', 'Transport', 'Retea', 'Sesiune'],
      correctIndices: [0, 2, 3, 4, 5, 6], 
    },
    {
      type: 'multiple-choice-multi',
      text: 'Care dintre urmatoarele pot fi considerate dispozitive de nivel 2?\nAlegeti 2 variante.',
      options: ['Switch', 'Router', 'Hub', 'MultiLayer Switch', 'Access Point', 'Wireless Router', 'Firewall'],
      correctIndices: [0, 3], 
    },
    {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele poate fi considerat dispozitiv de nivel 1?',
      options: ['Switch', 'Router', 'Hub', 'MultiLayer Switch', 'Access Point', 'Wireless Router', 'Firewall'],
      correctIndex: 2, 
    },
    {
      type: 'matching',
      text: 'Asociati fiecare dispozitiv cu nivelul OSI la care funtioneaza cel mai des:',
      subQuestions: [
        { text: 'Switch', answer: 'Layer 2' },
        { text: 'Router', answer: 'Layer 3' },
        { text: 'Access Point', answer: 'Layer 2' },
        { text: 'Hub', answer: 'Layer 1' },
        { text: 'Firewall', answer: 'Layer 3' },
      ],
      options: ['Layer 1', 'Layer 2', 'Layer 3'],
      },
    {
      type: 'multiple-choice-multi',
      text: 'Care dintre urmatoarele pot fi considerate dispozitive de nivel 3?\nAlegeti 4 variante.',
      options: ['Switch', 'Router', 'Hub', 'MultiLayer Switch', 'Access Point', 'Wireless Router', 'Firewall'],
      correctIndices: [1, 3, 4, 6], 
    },
    {
      type: 'matching',
      text: 'Asociati fiecare nivel OSI cu tipul de PDU corespunzator:',
      subQuestions: [
        { text: 'Aplicatie', answer: 'Date' },
        { text: 'Prezentare', answer: 'Date' },
        { text: 'Sesiune', answer: 'Date' },
        { text: 'Transport (UDP)', answer: 'Datagrame' },
        { text: 'Transport (TCP)', answer: 'Segmente' },
        { text: 'Retea', answer: 'Pachete' },
        { text: 'Legatura de Date', answer: 'Cadre' },
        { text: 'Fizic', answer: 'Biti' },
      ],
      options: ['Biti', 'Cadre', 'Datagrame', 'Segmente', 'Pachete', 'Date'],
    },
    {
      type: 'label-order',
      text: 'Ordonati de la stanga la dreapta nivelele stivei OSI.',
      labels: ['Fizic', 'Legatura de Date', 'Retea', 'Transport', 'Sesiune', 'Prezentare', 'Aplicatie'],
      correctOrder: [0, 1, 2, 3, 4, 5, 6],
    },
    {
      type: 'label-order',
      text: 'Ordonati de la stanga la dreapta nivelele stivei TCP/IP.',
      labels: ['Acces la Retea', 'Internet', 'Transport', 'Aplicatie'],
      correctOrder: [0, 1, 2, 3],
    },
    {
      type: 'multiple-choice',
      text: 'Care nivel OSI se ocupa cu formatul fisierelor si criptarea?',
      options: ['Aplicatie', 'Fizic', 'Legatura de Date', 'Prezentare', 'Transport', 'Retea', 'Sesiune'],
      correctIndex: 3,
    },
    {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele procedee reprezinta adaugarea unui header mesajelor pentru transmitere?',
      options: ['De-encapsulare', 'Multiplexare', 'Segmentare', 'Encapsulare', 'Routare'],
      correctIndex: 3,
    },
    {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele procedee reprezinta inlaturarea headerelor din mesaje pentru transmitere?',
      options: ['De-encapsulare', 'Multiplexare', 'Segmentare', 'Encapsulare', 'Routare'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele procedee reprezinta impartirea unui mesaj in mai multe mesaje mai mici pentru transmitere?',
      options: ['De-encapsulare', 'Multiplexare', 'Segmentare', 'Encapsulare', 'Routare'],
      correctIndex: 2,
    },
    {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele procedee reprezinta utilizarea mai multor sesiuni diferite de comunicare in acelasi timp?',
      options: ['De-encapsulare', 'Multiplexare', 'Segmentare', 'Encapsulare', 'Routare'],
      correctIndex: 1,
    },
  ]
});
