ACADOBRE_QUESTIONS.push({
  id: 'ospf',
    topic: 'OSPF',
    questions: [
    {
      type: 'open-ended',
      text: 'Cat de des sunt trimise rutele (LSAdvertisements) prin OSPF? (minute)',
      acceptedAnswers: ['30'],
    },
    {
      type: 'open-ended',
      text: 'Cat de des sunt trimise mesajele de hello prin OSPF? (secunde)',
      acceptedAnswers: ['10'],
    },
    {
      type: 'open-ended',
      text: 'Pentru cat timp sunt pastrati vecinii prin OSPF fara a primi hello (dead timer)? (secunde)',
      acceptedAnswers: ['40'],
    },
    {
      type: 'open-ended',
      text: 'Care este adresa IPv6 Multicast pentru toate routerele OSPF?',
      acceptedAnswers: ['ff02::5'],
    },
    {
      type: 'open-ended',
      text: 'Care este adresa IPv6 Multicast pentru DR/BDR in OSPF?',
      acceptedAnswers: ['ff02::6'],
    },
    {
      type: 'open-ended',
      text: 'Care este adresa IPv4 Multicast pentru toate routerele OSPF?',
      acceptedAnswers: ['224.0.0.5'],
    },
    {
      type: 'open-ended',
      text: 'Care este adresa IPv4 Multicast pentru DR/BDR in OSPF?',
      acceptedAnswers: ['224.0.0.6'],
    },
    {
      type: 'open-ended',
      text: 'Ce numar indica protocolul OSPF in campul IPv4 Protocol?',
      acceptedAnswers: ['89'],
    },
    {
      type: 'open-ended',
      text: 'Care este distanta administrativa pentru protocolul OSPF?',
      acceptedAnswers: ['110'],
    },
    {
      type: 'open-ended',
      text: 'Care este reference bandwidth-ul default pentru OSPF? (Mbps)',
      acceptedAnswers: ['100'],
    },
    {
      type: 'open-ended',
      text: 'Ce cod are o ruta invatata prin OSPF in tabela de rutare?',
      acceptedAnswers: ['O'],
    },
    {
      type: 'open-ended',
      text: 'Care este prioritatea default pentru interfetele OSPF?',
      acceptedAnswers: ['1'],
    },
    {
      type: 'open-ended',
      text: 'Ce tip de LSA este generat de fiecare router OSPF?',
      acceptedAnswers: ['1'],
    },
    {
      type: 'open-ended',
      text: 'Ce tip de LSA este generat de DR?',
      acceptedAnswers: ['2'],
    },
    {
      type: 'open-ended',
      text: 'Ce tip de LSA este generat de DR/BDR?',
      acceptedAnswers: ['5'],
    },
    {
      type: 'multiple-choice',
      text: 'In ce zona de memorie se salveaza structurile de date OSPF?',
      options: ['RAM', 'NVRAM', 'Flash', 'ROM', 'CPU', 'SSD'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca 2 rutere trebuie sa fie in aceeasi arie pentru a deveni vecini OSPF?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca 2 rutere trebuie sa aibe interfetele in acelasi subnet pentru a deveni vecini OSPF?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca 2 rutere pot deveni vecini OSPF daca au acelasi RID?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 1,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca 2 rutere pot deveni vecini OSPF daca au acelasi Process ID?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca 2 rutere pot deveni vecini OSPF daca nu au aceleasi timere pentru Hello si Dead?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 1,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca 2 rutere nu pot deveni vecini OSPF daca nu au aceleasi setari de MTU?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca 2 rutere pot deveni vecini OSPF daca nu au acelasi tip de retea OSPF?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 1,
    },
    {
      type: 'multiple-choice',
      text: 'Este adevarat ca 2 rutere nu pot deveni vecini OSPF daca nu au aceleasi setari de autentificare?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numesc interfetele pe care ruterele nu mai trimit doar mesaje specifice de rutare?',
      options: ['Interfete pasive', 'Interfete auto', 'Interfete down', 'Interfete trunk', 'Interfete acces'],
      correctIndex: 0, 
    },
    {
      type: 'multiple-choice',
      text: 'Care este algoritmul de rutare folosit de protocolul OSPF?',
      options: ['Djikstra', 'Bellman-Ford', 'Diffie-Hellman', 'Message-Digest5 ', 'Distance Vector', 'Link-State'],
      correctIndex: 0, 
    },
    {
      type: 'multiple-choice',
      text: 'Ce tip de protocol de rutare dinamica este OSPF?',
      options: ['Link-State', 'Djikstra', 'Path Vector', 'Message-Digest5', 'Distance Vector', 'Shortest Path First'],
      correctIndex: 0, 
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numeste metrica OSPF?',
      options: ['Cost', 'Djikstra', 'Path Vector', 'Hop Count', 'Bandwidth/Delay', 'Shortest Path First'],
      correctIndex: 0, 
    },
    {
      type: 'multiple-choice',
      text: 'Cum se calculeaza metrica OSPF?',
      options: ['Reference Bandwidth/Bandwidth', 'Djikstra', '(10^8)*Bandwidth', 'Hop Count*10', 'Bandwith/Delay', '1/Delay'],
      correctIndex: 0, 
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numesc mesajele OSPF prin care routerele afla despre vecinii lor?',
      options: ['Hello', 'Ola', 'LSAdvertisements', 'LSAck', 'LSU', 'LSR', 'DBD'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numesc mesajele OSPF prin care routerele ofera o descriere simplificata despre rutele pe care le au?',
      options: ['Hello', 'Ola', 'LSAdvertisements', 'LSAck', 'LSU', 'LSR', 'DBD'],
      correctIndex: 6,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numesc mesajele OSPF prin care routerele solicita informatii despre rutele pe care nu le au?',
      options: ['Hello', 'Ola', 'LSAdvertisements', 'LSAck', 'LSU', 'LSR', 'DBD'],
      correctIndex: 5,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numeste informatia din mesajele OSPF LSU?',
      options: ['Hello', 'Ola', 'LSAdvertisements', 'LSAck', 'LSU', 'LSR', 'DBD'],
      correctIndex: 2,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numesc mesajele OSPF prin care ruterele confirma ca au primit LSU?',
      options: ['Hello', 'Ola', 'LSAdvertisements', 'LSAck', 'LSU', 'LSR', 'DBD'],
      correctIndex: 3,
    },
    {
      type: 'multiple-choice',
      text: 'Care structura de date reprezinta harta LSA-urilor dintr-o arie OSPF?',
      options: ['Neighbor Table', 'LSDB', 'Adjacency Table', 'Routing Table', 'OSPF Table', 'ARP Table'],
      correctIndex: 1,
    },
    {
      type: 'multiple-choice',
      text: 'La ce nivel pe stiva OSI functioneaza protocolul OSPF?',
      options: ['Fizic', 'Legatura de Date', 'Retea', 'Transport', 'Sesiune', 'Prezentare', 'Aplicatie'],
      correctIndex: 2,
    },
    {
      type: 'multiple-choice',
      text: 'In ce structura de date isi mentine OSPF informatiile despre toti vecinii?',
      options: ['Neighbor Table', 'LSDB', 'Topology Table', 'Routing Table', 'OSPF Table', 'ARP Table'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'In ce structura de date se mentin vecinii cu care se ajunge in stadiul FULL in OSPF?',
      options: ['Adjacency Table', 'LSDB', 'Topology Table', 'Routing Table', 'OSPF Table', 'ARP Table'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'In ce structura de date isi mentine OSPF informatiile despre LSA-uri?',
      options: ['Neighbor Table', 'LSDB', 'Adjacency Table', 'Routing Table', 'OSPF Table', 'ARP Table'],
      correctIndex: 1,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se mai numeste LSBD in OSPF?',
      options: ['Adjacency Table', 'Neighbor Table', 'Topology Table', 'Routing Table', 'OSPF Table', 'ARP Table'],
      correctIndex: 2,
    },
    {
      type: 'multiple-choice',
      text: 'Cum ne mai putem referi la tabela de rutare?',
      options: ['Adjacency Table', 'Neighbor Table', 'Topology Table', 'Forwarding Database', 'OSPF Table', 'ARP Table'],
      correctIndex: 3,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numeste un router care trimite o ruta default prin OSPF?',
      options: ['Designated Router (DR)', 'Backup Designated Router (BDR)', 'DROther', 'Autonomous System Boundary Router (ASBR)', 'Area Border Router (ABR)', 'Master Router'],
      correctIndex: 3,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numeste un router care are interfete in cel putin 2 arii OSPF diferite?',
      options: ['Designated Router (DR)', 'Backup Designated Router (BDR)', 'DROther', 'Autonomous System Boundary Router (ASBR)', 'Area Border Router (ABR)', 'Master Router'],
      correctIndex: 4,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numeste routerul care initiaza schimbul de DBD?',
      options: ['Primary router', 'Designated Router (DR)', 'Backup Designated Router (BDR)', 'Slave Router', 'Autonomous System Boundary Router (ASBR)', 'Secondary Router', 'Master Router'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numesc routerele din aria 0?',
      options: ['Backbone router', 'Designated Router (DR)', 'Backup Designated Router (BDR)', 'Internal Router', 'Autonomous System Boundary Router (ASBR)', 'Secondary Router', 'Master Router'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numesc routerele cu toate interfetele in cadrul aceleasi arii?',
      options: ['Backbone router', 'Designated Router (DR)', 'Backup Designated Router (BDR)', 'Internal Router', 'Autonomous System Boundary Router (ASBR)', 'Secondary Router', 'Master Router'],
      correctIndex: 3,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numesc rutele in cadrul acleasi arii?',
      options: ['Inter-area route', 'Static Route', 'Intra-area route', 'External Route', 'Default Route', 'Floating Route'],
      correctIndex: 2,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se numesc rutele intre doua arii?',
      options: ['Inter-area route', 'Internal route', 'Intra-area route', 'External Route', 'Default Route', 'Floating Route'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Ce se intampla cand pica un DR?',
      options: ['BDR devine DR si se alege alt BDR', 'Necesita interventie manuala', 'BDR devine DROther si se alege alt DR', 'Se alege alt DR', 'Ruterele trimit toate LSA-urile catre BDR'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'In ce stadiu de operare OSPF devin ruterele vecini?',
      options: ['Down', 'Init', '2Way', 'ExStart', 'ExChange', 'Loading', 'Full'],
      correctIndex: 2,
    },
    {
      type: 'multiple-choice',
      text: 'În ce stadiu OSPF routerul trimite pachete Hello, dar nu a primit încă nimic de la vecini?',
      options: ['Down', 'Init', '2Way', 'ExStart', 'ExChange', 'Loading', 'Full'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'În ce stadiu OSPF un router primește un pachet Hello, dar propriul său Router ID nu se află în pachet?',
      options: ['Down', 'Init', '2Way', 'ExStart', 'ExChange', 'Loading', 'Full'],
      correctIndex: 1,
    },
    {
      type: 'multiple-choice',
      text: 'În ce stadiu de operare OSPF se realizează alegerea pentru DR și BDR pe rețelele de tip broadcast?',
      options: ['Down', 'Init', '2Way', 'ExStart', 'ExChange', 'Loading', 'Full'],
      correctIndex: 2,
    },
    {
      type: 'multiple-choice',
      text: 'În ce stadiu OSPF se stabilește relația Primary/Secondary și se alege numărul de secvență inițial pentru schimbul de date?',
      options: ['Down', 'Init', '2Way', 'ExStart', 'ExChange', 'Loading', 'Full'],
      correctIndex: 3,
    },
    {
      type: 'multiple-choice',
      text: 'În ce stadiu OSPF routerele fac schimb de pachete Database Description (DBD) pentru a-și compara bazele de date?',
      options: ['Down', 'Init', '2Way', 'ExStart', 'ExChange', 'Loading', 'Full'],
      correctIndex: 4,
    },
    {
      type: 'multiple-choice',
      text: 'În ce stadiu OSPF se trimit mesaje LSR (Link State Request) și LSU (Link State Update) pentru a obține informațiile lipsă?',
      options: ['Down', 'Init', '2Way', 'ExStart', 'ExChange', 'Loading', 'Full'],
      correctIndex: 5,
    },
    {
      type: 'multiple-choice',
      text: 'În ce stadiu OSPF bazele de date (LSDB) ale routerelor vecine sunt identice și sincronizarea este completă?',
      options: ['Down', 'Init', '2Way', 'ExStart', 'ExChange', 'Loading', 'Full'],
      correctIndex: 6,
    },
    {
      type: 'multiple-choice',
      text: 'În ce stadiu OSPF este un DROther cu DR sau BDR?',
      options: ['Down', 'Init', '2Way', 'ExStart', 'ExChange', 'Loading', 'Full'],
      correctIndex: 6,
    },
    {
      type: 'multiple-choice',
      text: 'În ce stadiu OSPF este un DROther cu DROther?',
      options: ['Down', 'Init', '2Way', 'ExStart', 'ExChange', 'Loading', 'Full'],
      correctIndex: 2,
    },
    {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele tipuri de retele OSPF este default pe interfete Ethernet?',
      options: ['Broadcast', 'Point-to-Point', 'Point-to-Multipoint', 'Autonomous System', 'Backbone', 'Ethernet', 'WirelessLAN'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele tipuri de retele OSPF alege DR si BDR?',
      options: ['Broadcast', 'Point-to-Point', 'Point-to-Multipoint', 'Autonomous System', 'Backbone', 'Ethernet', 'WirelessLAN'],
      correctIndex: 0,
    },
    {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele tipuri de retele OSPF este default pe interfete Serial?',
      options: ['Broadcast', 'Point-to-Point', 'Point-to-Multipoint', 'Autonomous System', 'Backbone', 'Ethernet', 'WirelessLAN'],
      correctIndex: 1,
    },
    {
      type: 'multiple-choice',
      text: 'Cum se mai numeste aria 0 in OSPF?',
      options: ['Broadcast', 'Point-to-Point', 'Point-to-Multipoint', 'Autonomous System', 'Backbone', 'Ethernet', 'WirelessLAN'],
      correctIndex: 4,
    },
    {
      type: 'multiple-choice',
      text: 'La ce arie trebuie sa fie conectate toate ariile in OSPF multi-area?',
      options: ['Broadcast', 'Point-to-Point', 'Point-to-Multipoint', 'Autonomous System', 'Backbone', 'Ethernet', 'WirelessLAN'],
      correctIndex: 4,
    },
    {
      type: 'multiple-choice-multi',
      text: 'Care sunt numele ruterelor asociate cu o alegere dintr-o retea OSPF?',
      options: ['Designated Router (DR)', 'Backup Designated Router (BDR)', 'DROther', 'Autonomous System Boundary Router (ASBR)', 'Area Border Router (ABR)', 'Master Router'],
      correctIndices: [0, 1, 2]
    },
    {
      type: 'multiple-choice-multi',
      text: 'Care dintre urmatoarele reprezinta tipuri de retele OSPF?',
      options: ['Broadcast', 'Point-to-Point', 'Point-to-Multipoint', 'Autonomous System', 'Backbone', 'Ethernet', 'WirelessLAN'],
      correctIndices: [0, 1, 2]
    },
    {
      type: 'label-order',
      text: 'Ordonati de la stanga la dreapta stadiile de operare OSPF',
      labels: ['Down', 'Init', '2Way', 'ExStart', 'ExChange', 'Loading', 'Full'],
      correctOrder: [0, 1, 2, 3, 4, 5, 6],
    },
    {
      type: 'label-order',
      text: 'Ordonati de la stanga la dreapta ordinea dupa care se alege DR si BDR:',
      labels: ['Cea mai mare prioritate pe interfata', 'Cel mai mare RID configurat manual', 'Cea mai mare adresa IP de pe o interfata Loopback', 'Cea mai mare adresa IP de pe o interfata fizica'],
      correctOrder: [0, 1, 2, 3],
    },
    ]
});
