ACADOBRE_QUESTIONS.push({
  id: 'physical_layer',
    topic: 'Nivelul Fizic',
    questions: [
      {
      type: 'image-order',
      text: 'Ordonati de la stanga la dreapta culorile firelor pentru standardul T568B de cablare.',
      images: [
        { src: 'questions/images/RJ_45/wire_white_orange.png', label: 'Alb-Porto' },
        { src: 'questions/images/RJ_45/wire_orange.png',       label: 'Porto' },
        { src: 'questions/images/RJ_45/wire_white_green.png',  label: 'Alb-Verde' },
        { src: 'questions/images/RJ_45/wire_blue.png',         label: 'Albastru' },
        { src: 'questions/images/RJ_45/wire_white_blue.png',   label: 'Alb-Albastru' },
        { src: 'questions/images/RJ_45/wire_green.png',        label: 'Verde' },
        { src: 'questions/images/RJ_45/wire_white_brown.png',  label: 'Alb-Maro' },
        { src: 'questions/images/RJ_45/wire_brown.png',        label: 'Maro' },
      ],
  
      correctOrder: [0, 1, 2, 3, 4, 5, 6, 7],
      },
      {
      type: 'image-order',
      text: 'Ordonati de la stanga la dreapta culorile firelor pentru standardul T568A de cablare.',
      images: [
        { src: 'questions/images/RJ_45/wire_white_green.png',   label: 'Alb-Verde' },
        { src: 'questions/images/RJ_45/wire_green.png',         label: 'Verde' },
        { src: 'questions/images/RJ_45/wire_white_orange.png',  label: 'Alb-Porto' },
        { src: 'questions/images/RJ_45/wire_blue.png',          label: 'Albastru' },
        { src: 'questions/images/RJ_45/wire_white_blue.png',    label: 'Alb-Albastru' },
        { src: 'questions/images/RJ_45/wire_orange.png',        label: 'Porto' },
        { src: 'questions/images/RJ_45/wire_white_brown.png',   label: 'Alb-Maro' },
        { src: 'questions/images/RJ_45/wire_brown.png',         label: 'Maro' },
      ],
  
      correctOrder: [0, 1, 2, 3, 4, 5, 6, 7],
      },
      {
      type: 'label-order',
      text: 'Puneti in ordine etapele de initializare ale unui router.',
      labels: ['POST', 'Bootstrap', 'IOS Image', 'Configuration file'],
      correctOrder: [0, 1, 2, 3],
      },
      {
      type: 'label-order',
      text: 'Puneti in ordine etapele de initializare ale unui switch.',
      labels: ['POST', 'Bootstrap', 'CPU', 'Flash file', 'IOS Image'],
      correctOrder: [0, 1, 2, 3, 4],
      },
      {
      type: 'matching',
      text: 'Asociati fiecare inceput de prompt cu modul de utilizator corespunzator:',
      subQuestions: [
        { text: 'Global Configuration', answer: '(config)#' },
        { text: 'Privileged EXEC', answer: '#' },
        { text: 'User EXEC', answer: '>' },
      ],
      options: ['>', '#', '(config)#', '!', '>#'],
      },
      {
      type: 'matching',
      text: 'Asociati tipul de metode de switching cu descrierea corespunzatoare:',
      subQuestions: [
        { text: 'Primeste si verifica erori pe intreg cadrul inainte de a trimite.', answer: 'Store-And-Forward' },
        { text: 'Primeste si verifica erori pe primii 64 de bytes inainte de a trimite.', answer: 'Fragment-Free' },
        { text: 'Primeste doar o parte din cadru inainte de a trimite. Are doua sub-categorii.', answer: 'Cut-Through' },
        { text: 'Trimite dupa ce citeste adresa MAC destinatie.', answer: 'Fast-Forward' },
      ],
      options: ['Store-And-Forward', 'Cut-Through', 'Adaptive switching', 'Fast-Forward', 'Fragment-Free'],
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care variante reprezinta versiuni de Cisco IOS?\nAlegeti 3 variante.',
      options: ['NX-OX', 'IOS K9', 'IOS XR', 'IOS XE', 'IOS ND'],
      correctIndices: [0, 2, 3], 
      },
      {
      type: 'multiple-choice',
      text: 'Unde se stocheaza configuratia de VLAN-uri normale?',
      options: ['ROM', 'NVRAM', 'RAM', 'Flash', 'CAM'],
      correctIndex: 3,
      },
      {
      type: 'multiple-choice',
      text: 'Unde se stocheaza configuratia de VLAN-uri extended?',
      options: ['ROM', 'NVRAM', 'RAM', 'Flash', 'CAM'],
      correctIndex: 2,
      },
      {
      type: 'multiple-choice',
      text: 'Ce mecanism este utilizat pentru a detecta coliziunile si a retransmite datele in cadrul unei retele Ethernet pe mediu partajat?',
      options: ['CSMA/CD', 'Token Ring', 'Collision Detection', 'CSMA/CA', 'Half-Duplex Collision Broadcast'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce mecanism este utilizat pentru a preveni coliziunile in cadrul unei retele wireless?',
      options: ['CSMA/CD', 'Token Ring', 'Collision Detection', 'CSMA/CA', 'Half-Duplex Collision Broadcast'],
      correctIndex: 3,
      },
      {
      type: 'multiple-choice',
      text: 'Unde se stocheaza configuratia curenta?',
      options: ['ROM', 'NVRAM', 'RAM', 'Flash', 'CAM'],
      correctIndex: 2,
      },
      {
      type: 'multiple-choice',
      text: 'Unde se stocheaza configuratia de startup?',
      options: ['ROM', 'NVRAM', 'RAM', 'Flash', 'CAM'],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Unde se stocheaza configuratia de bootstrap si POST?',
      options: ['ROM', 'NVRAM', 'RAM', 'Flash', 'CAM'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce tip de conexiune securizata la un dispozitiv de retea ar trebui sa folosim daca acesta se afla intr-o retea remote?',
      options: ['Global Configuration', 'Telnet', 'AUX', 'Consola', 'SSH'],
      correctIndex: 4, 
      },
      {
      type: 'multiple-choice',
      text: 'Unde se stocheaza configuratia de tabela MAC?',
      options: ['ROM', 'NVRAM', 'RAM', 'Flash', 'CAM'],
      correctIndex: 4,
      },
      {
      type: 'open-ended',
      text: 'Pana la ce distanta putem folosi cablurile UTP? (metri)',
      acceptedAnswers: ['100'],
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care variante pot reprezenta dezavantaje ale cablurilor pe baza de cupru?\nAlegeti 2 variante.',
      options: ['Interferente Electromagnetice', 'Interferente Radio', 'Mufare dificila', 'Securizare redusa', 'Pret scazut'],
      correctIndices: [0, 1], 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care variante pot reprezenta avantaje ale cablurilor pe baza de cupru?\nAlegeti 2 variante.',
      options: ['Interferente Electromagnetice', 'Interferente Radio', 'Pret scazut', 'Usor de instalat', 'Auto-MDIX'],
      correctIndices: [2, 3], 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care variante pot reprezenta dezavantaje ale cablurilor de fibra optica?\nAlegeti 2 variante.',
      options: ['Interferente Electromagnetice', 'Interferente Radio', 'Pret ridicat', 'Dificultate la instalat', 'Distanta redusa'],
      correctIndices: [2, 3], 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care variante pot reprezenta avantaje ale cablurilor de fibra optica?\nAlegeti 2 variante.',
      options: ['Interferente Electromagnetice', 'Imunitate la interferente', 'Pret ridicat', 'Dificultate la instalat', 'Distanta ridicata'],
      correctIndices: [1, 4], 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care variante NU reprezinta caracteristici ale mediului Wireless?\nAlegeti 3 variante.',
      options: ['Imunitate la interferente', 'Pret ridicat', 'Distanta redusa', 'Mobilitate Ridicata', 'Distanta ridicata'],
      correctIndices: [0, 1, 4], 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care dintre urmatoarele scenarii poate folosi un cablu straight-through? (fara Auto-MDIX)\nAlegeti 2 variante.',
      options: ['Switch-Switch', 'Switch-Router', 'Router-Router', 'PC-Switch', 'PC-PC'],
      correctIndices: [1, 3], 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care dintre urmatoarele scenarii poate folosi un cablu crossover? (fara Auto-MDIX)\nAlegeti 3 variante.',
      options: ['Switch-Switch', 'Switch-Router', 'Router-Router', 'PC-Switch', 'PC-PC'],
      correctIndices: [0, 2, 4], 
      },
      {
      type: 'multiple-choice',
      text: 'Ce tip de cablu folosim pentru conectarea la portul de consola?',
      options: ['Straight-Through', 'Rollover', 'Auto-MDIX', 'Crossover'],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Care este bandwidth-ul unui port FastEthernet? (Mbps)',
      options: ['100', '1000', '10', '10000'],
      correctIndex: 0,
      },
      {
      type: 'open-ended',
      text: 'Pana la ce distanta putem folosi cablurile de fibra optica? (kilometri)',
      acceptedAnswers: ['100'],
      },
      {
      type: 'multiple-choice',
      text: 'Care caracteristica defineste viteza teoretica la care poate ajunge o legatura?',
      options: ['Throughput', 'Goodput', 'Bandwidth', 'Latenta'],
      correctIndex: 2,
      },
      {
      type: 'multiple-choice',
      text: 'Care caracteristica defineste viteza efectiva la care ajunge o legatura?',
      options: ['Throughput', 'Goodput', 'Bandwidth', 'Latenta'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care caracteristica defineste durata de timp pentru comunicarea dispozitivelor?',
      options: ['Throughput', 'Goodput', 'Bandwidth', 'Latenta'],
      correctIndex: 3,
      },
      {
      type: 'multiple-choice',
      text: 'Care caracteristica defineste datele utilizabile care circula in retea?',
      options: ['Throughput', 'Goodput', 'Bandwidth', 'Latenta'],
      correctIndex: 1,
      },
    ]
});
