ACADOBRE_QUESTIONS.push({
  id: 'porturi',
    topic: 'Porturi Transport',
    questions: [
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru FTP control?',
        acceptedAnswers: ['20 TCP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru FTP Data?',
        acceptedAnswers: ['21 TCP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru SSH?',
        acceptedAnswers: ['22 TCP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru Telnet?',
        acceptedAnswers: ['23 TCP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru SMTP?',
        acceptedAnswers: ['25 TCP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru TACACS+?',
        acceptedAnswers: ['49 TCP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru DNS?',
        acceptedAnswers: ['53 TCP UDP', '53 UDP TCP'],
        hint: 'Exemplu de raspuns: "12 DBR URS".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru DHCPv4 Server?',
        acceptedAnswers: ['67 UDP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru DHCPv4 Client?',
        acceptedAnswers: ['68 UDP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru TFTP?',
        acceptedAnswers: ['69 UDP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru HTTP?',
        acceptedAnswers: ['80 TCP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru POP3?',
        acceptedAnswers: ['110 TCP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru NTP?',
        acceptedAnswers: ['123 UDP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru IMAP?',
        acceptedAnswers: ['143 TCP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru SNMP Agent?',
        acceptedAnswers: ['161 UDP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru SNMP Manager?',
        acceptedAnswers: ['162 UDP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru BGP?',
        acceptedAnswers: ['179 TCP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru HTTPS?',
        acceptedAnswers: ['443 TCP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru Syslog?',
        acceptedAnswers: ['514 UDP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru DHCPv6 Client?',
        acceptedAnswers: ['546 UDP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru DHCPv6 Server?',
        acceptedAnswers: ['547 UDP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru RADIUS Authentication & Authorization?',
        acceptedAnswers: ['1812 UDP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru RADIUS Accounting?',
        acceptedAnswers: ['1813 UDP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru HSRP?',
        acceptedAnswers: ['1985 UDP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru GLBP?',
        acceptedAnswers: ['3222 UDP'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'multiple-choice-multi',
        text: 'Care dintre urmatoarele reprezinta caracteristicile protocolului TCP?',
        options: ['Connection-oriented', 'Flow control', 'Reliability', 'Best-Effort Delievery', 'Congestion control', 'Three-way Handshake'],
      correctIndices: [0, 1, 2],
      },
      {
        type: 'multiple-choice-multi',
        text: 'Care dintre urmatoarele reprezinta caracteristicile protocolului UDP?',
        options: ['Connectionless', 'Best-Effort', 'Congestion control', 'Stateless Communication'],
      correctIndices: [0, 1],
      },
      {
        type: 'multiple-choice',
        text: 'Care dintre urmatoarele protocoale foloseste atat TCP cat si UDP?',
        options: ['DNS', 'NAT', 'VoIP', 'SMTP', 'FTP'],
      correctIndex: 0,
      },
      {
        type: 'open-ended',
        text: 'Care este range-ul de porturi well-known?',
        acceptedAnswers: ['0-1023'],
        hint: 'Exemplu de raspuns: "x-y".',
      },
      {
        type: 'open-ended',
        text: 'Care este range-ul de porturi inregistrate?',
        acceptedAnswers: ['1024-49151'],
        hint: 'Exemplu de raspuns: "x-y".',
      },
      {
        type: 'open-ended',
        text: 'Care este range-ul de porturi efemere?',
        acceptedAnswers: ['49152-65535'],
        hint: 'Exemplu de raspuns: "x-y".',
      },
    ]
});
