ACADOBRE_QUESTIONS.push({
  id: 'qos',
    topic: 'Quality of Service',
    questions: [
  {
    type: 'multiple-choice',
    text: 'Care dintre următoarele principii ale retelisticii asigura ca traficul unei retele este trimis intr-o ordine ierarhica?',
    options: [
      'Quality of Service',
      'Redundancy',
      'Fault Tolerance',
      'Security',
      'Scalability',
      'Confidentiality',
      'Priority Assurance'
    ],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Într-o rețea convergentă, în care se găsește trafic de voce, video și date, de ce este QoS important? (Acadnet)',
    options: ['echipamentele vechi nu sunt capabile să transmită trafic de voce/video fără QoS', 'Traficul de voce și video este mai sensibil la latență', 'Toate răspunsurile sunt corecte', 'Pachetele de date sunt sensibile la jitter', 'traficul de date trebuie să aibă prioritate', 'Ca traficul de browsing și email să aibă aceeași prioritate ca traficul de voce, date și video'],
    correctIndex: 1
  },
  {
    type: 'multiple-choice',
    text: 'Ce reprezinta termenul de congestie intr-o retea?',
    options: [
      'Traficul de intrare pe dispozitivele de retea depaseste capacitatea dispozitivului de a trimite',
      'Traficul de iesire pe dispozitivele de retea depaseste capacitatea dispozitivului de a primi',
      'Erorile produse la nivelul unui dispozitiv atunci cand se modifica imaginea IOS',
      'Daune fizice asupra dispozitivelor ce impiedica trimiterea datelor',
      'Lipsa posibilitatii pentru a adauga alte dispozitive pe parcurs ce reteaua creste in utilizatori',
      'Deconectarea interfetei care conecta reteaua la Internet',
    ],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Ce reprezinta termenul de bandwidth intr-o retea?',
    options: [
      'Numarul teoretic de biti ce poate circula pe o legatura intr-o secunda',
      'Numarul efectiv de biti care circula pe o legatura intr-o secunda',
      'Durata ca datele trimise sa ajunga de la sursa la destinatie',
      'O crestere in timpul in care datele trimise circula prin retea',
      'Variatia delay-ului din retea',
      'Numarul de biti care il intereseaza pe utilizator care circula pe o legatura intr-o secunda',
    ],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Ce reprezinta termenul de delay intr-o retea?',
    options: [
      'Numarul teoretic de biti ce poate circula pe o legatura intr-o secunda',
      'Numarul efectiv de biti care circula pe o legatura intr-o secunda',
      'Durata ca datele trimise sa ajunga de la sursa la destinatie',
      'O crestere in timpul in care datele trimise circula prin retea',
      'Variatia delay-ului din retea',
      'Numarul de biti care il intereseaza pe utilizator care circula pe o legatura intr-o secunda',
    ],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice',
    text: 'Ce reprezinta termenul de jitter intr-o retea?',
    options: [
      'Numarul teoretic de biti ce poate circula pe o legatura intr-o secunda',
      'Numarul efectiv de biti care circula pe o legatura intr-o secunda',
      'Durata ca datele trimise sa ajunga de la sursa la destinatie',
      'O crestere in timpul in care datele trimise circula prin retea',
      'Variatia delay-ului din retea',
      'Numarul de biti care il intereseaza pe utilizator care circula pe o legatura intr-o secunda',
    ],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Ce reprezinta termenul de shaping in cadrul QoS?',
    options: [
      'Salvarea pachetelor intr-un buffer pentru a le trimite cu o valoare constanta de delay',
      'Aruncarea pachetelor care depasesc o limita setata de utilizator, sub limita fizica',
      'Aruncarea ultimelor pachete primite atunci cand sunt primite intr-o coada plina',
      'Comunicarea nu poate admite pierderi de pachete',
      'Variatia delay-ului din retea',
      'Trimiterea unor mesaje pentru a aloca resurse pentru QoS',
    ],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Ce reprezinta termenul de policing in cadrul QoS?',
    options: [
      'Salvarea pachetelor intr-un buffer pentru a le trimite cu o valoare constanta de delay',
      'Aruncarea pachetelor care depasesc o limita setata de utilizator, sub limita fizica',
      'Aruncarea ultimelor pachete primite atunci cand sunt primite intr-o coada plina',
      'Comunicarea nu poate admite pierderi de pachete',
      'Variatia delay-ului din retea',
      'Trimiterea unor mesaje pentru a aloca resurse pentru QoS',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Ce reprezinta termenul de tail drop in cadrul QoS?',
    options: [
      'Salvarea pachetelor intr-un buffer pentru a le trimite cu o valoare constanta de delay',
      'Aruncarea pachetelor care depasesc o limita setata de utilizator, sub limita fizica',
      'Aruncarea ultimelor pachete primite atunci cand sunt primite intr-o coada plina',
      'Comunicarea nu poate admite pierderi de pachete',
      'Variatia delay-ului din retea',
      'Trimiterea unor mesaje pentru a aloca resurse pentru QoS',
    ],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'Ce reprezinta termenul de fragile flows in cadrul QoS?',
    options: [
      'Salvarea pachetelor intr-un buffer pentru a le trimite cu o valoare constanta de delay',
      'Aruncarea pachetelor care depasesc o limita setata de utilizator, sub limita fizica',
      'Aruncarea ultimelor pachete primite atunci cand sunt primite intr-o coada plina',
      'Comunicarea nu poate admite pierderi de pachete',
      'Variatia delay-ului din retea',
      'Trimiterea unor mesaje pentru a aloca resurse pentru QoS',
    ],
    correctIndex: 3,
  },
// delay types
  {
    type: 'multiple-choice',
    text: 'Care este cauza delay-ului de tip Code delay?',
    options: [
      'Timpul necesar ca datele sa fie comprimate la sursa',
      'Timpul necesar ca pachetele sa fie encapsulate',
      'Timpul necesar pentru a trimite cadrul pe mediul fizic',
      'Timpul necesar pentru a salva pachetele intr-un buffer pentru a le trimite cu o valoare constanta de delay',
      'Timpul pe care pachetul il petrece in coada inainte de a fi trimis',
      'Timpul necesar pentru ca pachetul sa ajunga de la sursa la destinatie',
    ],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Care este cauza delay-ului de tip Packetization delay?',
    options: [
      'Timpul necesar ca datele sa fie comprimate la sursa',
      'Timpul necesar ca pachetele sa fie encapsulate',
      'Timpul necesar pentru a trimite cadrul pe mediul fizic',
      'Timpul necesar pentru a salva pachetele intr-un buffer pentru a le trimite cu o valoare constanta de delay',
      'Timpul pe care pachetul il petrece in coada inainte de a fi trimis',
      'Timpul necesar pentru ca pachetul sa ajunga de la sursa la destinatie',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Care este cauza delay-ului de tip Serialization delay?',
    options: [
      'Timpul necesar ca datele sa fie comprimate la sursa',
      'Timpul necesar ca pachetele sa fie encapsulate',
      'Timpul necesar pentru a trimite cadrul pe mediul fizic',
      'Timpul necesar pentru a salva pachetele intr-un buffer pentru a le trimite cu o valoare constanta de delay',
      'Timpul pe care pachetul il petrece in coada inainte de a fi trimis',
      'Timpul necesar pentru ca pachetul sa ajunga de la sursa la destinatie',
    ],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'Care este cauza delay-ului de tip De-Jitter delay?',
    options: [
      'Timpul necesar ca datele sa fie comprimate la sursa',
      'Timpul necesar ca pachetele sa fie encapsulate',
      'Timpul necesar pentru a trimite cadrul pe mediul fizic',
      'Timpul necesar pentru a salva pachetele intr-un buffer pentru a le trimite cu o valoare constanta de delay',
      'Timpul pe care pachetul il petrece in coada inainte de a fi trimis',
      'Timpul necesar pentru ca pachetul sa ajunga de la sursa la destinatie',
    ],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice',
    text: 'Care este cauza delay-ului de tip Queueing delay?',
    options: [
      'Timpul necesar ca datele sa fie comprimate la sursa',
      'Timpul necesar ca pachetele sa fie encapsulate',
      'Timpul necesar pentru a trimite cadrul pe mediul fizic',
      'Timpul necesar pentru a salva pachetele intr-un buffer pentru a le trimite cu o valoare constanta de delay',
      'Timpul pe care pachetul il petrece in coada inainte de a fi trimis',
      'Timpul necesar pentru ca pachetul sa ajunga de la sursa la destinatie',
    ],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Care este cauza delay-ului de tip Propagation delay?',
    options: [
      'Timpul necesar ca datele sa fie comprimate la sursa',
      'Timpul necesar ca pachetele sa fie encapsulate',
      'Timpul necesar pentru a trimite cadrul pe mediul fizic',
      'Timpul necesar pentru a salva pachetele intr-un buffer pentru a le trimite cu o valoare constanta de delay',
      'Timpul pe care pachetul il petrece in coada inainte de a fi trimis',
      'Timpul necesar pentru ca pachetul sa ajunga de la sursa la destinatie',
    ],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'Ce mecanism QoS este folosit in compensarea pentru jitter?',
    options: [
      'Playout Delay Buffer',
      'De-jitter Buffer',
      'De-Jitter Queue',
      'Playout Delay Queue',
      'Constant Delay Buffer',
    ],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Selectati tipurile de delay fixat (Selectaţi 4 variante)',
    options: [
      'Code Delay',
      'Packetization Delay',
      'Serialization Delay',
      'De-jitter Delay',
      'Queueing Delay',
      'Propagation Delay',
      'Communication Delay'
    ],
    correctIndices: [0, 1, 2, 3],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Selectati tipurile de delay variabil (Selectaţi 2 variante)',
    options: [
      'Code Delay',
      'Packetization Delay',
      'Serialization Delay',
      'De-jitter Delay',
      'Queueing Delay',
      'Propagation Delay',
      'Communication Delay'
    ],
    correctIndices: [4, 5],
  },
// traffic characteristics
  {
    type: 'multiple-choice-multi',
    text: 'Alegeti caracteristicile traficului de voce (Selectaţi 5 variante)',
    options: [
      'Necesita cea mai mare prioritate',
      'Foloseste Real-Time Transport Protocol (RTP) prin UDP',
      'Este smooth (numarul de biti trimisi pe secunda este constant)',
      'Este benign (nu consuma multa latime de banda)',
      'Este sensibil la pierderi de pachete si intarzieri in trimitere',
      'Foloseste Real-Time Streaming Protocol (RTSP) prin UDP',
      'Este bursty (numarul de biti trimisi pe secunda variaza)',
      'Este greedy (consuma multa latime de banda)'
    ],
    correctIndices: [0, 1, 2, 3, 4],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Alegeti parametrii necesari pentru traficul de voce (Selectaţi 4 variante)',
    options: [
      'Latenta <= 150 ms',
      'Jitter <= 30 ms',
      'Loss <= 1%',
      'Bandwidth 30-128 Kbps',
      'Latenta <= 200-400 ms',
      'Jitter <= 30-50 ms',
      'Loss <= 0.1-1%',
      'Bandwidth 384-2000+ Kbps',
    ],
    correctIndices: [0, 1, 2, 3],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Alegeti caracteristicile traficului de video (Selectaţi 5 variante)',
    options: [
      'Necesita cea mai mare prioritate dupa traficul de voce',
      'Foloseste Real-Time Transport Protocol (RTP) prin UDP',
      'Este smooth (numarul de biti trimisi pe secunda este constant)',
      'Este benign (nu consuma multa latime de banda)',
      'Este sensibil la pierderi de pachete si intarzieri in trimitere',
      'Foloseste Real-Time Streaming Protocol (RTSP) prin UDP',
      'Este bursty (numarul de biti trimisi pe secunda variaza)',
      'Este greedy (consuma multa latime de banda)'
    ],
    correctIndices: [0, 4, 5, 6, 7],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Alegeti parametrii necesari pentru traficul video (Selectaţi 4 variante)',
    options: [
      'Latenta <= 150 ms',
      'Jitter <= 30 ms',
      'Loss <= 1%',
      'Bandwidth 30-128 Kbps',
      'Latenta <= 200-400 ms',
      'Jitter <= 30-50 ms',
      'Loss <= 0.1-1%',
      'Bandwidth 384-2000+ Kbps',
    ],
    correctIndices: [4, 5, 6, 7],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Alegeti caracteristicile traficului de date (Selectaţi 4 variante)',
    options: [
      'Poate folosi atat TCP cat si UDP',
      'Poate fi atat smooth cat si bursty',
      'Este smooth (numarul de biti trimisi pe secunda este constant)',
      'Poate fi atat benign cat si greedy',
      'Nu este sensibil la pierderi de pachete si intarzieri in trimitere',
      'Foloseste Real-Time Streaming Protocol (RTSP) prin UDP',
      'Este greedy (consuma multa latime de banda)'
    ],
    correctIndices: [0, 1, 3, 4],
  },
  {
    type: 'open-ended',
    text: 'Care este portul si protocolul de nivel 4 pentru Real-Time Streaming Protocol (RTSP)?',
    acceptedAnswers: ['554 UDP', '554 udp'],
    hint: 'Exemplu de raspuns: "12 DBR".',
  },
//queueing algorithms
  {
    type: 'multiple-choice-multi',
    text: 'Alegeti algoritmii QoS de ordonare in coada (Selectaţi 4 variante)',
    options: [
      'First-In, First-Out (FIFO)',
      'Weighted Fair Queueing (WFQ)',
      'Class Based Weighted Fair Queueing (CBWFQ)',
      'Low Latency Queueing (LLQ)',
      'Priority Based Queueing (PBQ)',
      'Real Time Queueing (RTQ)',
      'More Need, More Get (MNMG)'
    ],
    correctIndices: [0, 1, 2, 3],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care din variantele de mai jos sunt algoritmi folosiţi pentru QoS? (Alegeţi 3 variante) (Acadnet)',
    options: ['IPsec', 'WFQ', 'LLQ', 'OSPF', 'RSA', 'FIFO'],
    correctIndices: [1, 2, 5],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care sunt functiile algoritmului FIFO? (Selectaţi 2 variante)',
    options: [
      'Pachetele sunt salvate si trimise in ordinea in care sunt primite',
      'Este cel mai simplu algoritm',
      'Este un algoritm automatizat',
      'Separa traficul in clase definite de utilizator folosind ACL-uri, interfete sau protocoale',
      'Filtreaza traficul pe baza adreselor destinatie',
      'Creeaza o coada separata pentru traficul de voce',
      'Aplica o prioritate pachetelor pe baza cerintei de bandwidth',
    ],
    correctIndices: [0, 1],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care sunt functiile algoritmului WFQ? (Selectaţi 4 variante)',
    options: [
      'Pachetele sunt salvate si trimise in ordinea in care sunt primite',
      'Este cel mai simplu algoritm',
      'Este un algoritm automatizat',
      'Separa traficul in clase definite de utilizator folosind ACL-uri, interfete sau protocoale',
      'Filtreaza traficul pe baza adreselor destinatie',
      'Creeaza o coada separata pentru traficul de voce',
      'Aplica o prioritate pachetelor pe baza cerintei de bandwidth',
      'Nu ofera optiuni de clasificare a traficului'
    ],
    correctIndices: [2, 4, 6, 7],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care sunt functiile algoritmului CBWFQ? (Selectaţi 2 variante)',
    options: [
      'Pachetele sunt salvate si trimise in ordinea in care sunt primite',
      'Este cel mai simplu algoritm',
      'Fiecare clasa de trafic reprezinta o coada FIFO',
      'Separa traficul in clase definite de utilizator folosind ACL-uri, interfete sau protocoale',
      'Filtreaza traficul pe baza adreselor destinatie',
      'Creeaza o coada separata pentru traficul de voce',
      'Aplica o prioritate pachetelor pe baza cerintei de bandwidth',
      'Nu ofera optiuni de clasificare a traficului'
    ],
    correctIndices: [2, 3],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care sunt functiile algoritmului LLQ? (Selectaţi 3 variante)',
    options: [
      'Pachetele sunt salvate si trimise in ordinea in care sunt primite',
      'Este cel mai simplu algoritm',
      'Fiecare clasa de trafic rerezinta o coada FIFO',
      'Separa traficul in clase definite de utilizator folosind ACL-uri, interfete sau protocoale',
      'Filtreaza traficul pe baza adreselor destinatie',
      'Creeaza o coada separata pentru traficul de voce',
      'Aplica o prioritate pachetelor pe baza cerintei de bandwidth',
      'Nu ofera optiuni de clasificare a traficului'
    ],
    correctIndices: [2, 3, 5],
  },
//models
  {
    type: 'multiple-choice-multi',
    text: 'Care sunt cele trei modele ale QoS? (Alegeți 3 variante) (Acadnet)',
    options: [
      'Modelul Resource Management',
      'Modelul Integrated Services',
      'Modelul Policy-Based Services',
      'Modelul Differentiated Services',
      'Modelul Best-Effort',
      'Modelul Flow Prioritization',
    ],
    correctIndices: [1, 3, 4],
  },
  {
    type: 'multiple-choice',
    text: 'Care model QoS nu necesită mecanisme QoS speciale? (Acadnet)',
    options: [
      'WFQ',
      'Best-Effort',
      'Differential Services',
      'Integrated Services',
      'CBWFQ',
      'LLQ'
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Care model QoS este connection-oriented?',
    options: [
      'Best-Effort',
      'IntServ',
      'DiffServ',
      'FIFO',
      'LLQ',
      'RTQ',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Care model QoS foloseste Resource Reservation Protocol (RSVP)?',
    options: [
      'Best-Effort',
      'IntServ',
      'DiffServ',
      'FIFO',
      'LLQ',
      'RTQ',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Ce se intampla daca modelul IntServ determina ca reteaua nu dispune de resursele necesare?',
    options: [
      'Salveaza traficul intr-un buffer',
      'Nu trimite traficul',
      'Trimite traficul in pachete mai mici',
      'Trimite traficul folosind DiffServ',
      'Trimite traficul folosind Best-Effort',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Care model QoS clasifica traficul din retea?',
    options: [
      'Best-Effort',
      'IntServ',
      'DiffServ',
      'FIFO',
      'LLQ',
      'RTQ',
    ],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'In care model QoS dispozitivele de final nu cunosc implementarea QoS?',
    options: [
      'Best-Effort',
      'IntServ',
      'DiffServ',
      'FIFO',
      'LLQ',
      'RTQ',
    ],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'In care model QoS serviciul de QoS este implementat la fiecare hop?',
    options: [
      'Best-Effort',
      'IntServ',
      'DiffServ',
      'FIFO',
      'LLQ',
      'RTQ',
    ],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care sunt avantajele modelului QoS Best-Effort? (Selectaţi 2 variante)',
    options: [
      'Este cel mai scalabil model',
      'Usurinta in configurare',
      'Aloca resursele necesare inainte ca dispozitivele sa comunice',
      'Poate diferentia nevoile traficului in QoS',
      'Creeaza o noua coada pe dispozitive'
    ],
    correctIndices: [0, 1],
  },
  {
    type: 'multiple-choice',
    text: 'Care este avantajul modelului QoS IntServ?',
    options: [
      'Este cel mai scalabil model',
      'Usurinta in configurare',
      'Aloca resursele necesare inainte ca dispozitivele sa comunice',
      'Poate diferentia nevoile traficului in QoS',
      'Creeaza o noua coada pe dispozitive'
    ],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care sunt avantajele modelului QoS DiffServ? (Alegeți 2 variante)',
    options: [
      'Scalabilitate Ridicata',
      'Usurinta in configurare',
      'Aloca resursele necesare inainte ca dispozitivele sa comunice',
      'Poate diferentia nevoile traficului in QoS',
      'Creeaza o noua coada pe dispozitive'
    ],
    correctIndices: [0, 3],
  },
  {
    type: 'multiple-choice',
    text: 'Care dintre următoarele variante este un model de implementare QoS? (Acadnet)',
    options: [
      'Low-effort model',
      'Differentiated Protocols',
      'Prioritized Services',
      'niciuna din variante',
      'Integrated Services',
      'toate variantele'
    ],
    correctIndex: 4,
  },
// qos tools
  {
    type: 'label-order',
    text: 'Puneti in ordine etapele procesului QoS complet:',
    labels: [
      'Receiving traffic',
      'Routing and Network Processes',
      'Classification',
      'Marking',
      'Policing and Selective Dropping',
      'Queueing',
      'Scheduling and Shaping',
      'Sending Traffic',
    ],
    correctOrder: [0, 1, 2, 3, 4, 5, 6, 7],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Cum se poate realiza clasificarea in cadrul QoS? (Alegeti 2 variante)',
    options: [
      'Folosind valori in headerele mesajelor',
      'Folosind Access Control Lists (ACLs)',
      'Folosind Class Maps',
      'Folosind Weighted Random Early Detection (WRED)',
      'Folosind WFQ, CBWFQ sau LLQ pentru a creste spatiul din buffer',
    ],
    correctIndices: [1, 2],
  },
  {
    type: 'multiple-choice',
    text: 'Cum se poate realiza marcarea(etichetarea) in cadrul QoS?',
    options: [
      'Folosind valori in headerele mesajelor',
      'Folosind Access Control Lists (ACLs)',
      'Folosind Class Maps',
      'Folosind Weighted Random Early Detection (WRED)',
      'Folosind WFQ, CBWFQ sau LLQ pentru a creste spatiul din buffer',
    ],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Cum se pot evita congestiile TCP in cadrul QoS?',
    options: [
      'Folosind valori in headerele mesajelor',
      'Folosind Access Control Lists (ACLs)',
      'Folosind Class Maps',
      'Folosind Weighted Random Early Detection (WRED)',
      'Folosind WFQ, CBWFQ sau LLQ pentru a creste spatiul din buffer',
    ],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice',
    text: 'Cum se pot evita pierderile de pachete in cadrul QoS?',
    options: [
      'Folosind valori in headerele mesajelor',
      'Folosind Access Control Lists (ACLs)',
      'Folosind Class Maps',
      'Folosind Weighted Random Early Detection (WRED)',
      'Folosind WFQ, CBWFQ sau LLQ pentru a creste spatiul din buffer',
    ],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Ce se intampla atunci cand sunt primite pachete intr-o coada plina?',
    options: [
      'Traficul primit este trimis imediat',
      'Traficul nou venit este aruncat',
      'Traficul din coada se arunca, golind coada',
      'Traficul este adaugat in coada in ciuda limitei depasite',
      'Traficul primit este adaugat intr-o noua coada',
    ],
    correctIndex: 1,
  },
// marking
      {
      type: 'matching',
      text: 'Asociati tehnologia de encapsulare cu numele campului dedicat pentru marcarea QoS:',
      subQuestions: [
        { text: 'VLAN', answer: 'Class of Service' },
        { text: 'Wi-Fi', answer: 'Traffic Identifier' },
        { text: 'MPLS', answer: 'Experimental' },
        { text: 'IPv4', answer: 'Type of Service' },
        { text: 'IPv6', answer: 'Traffic Class' },
      ],
      options: ['Class of Service', 'Traffic Class', 'Traffic Identifier', 'Experimental', 'Type of Service'],
      },
      {
        type: 'open-ended',
        text: 'Cati biti au campurile dedicate pentru marcarea QoS la Layer 2?',
        acceptedAnswers: ['3'],
      },
      {
        type: 'open-ended',
        text: 'Cati biti au campurile dedicate pentru marcarea QoS la Layer 3?',
        acceptedAnswers: ['8'],
      },
      {
        type: 'multiple-choice',
        text: 'Unde ar trebui realizata marcarea traficului?',
        options: [
          'Cat mai aproape de sursa traficului',
          'Cat mai aproape de destinatia traficului',
          'Cat mai aproape de router',
          'Cat mai aproape de conectivitatea cu ISP-ul',
          'Cat mai aproape de switch-ul multilayer',
        ],
        correctIndex: 0,
      },
      {
        type: 'multiple-choice',
        text: 'Este adevarat ca marcarea traficului pe legaturi Ethernet functioneaza si in afara 802.1q?',
        options: [
          'Adevarat',
          'Fals',
        ],
        correctIndex: 1,
      },
      {
        type: 'open-ended',
        text: 'Care este numele standardului pentru prioritizare QoS in cadrul 802.1q?',
        acceptedAnswers: ['802.1p', '802.1P'],
      },
      {
        type: 'label-order',
        text: 'Ordonați, de sus în jos, în funcție de CoS Value (Class of Service Value), tipul de pachete. (Acadnet)',
        hint: 'pentru Reserved puneti in ordine de la mic la mare, ca sa poata fi deosebite de checker'
        labels: [
          'Videoconferencing',
          'Best-Effort Data',
          'Call Signaling',
          'Reserved (1)',
          'Medium-Priority Data',
          'Reserved (2)',
          'High-Priority Data',
          'Voice bearer (voice traffic)',
        ],
        correctOrder: [1, 4, 6, 2, 0, 7, 3, 5],
      },
      {
        type: 'multiple-choice-multi',
        text: 'Care doua subcampuri ale unui antet alcatuiesc campul Type of Service pentru marcare QoS de Layer 3?',
        options: [
          'Differentiated Services Code Point (DSCP)',
          'Explicit Congestion Notification (ECN)',
          'Type of Service (ToS)',
          'Folosind Weighted Random Early Detection (WRED)',
          'Traffic Identifier (TID)',
          'IP Precedence (IPP)'
        ],
        correctIndices: [0, 1],
      },
      {
        type: 'multiple-choice',
        text: 'Ce camp preceda campul ToS pentru QoS in antetele de Layer 3?',
        options: [
          'Differentiated Services Code Point (DSCP)',
          'Explicit Congestion Notification (ECN)',
          'Type of Service (ToS)',
          'Folosind Weighted Random Early Detection (WRED)',
          'Traffic Identifier (TID)',
          'IP Precedence (IPP)'
        ],
        correctIndex: 5,
      },
      {
        type: 'multiple-choice-multi',
        text: 'Care sunt categoriile de valori DSCP? (Alegeţi 3 variante)',
        options: [
          'Best-Effort (BE)',
          'Expedited Forwarding (EF)',
          'Assured Forwarding (AF)',
          'Express Forwarding (EF)',
          'Low-latency Forwarding (LF)',
          'Reliable Forwarding (RF)'
        ],
        correctIndices: [0, 1, 2],
      },
      {
        type: 'multiple-choice',
        text: 'Care tip de forwarding DSCP este recomandat sa fie folosit pentru traficul de voce?',
        options: [
          'Best-Effort (BE)',
          'Expedited Forwarding (EF)',
          'Assured Forwarding (AF)',
          'Express Forwarding (EF)',
          'Low-latency Forwarding (LF)',
          'Reliable Forwarding (RF)'
        ],
        correctIndex: 1,
      },
      {
        type: 'open-ended',
        text: 'Ce valoare DSCP implica Best-Effort Forwarding?',
        acceptedAnswers: ['0'],
      },
      {
        type: 'open-ended',
        text: 'Ce valoare DSCP implica Expedited Forwarding?',
        acceptedAnswers: ['46'],
      },
      {
      type: 'matching',
      text: 'Asociati numarul de ordine al bitilor (de la stanga la dreapta) din campul DSCP pentru Assured Forwarding (AF) si ce indica fiecare:',
      subQuestions: [
        { text: 'Bitul 1', answer: 'Clasa' },
        { text: 'Bitul 2', answer: 'Clasa' },
        { text: 'Bitul 3', answer: 'Clasa' },
        { text: 'Bitul 4', answer: 'Drop Precedence' },
        { text: 'Bitul 5', answer: 'Drop Precedence' },
        { text: 'Bitul 6', answer: 'Mereu setat pe 0' },
      ],
      options: ['Clasa', 'Drop Precedence', 'Mereu setat pe 0'],
      },
    ]
});