ACADOBRE_QUESTIONS.push({
  id: 'security',
    topic: 'Securitate',
    questions: [
      {
      type: 'open-ended',
      text: 'Care este codul pentru standardul IEEE pentru autentificare?',
      acceptedAnswers: ['802.1X', '802.1x'],
      },
      {
      type: 'multiple-choice',
      text: 'De la ce vine acronimul AAA?',
      options: ['Authentication, Authorization, Accounting',
                'Authorization, Accepting, Accessing',
                'Authentication, Addressing, Accounting',
                'Accessing, Accepting, Applying',
                'Aspiring Actual Address'
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care din componentele AAA se ocupa cu verificarea identitatii unui utilizator?',
      options: ['Authentication',
                'Authorization',
                'Accounting',
                'Applying',
                'Addressing'
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele reprezinta o metoda simpla de securizare la nivel fizic?',
      options: ['Oprirea porturilor nefolosite',
                'Activarea unui ngFirewall',
                'Folosirea unei adrese MAC unice',
                'Folosirea unei adrese IP unice',
                'Oprirea sesiunilor TCP nefolosite'
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce aparat este folosit pentru securizarea e-mailurilor cu continut malitios?',
      options: ['ESA',
                'Firewall',
                'WSA',
                'ngFirewall',
                'VPN',
                'IPS',
                'IDS',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce aparat este folosit pentru securizarea paginilor web cu continut malitios?',
      options: ['ESA',
                'Firewall',
                'WSA',
                'ngFirewall',
                'VPN',
                'IPS',
                'IDS',
               ],
      correctIndex: 2,
      },
      {
      type: 'multiple-choice',
      text: 'Ce aparat este folosit pentru detectarea intrarilor neautorizate in retea?',
      options: ['ESA',
                'Firewall',
                'WSA',
                'ngFirewall',
                'VPN',
                'IPS',
                'IDS',
               ],
      correctIndex: 6,
      },
      {
      type: 'multiple-choice',
      text: 'Ce aparat este folosit pentru blocarea intrarilor neautorizate in retea?',
      options: ['ESA',
                'Firewall',
                'WSA',
                'ngFirewall',
                'VPN',
                'IPS',
                'IDS',
               ],
      correctIndex: 5,
      },
      {
      type: 'multiple-choice',
      text: 'Ce aparat creeaza o retea virtuala pentru a cripta traficul?',
      options: ['ESA',
                'Firewall',
                'WSA',
                'ngFirewall',
                'VPN',
                'IPS',
                'IDS',
               ],
      correctIndex: 4,
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele reprezinta un dispozitiv folosit pentru securizare?',
      options: ['Firewall', 'Switch', 'Router', 'MLSW', 'Wireless Router'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care din componentele AAA se ocupa cu controlul atributiilor unui utilizator?',
      options: ['Authentication',
                'Authorization',
                'Accounting',
                'Applying',
                'Addressing'
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Care din componentele AAA se ocupa cu pastrarea evidentei despre activitatea unui utilizator?',
      options: ['Authentication',
                'Authorization',
                'Accounting',
                'Applying',
                'Addressing'
               ],
      correctIndex: 2,
      },
      {
      type: 'multiple-choice',
      text: 'Care este diferenta dintre encriptie si hashing?',
      options: ['Encriptia este reversibila, dar hashingul nu',
                'Hashingul este reversibil, dar encriptia nu',
                'Hashingul este mai rapid decat encriptia',
                'Encriptia permite chei doar pana la 64 biti',
                'Hashingul permite chei doar pana la 32 biti'
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele reprezinta un atac prin care se impersoneaza ilegitim un alt dispozitiv fata de cel propriu?',
      options: ['Virusi', 'Viermi', 'Troieni', 'Spoofing', 'DoS', 'DDoS', 'Man-in-the-middle', 'Reconnaisance Attacks', 'Social Engineering'],
      correctIndex: 3, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele reprezinta un atac prin care se intercepteaza (si modifica) traficul intre doua hosturi?',
      options: ['Virusi', 'Viermi', 'Troieni', 'Spoofing', 'DoS', 'DDoS', 'Man-in-the-middle', 'Reconnaisance Attacks', 'Social Engineering'],
      correctIndex: 6, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele reprezinta un atac prin care se culeg informatii sensibile despre o retea?',
      options: ['Virusi', 'Viermi', 'Troieni', 'Spoofing', 'DoS', 'DDoS', 'Man-in-the-middle', 'Reconnaisance Attacks', 'Social Engineering'],
      correctIndex: 7, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele reprezinta un atac prin care se trimite un program javascript malitios pe un site web vulnerabil, iar programul este pastrat pe server?',
      options: ['Stored XSS', 'Reflected XSS', 'DOM XSS', 'SQL Injection', 'DoS', 'DDoS', 'Man-in-the-middle', 'Phishing' ],
      correctIndex: 0, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele reprezinta un atac prin care se trimite un program javascript malitios pe un site web vulnerabil si se primeste un raspuns imediat?',
      options: ['Stored XSS', 'Reflected XSS', 'DOM XSS', 'SQL Injection', 'DoS', 'DDoS', 'Man-in-the-middle', 'Phishing' ],
      correctIndex: 1, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele reprezinta un atac prin care se trimite un program javascript malitios pe un site web vulnerabil si ruleaza complet pe partea clientului?',
      options: ['Stored XSS', 'Reflected XSS', 'DOM XSS', 'SQL Injection', 'DoS', 'DDoS', 'Man-in-the-middle', 'Phishing' ],
      correctIndex: 2, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele reprezinta un atac prin care se trimit inputuri malitioase pe un site web vulnerabil ca acesta sa ofere informatii sensibile?',
      options: ['Stored XSS', 'Reflected XSS', 'DOM XSS', 'Injection', 'DoS', 'DDoS', 'Man-in-the-middle', 'Phishing' ],
      correctIndex: 3, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele reprezinta un atac prin care se abuzeaza de increderea unui utilizator?',
      options: ['Virusi', 'Viermi', 'Troieni', 'Spoofing', 'DoS', 'DDoS', 'Man-in-the-middle', 'Reconnaisance Attacks', 'Social Engineering'],
      correctIndex: 8, 
      },
      {
      type: 'multiple-choice',
      text: 'In ce categorie de atacuri se incadreaza atacurile de tip Phishing?',
      options: ['Virusi', 'Viermi', 'Troieni', 'Spoofing', 'DoS', 'DDoS', 'Man-in-the-middle', 'Reconnaisance Attacks', 'Social Engineering'],
      correctIndex: 8, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele scenarii reprezinta un atac DoS?',
      options: ['Un utilizator trimite foarte multe cereri',
                'Mai multi utilizatori trimit foarte multe cereri concomitent',
                'Un utilizator este convins sa isi comunice date personale',
                'Un joc piratat deschide un script ascuns pentru furt de date',
                'Traficul dintre doua dispozitive trece mai intai pe la un atacator, dupa care este modificat',
                'Un atacator foloseste adresa IP a unui utilizator legitim',
                'Un program malitios se raspandeste intr-un calculator fara interventia utilizatorului',
                'Un program malitios se raspandeste intr-un calculator dupa interventia utilizatorului'
               ],
      correctIndex: 0, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele scenarii reprezinta un atac DDoS?',
      options: ['Un utilizator trimite foarte multe cereri',
                'Mai multi utilizatori trimit foarte multe cereri concomitent',
                'Un utilizator este convins sa isi comunice date personale',
                'Un joc piratat deschide un script ascuns pentru furt de date',
                'Traficul dintre doua dispozitive trece mai intai pe la un atacator, dupa care este modificat',
                'Un atacator foloseste adresa IP a unui utilizator legitim',
                'Un program malitios se raspandeste intr-un calculator fara interventia utilizatorului',
                'Un program malitios se raspandeste intr-un calculator dupa interventia utilizatorului'
               ],
      correctIndex: 1, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele scenarii reprezinta un atac de tip Social Engineering?',
      options: ['Un utilizator trimite foarte multe cereri',
                'Mai multi utilizatori trimit foarte multe cereri concomitent',
                'Un utilizator este convins sa isi comunice date personale',
                'Un joc piratat deschide un script ascuns pentru furt de date',
                'Traficul dintre doua dispozitive trece mai intai pe la un atacator, dupa care este modificat',
                'Un atacator foloseste adresa IP a unui utilizator legitim',
                'Un program malitios se raspandeste intr-un calculator fara interventia utilizatorului',
                'Un program malitios se raspandeste intr-un calculator dupa interventia utilizatorului'
               ],
      correctIndex: 2, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele scenarii reprezinta un atac de tip troian?',
      options: ['Un utilizator trimite foarte multe cereri',
                'Mai multi utilizatori trimit foarte multe cereri concomitent',
                'Un utilizator este convins sa isi comunice date personale',
                'Un joc piratat deschide un script ascuns pentru furt de date',
                'Traficul dintre doua dispozitive trece mai intai pe la un atacator, dupa care este modificat',
                'Un atacator foloseste adresa IP a unui utilizator legitim',
                'Un program malitios se raspandeste intr-un calculator fara interventia utilizatorului',
                'Un program malitios se raspandeste intr-un calculator dupa interventia utilizatorului'
               ],
      correctIndex: 3, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele scenarii reprezinta un atac de tip Man-in-the-middle?',
      options: ['Un utilizator trimite foarte multe cereri',
                'Mai multi utilizatori trimit foarte multe cereri concomitent',
                'Un utilizator este convins sa isi comunice date personale',
                'Un joc piratat deschide un script ascuns pentru furt de date',
                'Traficul dintre doua dispozitive trece mai intai pe la un atacator, dupa care este modificat',
                'Un atacator foloseste adresa IP a unui utilizator legitim',
                'Un program malitios se raspandeste intr-un calculator fara interventia utilizatorului',
                'Un program malitios se raspandeste intr-un calculator dupa interventia utilizatorului'
               ],
      correctIndex: 4, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele scenarii reprezinta un atac de tip Spoofing?',
      options: ['Un utilizator trimite foarte multe cereri',
                'Mai multi utilizatori trimit foarte multe cereri concomitent',
                'Un utilizator este convins sa isi comunice date personale',
                'Un joc piratat deschide un script ascuns pentru furt de date',
                'Traficul dintre doua dispozitive trece mai intai pe la un atacator, dupa care este modificat',
                'Un atacator foloseste adresa IP a unui utilizator legitim',
                'Un program malitios se raspandeste intr-un calculator fara interventia utilizatorului',
                'Un program malitios se raspandeste intr-un calculator dupa interventia utilizatorului'
               ],
      correctIndex: 5, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele scenarii reprezinta un atac de tip vierme?',
      options: ['Un utilizator trimite foarte multe cereri',
                'Mai multi utilizatori trimit foarte multe cereri concomitent',
                'Un utilizator este convins sa isi comunice date personale',
                'Un joc piratat deschide un script ascuns pentru furt de date',
                'Traficul dintre doua dispozitive trece mai intai pe la un atacator, dupa care este modificat',
                'Un atacator foloseste adresa IP a unui utilizator legitim',
                'Un program malitios se raspandeste intr-un calculator fara interventia utilizatorului',
                'Un program malitios se raspandeste intr-un calculator dupa interventia utilizatorului'
               ],
      correctIndex: 6, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele scenarii reprezinta un atac de tip virus?',
      options: ['Un utilizator trimite foarte multe cereri',
                'Mai multi utilizatori trimit foarte multe cereri concomitent',
                'Un utilizator este convins sa isi comunice date personale',
                'Un joc piratat deschide un script ascuns pentru furt de date',
                'Traficul dintre doua dispozitive trece mai intai pe la un atacator, dupa care este modificat',
                'Un atacator foloseste adresa IP a unui utilizator legitim',
                'Un program malitios se raspandeste intr-un calculator fara interventia utilizatorului',
                'Un program malitios se raspandeste intr-un calculator dupa interventia utilizatorului'
               ],
      correctIndex: 7, 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care dintre urmatoarele reprezinta principiile securitatii?\nAlegeti 3 variante.',
      options: ['Integritate', 'Confidentialitate', 'Disponibilitate', 'Redundanta', 'Scalabilitate', 'Prioritizare', 'Organizare', 'Fiabilitate'],
      correctIndices: [0, 1, 2], 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele tipuri de server este folosit in 802.1X?',
      options: ['Radius', 'TACACS+', 'DHCP', 'TFTP', 'DNS', 'FTP', 'CDP', 'LLDP', 'SNMP'],
      correctIndex: 0,  
      },
      {
      type: 'multiple-choice-multi',
      text: 'Ce protocoale ar putea fi folosite intr-un atac de tip Reconnaisance?\nAlegeti 2 variante.',
      options: ['Radius', 'TACACS+', 'DHCP', 'TFTP', 'DNS', 'FTP', 'CDP', 'LLDP', 'SNMP'],
      correctIndices: [6, 7], 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care dintre urmatoarele reprezinta categorii de atacuri malware?\nAlegeti 3 variante.',
      options: ['Virusi', 'Viermi', 'Troieni', 'Spoofing', 'DoS', 'DDoS', 'Man-in-the-middle', 'Reconnaisance Attacks', 'Social Engineering'],
      correctIndices: [0, 1, 2], 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care dintre urmatoarele reprezinta atacuri care trimit un numar foarte mari de cereri pentru a suprasolicita un serviciu?\nAlegeti 2 variante.',
      options: ['Virusi', 'Viermi', 'Troieni', 'Spoofing', 'DoS', 'DDoS', 'Man-in-the-middle', 'Reconnaisance Attacks', 'Social Engineering'],
      correctIndices: [4, 5], 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Alegeti cele 4 variante care descriu un atac de impersonare ilegitima:',
      options: ['IP Spoofing', 'MAC Spoofing', 'ARP Posioning', 'DHCP Poisoning', 'Trojan', 'CDP Reconnaisance', 'UDP Spoofing'],
      correctIndices: [0, 1, 2, 3], 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Alegeti cele 3 variantele care descriu un atac de DoS / DDoS:',
      options: ['DHCP Starvation', 'CAM Flooding', 'NAT Exhaustion', 'IP Exhaustion', 'IP Flooding', 'CDP Reconnaisance'],
      correctIndices: [0, 1, 2], 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Ce se poate intampla in urma unui atac de tip STP?\nAlegeti 2 variante.',
      options: ['Arborele STP se modifica', 'Root Bridge se modifica', 'Se suprascriu adresele din tabela MAC', 'Versiunea de STP se modifica', 'Continutul mesajelor STP se modifica', 'Adresele MAC ale dispozitivelor se modifica'],
      correctIndices: [0, 1], 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Cum pot fi prevenite atacurile de VLAN Hopping & VLAN Double tagging?\nAlegeti 2 variante.',
      options: ['Schimbarea VLAN-ului nativ', 'Dezactivarea DTP', 'Dezactivarea STP', 'Folosirea VLAN-urilor din range-ul extended', 'Oprirea VLAN-urilor nefolosite'],
      correctIndices: [0, 1], 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Selectati 5 algoritmi de encriptie simetrica:',
      options: ['AES', '3DES', 'ChaCha20', 'RC4', 'SEAL', 'Diffie-Hellman', 'RSA', 'DSA', 'ECC', 'El Gamal'],
      correctIndices: [0, 1, 2, 3, 4], 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Selectati 5 algoritmi de encriptie asimetrica:',
      options: ['AES', '3DES', 'ChaCha20', 'RC4', 'Diffie-Hellman', 'RSA', 'DSA', 'ECC', 'El Gamal', 'SEAL'],
      correctIndices: [4, 5, 6, 7, 8], 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Selectati 2 algoritmi de hashing:',
      options: ['AES', '3DES', 'ChaCha20', 'RC4', 'Diffie-Hellman', 'RSA', 'DSA', 'ECC', 'El Gamal', 'SEAL', 'MD5', 'SHA'],
      correctIndices: [9, 10], 
      },
      {
      type: 'matching',
      text: 'Asociati algoritmul de encriptie cu valorile pentru chei:',
      subQuestions: [
        { text: 'DES', answer: '56' },
        { text: '3DES', answer: '112/168' },
        { text: 'AES', answer: '128,192,256' },
        { text: 'SEAL', answer: '160' },
        { text: 'Blowfish', answer: '32-448' },
        { text: 'RSA', answer: '1024+' },
      ],
      options: ['56', '112/168', '64', '128,192,256', '32-448', '1024+', '160' , '128'],
      },
      {
      type: 'matching',
      text: 'Asociati algoritmul de hashing cu valorile pentru chei:',
      subQuestions: [
        { text: 'MD5', answer: '128' },
        { text: 'SHA', answer: '160' },
      ],
      options: ['56', '1024+', '160' , '128'],
      },
      {
      type: 'matching',
      text: 'Asociati descrierea atacurilor cu categoria in care se incadreaza cel mai bine:',
      subQuestions: [
        { text: 'DHCP Posioning', answer: 'Spoofing' },
        { text: 'DHCP Starvation', answer: 'DoS' },
        { text: 'CDP Reconnaisance', answer: 'Reconnaisance Attack' },
        { text: 'MAC Flooding', answer: 'DoS' },
        { text: 'VLAN Hopping', answer: 'VLAN Attack' },
        { text: 'Double-Tagging', answer: 'VLAN Attack' },
        { text: 'ARP Posioning', answer: 'Spoofing' },
        { text: 'IP Spoofing', answer: 'Spoofing' },
        { text: 'MAC Spoofing', answer: 'Spoofing' },
        { text: 'Virusi', answer: 'Malware' },
        { text: 'Troieni', answer: 'Malware' },
      ],
      options: ['Spoofing', 'Reconnaisance Attack', 'DoS', 'VLAN Attack', 'Malware'],
      },
    ]
});
