ACADOBRE_QUESTIONS.push({
  id: 'snmp',
    topic: 'SNMP',
    questions: [
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru SNMP Agent?',
        acceptedAnswers: ['161 UDP', '161 udp'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru SNMP Manager?',
        acceptedAnswers: ['162 UDP', '162 udp'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
      type: 'multiple-choice',
      text: 'La ce nivel OSI opereaza SNMP?',
      options: ['Aplicatie', 'Fizic', 'Legatura de Date', 'Prezentare', 'Transport', 'Retea', 'Sesiune'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care este rolul principal al SNMP?',
      options: ['Monitorizare si configurare centralizata',
                'Asigurarea fiabilitatii in transportul datelor',
                'Asigurarea redundantei',
                'Managementul congestiilor in retea',
                'Verificarea erorilor in transmiterea datelor',
                ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care este diferenta dintre Syslog si SNMP?',
      options: ['Syslog permite doar notificari, SNMP are mai multe functii',
                'Syslog foloseste TCP, iar SNMP foloseste UDP',
                'Syslog foloseste UDP, iar SNMP foloseste TCP',
                'SNMP permite doar notificari, Syslog are mai multe functii',
                'Syslog retrimtite mesajele care nu ajung la destinatie, SNMP este best-effort',
                ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce tip de software ruleaza pe dispozitivele SNMP care administreaza?',
      options: ['SNMP Manager',
                'SNMP Agent',
                'SNMP Sender',
                'SNMP Requester',
                'SNMP Cacher',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce tip de software ruleaza pe dispozitivele SNMP care sunt gestionate?',
      options: ['SNMP Manager',
                'SNMP Agent',
                'SNMP Sender',
                'SNMP Requester',
                'SNMP Cacher',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Cum se numesc dispozitivele care gestioneaza alte dispozitive in SNMP?',
      options: ['Networking Management Station',
                'Managed Devices',
                'SNMP Sender',
                'SNMP Requester',
                'SNMP Cacher',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Cum se numesc dispozitivele care sunt gestionate de catre alte dispozitive in SNMP?',
      options: ['Networking Management Station',
                'Managed Devices',
                'SNMP Sender',
                'SNMP Requester',
                'SNMP Cacher',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Ce structura de date de pe dispozitivele administrate contine variabile gestionate de SNMP?',
      options: ['Management Information Base',
                'Management Variable Table',
                'Information Table',
                'Configuration Files',
                'SNMP Cache',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Dupa ce sunt organziate informatiile in SNMP MIB?',
      options: ['Object ID',
                'SNMPEntry',
                'Variable Tag',
                'SNMP ID',
                'Object Entry',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care versiune SNMP foloseste encriptie si autentificare?',
      options: ['SNMPv3',
                'SNMPv2c',
                'SNMPv2',
                'SNMPv3c',
                'SNMPv1',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca un client SNMP poate trimite notificari catre NMS fara a avea o solicitare?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca un NMS nu poate solicita informatii de la clientii SNMP?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca un NMS poate face modificari de configurare pentru clientii SNMP?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Ce tip de mesaj SNMP este trimis de NMS pentru a realiza schimbari in configurarea clientilor SNMP?',
      options: ['Set',
                'Write',
                'Configure',
                'Inform',
                'Change',
                'Speak',
                'Trap'
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce tip de mesaj SNMP este trimis de clienti catre NMS si nu este confirmat la primire?',
      options: ['Trap',
                'Inform',
                'Configure',
                'Write',
                'Change',
                'Speak',
                'Set'
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce tip de mesaj SNMP este trimis de clienti catre NMS si este confirmat la primire?',
      options: ['Trap',
                'Inform',
                'Configure',
                'Write',
                'Change',
                'Speak',
                'Set'
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Ce tip de mesaj SNMP este drept raspuns la o cerere anterioara?',
      options: ['Response',
                'Reply',
                'Request',
                'Retry',
                'Replic',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice-multi',
      text: 'Ce tip de mesaje SNMP sunt trimise de NMS pentru a obtine informatii de la clientii SNMP?\nAlegeti 3 variante.',
      options: ['Get',
                'GetNext',
                'GetBulk',
                'GetNow',
                'GetMore',
                'GetRekt',
               ],
      correctIndices: [0, 1, 2],
      },
    ]
});
