ACADOBRE_QUESTIONS.push({
  id: 'ssh',
    topic: 'SSH',
    questions: [
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru SSH?',
        acceptedAnswers: ['22 TCP', '22 tcp'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru Telnet?',
        acceptedAnswers: ['23 TCP', '23 tcp'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Ce comanda face ca mesajele syslog sa fie generate pe o linie noua?',
        acceptedAnswers: ['logging synchronous', 'logg syn'],
      },
      {
        type: 'open-ended',
        text: 'Ce comanda face ca mesajele syslog sa fie generate pe liniile VTY?',
        acceptedAnswers: ['terminal monitor'],
      },
      {
        type: 'open-ended',
        text: 'Cum putem deloga un utilizator dupa 1 minut si 30 de secunde?',
        acceptedAnswers: ['exec-timeout 1 30'],
      },
      {
        type: 'open-ended',
        text: 'Ce comanda trebuie introdusa dupa ce configuram o parola pe consola?',
        acceptedAnswers: ['login'],
      },
      {
        type: 'open-ended',
        text: 'Ce comanda trebuie introdusa pentru configurarea logarii pe liniile VTY?',
        acceptedAnswers: ['login local'],
      },
      {
        type: 'open-ended',
        text: 'Cate linii VTY exista?',
        acceptedAnswers: ['16'],
      },
      {
      type: 'multiple-choice',
      text: 'Ce tip de imagine IOS permite SSH?',
      options: ['k9',
                'encrypted',
                '102',
                'XE',
                'XR',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce tip de algoritm folosesc cheile SSH?',
      options: ['RSA',
                'Diffie-Hellman',
                'DSA',
                'AES',
                '3DES',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Cum trebuie aplicate ACL-urile pe interfetele VTY?',
      options: ['Inbound',
                'Outbound',
                'Inside',
                'Outside',
                'Implicit',
                'Explicit'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care este verisunea recomandata de SSH?',
      options: ['2',
                '1',
                '1.99',
                '3',
                '0',
                '1.5'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca telnet nu poate functiona fara o parola pentru enable?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice-multi',
      text: 'Ce tip de criptare foloseste SSH?\nAlegeti 2 variante.',
      options: ['Simetrica',
                'Asimetrica',
                'Publica',
                'Privata',
                'Asimptotica',
                'Explicita'],
      correctIndices: [0, 1],
      },
      {
      type: 'multiple-choice-multi',
      text: 'De ce este nevoie pentru a putea genera cheile RSA?\nAlegeti 2 variante.',
      options: ['Schimbarea hostname',
                'Configurarea unui nume de domeniu',
                'Pornirea SSHv2',
                'Folosirea unui username',
                'Configurarea unui parole de domeniu',
                'Configurarea liniilor VTY'],
      correctIndices: [0, 1],
      },
      {
      type: 'label-order',
      text: 'Puneti in ordine pasii de configurare SSH',
      hint: 'Hint: sunt mai multe posibilitati. Doar cativa pasi sunt obligatoriu inaintea altora.',
      labels: ['Schimbarea hostname',
               'Configurarea unui nume de domeniu',
               'Generarea cheilor RSA',
               'Configurarea username+parola',
               'Pornirea SSHv2',
               'Configurarea liniilor VTY'
             ],
      correctOrder: [0, 1, 2, 3, 4, 5],
      },
      {
      type: 'matching',
      text: 'Asociati fiecare inceput de prompt cu modul de utilizator corespunzator:',
      subQuestions: [
        { text: 'Global Configuration', answer: '(config)#' },
        { text: 'Privileged EXEC', answer: '#' },
        { text: 'User EXEC', answer: '>' },
      ],
      options: ['>', '#', '(config)#', '!', '>#'],
      },
    ]
});
