ACADOBRE_QUESTIONS.push({
  id: 'stp',
    topic: 'STP si RSTP',
    questions: [
      {
      type: 'open-ended',
      text: 'Cat timp raman in stadiul Blocking switchurile care ruleaza CST? (secunde)',
      acceptedAnswers: ['20'],
      },
      {
      type: 'open-ended',
      text: 'Cat timp raman in stadiul Listening switchurile care ruleaza CST? (secunde)',
      acceptedAnswers: ['15'],
      },
      {
      type: 'open-ended',
      text: 'Cat timp raman in stadiul Learning switchurile care ruleaza CST? (secunde)',
      acceptedAnswers: ['15'],
      },
      {
      type: 'open-ended',
      text: 'Cat timp dureaza ca un switch sa ajunga in stadiul Forwarding daca foloseste RSTP? (secunde)',
      acceptedAnswers: ['6'],
      },
      {
      type: 'open-ended',
      text: 'Care este codul pentru standardul IEEE CST?',
      acceptedAnswers: ['802.1D', '802.1d'],
      },
      {
      type: 'open-ended',
      text: 'Care este codul pentru standardul IEEE RSTP?',
      acceptedAnswers: ['802.1W', '802.1w'],
      },
      {
      type: 'open-ended',
      text: 'Care este codul pentru standardul IEEE MSTP?',
      acceptedAnswers: ['802.1S', '802.1s'],
      },
      {
      type: 'open-ended',
      text: 'Care este costul pentru o legatura cu viteza 10 Mbps pentru CST?',
      acceptedAnswers: ['100'],
      },
      {
      type: 'open-ended',
      text: 'Care este costul pentru o legatura cu viteza 100 Mbps (FastEthernet) pentru CST?',
      acceptedAnswers: ['19'],
      },
      {
      type: 'open-ended',
      text: 'Care este costul pentru o legatura cu viteza 1000 Mbps pentru CST?',
      acceptedAnswers: ['4'],
      },
      {
      type: 'open-ended',
      text: 'Care este costul pentru o legatura cu viteza 10000 Mbps sau mai mare pentru CST?',
      acceptedAnswers: ['1'],
      },
      {
      type: 'open-ended',
      text: 'Care este costul pentru o legatura cu viteza 100 Mbps (FastEthernet) pentru RSTP?',
      acceptedAnswers: ['200000'],
      },
      {
      type: 'open-ended',
      text: 'Care este valoarea default pentru prioritate a unui Bridge ID?',
      acceptedAnswers: ['32768'],
      },
      {
      type: 'open-ended',
      text: 'Care este incrementul pentru prioritatea unui Bridge ID?',
      acceptedAnswers: ['4096'],
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca doar Root Bridge-ul poate trimite BPDU?',
      options: ['Adevarat', 'Fals'],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'De la ce vine acronimul BPDU?',
      options: ['Bridge Protocol Data Unit', 'Binary Packet Delivery Unit', 'Basic Port Designation Unit', 'Broadcast Protocol Data Unit', 'Backbone Path Distribution Unit'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce rol are Root Bridge-ul pentru STP?',
      options: ['Este singurul care genereaza BPDU', 'Este punctul de referinta pentru Algoritmul STP', 'Functioneaza drept backup pentru switchurile din retea', 'Primeste BPDU', 'Tot traficul trebuie sa treaca prin root bridge'],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Care componenta din Toolkit-ul STP sare peste stadiile Listening si Learning?',
      options: ['PortFast', 'BPDU Guard', 'BPDU Filter', 'Root Guard', 'Root Bridge'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care componenta din Toolkit-ul STP pune portul in modul err-disabled daca primeste un BPDU?',
      options: ['PortFast', 'BPDU Guard', 'BPDU Filter', 'Root Guard', 'Root Bridge'],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Care componenta din Toolkit-ul STP opreste un port din a trimite BPDU?',
      options: ['PortFast', 'BPDU Guard', 'BPDU Filter', 'Root Guard', 'Root Bridge'],
      correctIndex: 2,
      },
      {
      type: 'multiple-choice',
      text: 'Care componenta din Toolkit-ul STP pune portul in modul err-disabled daca primeste un BPDU cu BID mai mic?',
      options: ['PortFast', 'BPDU Guard', 'BPDU Filter', 'Root Guard', 'Root Bridge'],
      correctIndex: 3,
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre versiunile STP NU are Toolkit?',
      options: ['CST', 'PVST', 'PVST+', 'RSTP', 'RPVST+', 'MSTP'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre versiunile STP este cea default pe switchurile Cisco?',
      options: ['CST', 'PVST', 'PVST+', 'RSTP', 'RPVST+', 'MSTP'],
      correctIndex: 2,
      },
      {
      type: 'multiple-choice',
      text: 'Ce previne protocolul STP?',
      options: ['Buclele de retea', 'Atacuri', 'Redundanta', 'Cutrmeure', 'Trafic congestionat'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care este primul criteriu dupa care se alege Root Bridge-ul?',
      options: ['Cea mai mica prioritate', 'Cea mai mica adresa MAC', 'Cea mai mare prioritate', 'Cea mai mare Adresa MAC', 'Cel mai mic numar de port'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce rol au toate porturile pe Root Bridge?',
      options: ['Designated', 'Root', 'Blocking', 'Alternate', 'Backup'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce rol au porturile cu cel mai mic cost fata de Root Bridge pe un switch?',
      options: ['Designated', 'Root', 'Blocking', 'Alternate', 'Backup'],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Daca sunt mai multe rute cu cost minim catre Root Bridge, care va fi urmatorul criteriu de alegere al porturilor Root?',
      options: ['Dupa vecinul cu BID-ul mai mic', 'Dupa portul cu adresa MAC mai mica', 'Dupa numarul de port mai mic', 'Dupa switchul cu IOS mai vechi', 'Dupa cablul mai mic'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Cand porturile root au fost deja stabilite, cum se alege care port switch va avea portul designated si care va avea blocking?',
      options: ['Dupa BID-ul mai mic', 'Dupa portul cu adresa MAC mai mica', 'Dupa numarul de port mai mic', 'Dupa switchul cu IOS mai vechi', 'Dupa cablul mai mic'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Cand a fost stabilit care switch va avea portul Designated si care va avea portul Blocking, dar intre switchuri exista mai multe legaturi, cum se alege care dintre interfete va fi designated?',
      options: ['Dupa BID-ul mai mic', 'Dupa portul cu adresa MAC mai mica', 'Dupa numarul de port mai mic', 'Dupa switchul cu IOS mai vechi', 'Dupa cablul mai mic'],
      correctIndex: 2,
      },
      {
      type: 'multiple-choice',
      text: 'Ce rol au porturile care nu sunt nici Root nici Designated pentru CST?',
      options: ['Designated', 'Root', 'Blocking', 'Alternate', 'Backup'],
      correctIndex: 2,
      },
      {
      type: 'multiple-choice',
      text: 'In ce stadiu RSTP au fost imbinate stadiile CST Blocking si Disabled?',
      options: ['Blocking', 'Listening', 'Learning', 'Forwarding', 'Disabled', 'Discarding'],
      correctIndex: 5,
      },
      {
      type: 'multiple-choice',
      text: 'In ce stadiu RSTP au fost imbinate stadiile CST Listening si Learning?',
      options: ['Blocking', 'Listening', 'Learning', 'Forwarding', 'Disabled', 'Discarding'],
      correctIndex: 2,
      },
      {
      type: 'multiple-choice',
      text: 'Ce rol au porturile opuse unui port Root?',
      options: ['Designated', 'Root', 'Blocking', 'Alternate', 'Backup'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care este echivalentul porturilor Blocking din CST pentru RSTP?',
      options: ['Designated', 'Root', 'Blocking', 'Alternate', 'Backup'],
      correctIndex: 3,
      },
      {
      type: 'multiple-choice',
      text: 'Care din rolurile posibile ale unui port ofera redundanta pe o legatura cu mediu impartit(Hub)?',
      options: ['Designated', 'Root', 'Blocking', 'Alternate', 'Backup'],
      correctIndex: 4,
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre stadiile CST trimite trafic normal?',
      options: ['Blocking', 'Listening', 'Learning', 'Forwarding', 'Disabled', 'Discarding'],
      correctIndex: 3, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre stadiile RSTP trimite trafic normal?',
      options: ['Blocking', 'Listening', 'Learning', 'Forwarding', 'Disabled', 'Discarding'],
      correctIndex: 3, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre stadiile RSTP NU trimite BPDU?',
      options: ['Blocking', 'Listening', 'Learning', 'Forwarding', 'Disabled', 'Discarding'],
      correctIndex: 5, 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care dintre stadiile CST NU trimit BPDU?\nAlegeti 2 variante.',
      options: ['Blocking', 'Listening', 'Learning', 'Forwarding', 'Disabled', 'Discarding'],
      correctIndices: [0, 4], 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care dintre stadiile CST invata adrese MAC?\nAlegeti 2 variante.',
      options: ['Blocking', 'Listening', 'Learning', 'Forwarding', 'Disabled', 'Discarding'],
      correctIndices: [2, 3], 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care dintre stadiile RSTP invata adrese MAC?\nAlegeti 2 variante.',
      options: ['Blocking', 'Listening', 'Learning', 'Forwarding', 'Disabled', 'Discarding'],
      correctIndices: [2, 3], 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care dintre versiunile pot folosi instante diferite pentru fiecare VLAN dot1q?\nAlegeti 3 variante.',
      options: ['CST', 'PVST', 'PVST+', 'RSTP', 'RPVST+', 'MSTP'],
      correctIndices: [2, 4, 5], 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care dintre urmatorii parametrii alcatuiesc Bridge ID-ul?\nAlegeti 3 variante.',
      options: ['Extended System ID', 'Priority', 'MAC Address', 'Port number', 'IP Address', 'Hostname', 'VLAN ID'],
      correctIndices: [0, 1, 2], 
      },
      {
      type: 'matching',
      text: 'Stabiliti care verisuni STP sunt proprietare si care sunt standard:',
      subQuestions: [
        { text: 'CST', answer: 'Standard' },
        { text: 'PVST', answer: 'Proprietar' },
        { text: 'PVST+', answer: 'Proprietar' },
        { text: 'RSTP', answer: 'Standard' },
        { text: 'RPVST+', answer: 'Proprietar' },
        { text: 'MSTP', answer: 'Standard' },
      ],
      options: ['Proprietar', 'Standard'],
      },
    ]
});
