ACADOBRE_QUESTIONS.push({
  id: 'syslog',
    topic: 'Syslog',
    questions: [
      {
        type: 'open-ended',
        text: 'Care este portul si protocolul de nivel 4 pentru Syslog?',
        acceptedAnswers: ['514 UDP', '514 udp'],
        hint: 'Exemplu de raspuns: "12 DBR".',
      },
      {
        type: 'open-ended',
        text: 'Ce comanda face ca mesajele syslog sa fie generate pe o linie noua?',
        acceptedAnswers: ['logging synchronous', 'logg syn'],
      },
      {
        type: 'open-ended',
        text: 'Ce comanda face ca mesajele syslog sa fie generate pe liniile VTY?',
        acceptedAnswers: ['terminal monitor'],
      },
      {
        type: 'open-ended',
        text: 'Care este nivelul de severitate Syslog pentru "Emergency"?',
        acceptedAnswers: ['0'],
      },
      {
        type: 'open-ended',
        text: 'Care este nivelul de severitate Syslog pentru "Alert"?',
        acceptedAnswers: ['1'],
      },
      {
        type: 'open-ended',
        text: 'Care este nivelul de severitate Syslog pentru "Critical"?',
        acceptedAnswers: ['2'],
      },
      {
        type: 'open-ended',
        text: 'Care este nivelul de severitate Syslog pentru "Error"?',
        acceptedAnswers: ['3'],
      },
      {
        type: 'open-ended',
        text: 'Care este nivelul de severitate Syslog pentru "Warning"?',
        acceptedAnswers: ['4'],
      },
      {
        type: 'open-ended',
        text: 'Care este nivelul de severitate Syslog pentru "Notice"?',
        acceptedAnswers: ['5'],
      },
      {
        type: 'open-ended',
        text: 'Care este nivelul de severitate Syslog pentru "Informational"?',
        acceptedAnswers: ['6'],
      },
      {
        type: 'open-ended',
        text: 'Care este nivelul de severitate Syslog pentru "Debugging"?',
        acceptedAnswers: ['7'],
      },
      {
      type: 'multiple-choice',
      text: 'La ce nivel OSI opereaza Syslog?',
      options: ['Aplicatie', 'Fizic', 'Legatura de Date', 'Prezentare', 'Transport', 'Retea', 'Sesiune'],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care este rolul principal al protocolului de Syslog?',
      options: ['Pastrarea evidentei asupra anumitor evenimente',
                'Monitorizare si configurare centralizata',
                'Asigurarea redundantei',
                'Managementul congestiilor in retea',
                'Verificarea erorilor in transmiterea datelor',
                ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care este diferenta dintre Syslog si SNMP?',
      options: ['Serverele syslog nu pot cere explicit informatii',
                'Syslog foloseste TCP, iar SNMP foloseste UDP',
                'Syslog foloseste UDP, iar SNMP foloseste TCP',
                'Serverele SNMP nu pot cere explicit informatii',
                'Syslog retrimtite mesajele care nu ajung la destinatie, SNMP este best-effort',
                ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca toate nivelele de severitate Syslog sunt pornite implicit pe consola?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca nivelele de severitate Syslog afisate pot fi modificate?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice-multi',
      text: 'Unde pot fi trimise mesajele Syslog?',
      options: ['Consola',
                'Buffer in RAM',
                'Server Syslog',
                'Liniile VTY (terminal monitor)',
                'Liniile VTY (by default)',
                'Server SysMonitor',
                'Liniile de interfata',
                'User EXEC',
               ],
      correctIndices: [0, 1, 2, 3],
      },
      {
      type: 'label-order',
      text: 'Puneti nivelele de severitate Syslog in ordine:',
      labels: ['Emergency', 'Alert', 'Critical', 'Error', 'Warning', 'Notice', 'Informational', 'Debugging'],
      correctOrder: [0, 1, 2, 3, 4, 5, 6, 7],
      },
      {
      type: 'matching',
      text: 'Asociati fiecare parte din acest mesaj cu componenta syslog corespunzatoare:\n%LINEPROTO-5-UPDOWN: Line protocol on Interface Gig0/0/0, changed state to up',
      subQuestions: [
        { text: 'facility', answer: 'LINEPROTO' },
        { text: 'severity', answer: '5' },
        { text: 'MNEMONIC', answer: 'UPDOWN' },
        { text: 'description', answer: 'Line protocol on Interface Gig0/0/0, changed state to up' },
      ],
      options: ['5','UPDOWN', 'LINEPROTO', 'Line protocol on Interface Gig0/0/0, changed state to up'],
      },
    ]
});