ACADOBRE_QUESTIONS.push({
  id: 'vlans',
    topic: 'VLAN-uri',
    questions: [
      {
      type: 'open-ended',
      text: 'Care este range-ul pentru VLAN-urile normale?',
      hint: 'Scrieti in formatul "a-b".',
      acceptedAnswers: ['1-1005'],
      },
      {
      type: 'open-ended',
      text: 'Care este range-ul pentru VLAN-urile extended?',
      hint: 'Scrieti in formatul "a-b".',
      acceptedAnswers: ['1006-4094'],
      },
      {
      type: 'open-ended',
      text: 'Care este codul pentru standardul IEEE VLAN?',
      acceptedAnswers: ['802.1Q', '802.1q'],
      },
      {
      type: 'open-ended',
      text: 'Care este numarul de VLAN default?',
      acceptedAnswers: ['1'],
      },
      {
      type: 'multiple-choice',
      text: 'La ce nivel OSI opereaza VLAN-urile?',
      options: ['Aplicatie', 'Fizic', 'Legatura de Date', 'Prezentare', 'Transport', 'Retea', 'Sesiune'],
      correctIndex: 2,
      },
      {
      type: 'multiple-choice',
      text: 'Cum se numesc legaturile pe care pot circula mai mutle VLAN-uri diferite?',
      options: ['Data',
                'Management',
                'Voice',
                'Native',
                'Default',
                'Trunk',
                'Quality',
                'Access',
                ],
      correctIndex: 5,
      },
      {
      type: 'multiple-choice',
      text: 'Cum se numesc legaturile pe care poate circula un singur VLAN?',
      options: ['Data',
                'Management',
                'Voice',
                'Native',
                'Default',
                'Trunk',
                'Quality',
                'Access',
                ],
      correctIndex: 7,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca pentru a sterge un VLAN este suficient sa folosim comanda "no vlan <number>"?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca o interfata poate fi atat trunk si access in acelasi timp?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca o legatura trunk permite implicit toate VLAN-urile?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca pentru securitate este recomandat ca DTP sa fie oprit?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca pentru securitate nu este recomandat ca VLAN-ul nativ sa fie schimbat pe unul neutilizat?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care este cea mai scalabila metoda de rutare Inter-VLAN?',
      options: ['Legacy',
                'ROAS',
                'Layer 3 SVI',
                'Native Routing',
                'OSPF Routing',
                'Trunking Route',
                'Access Route',
                ],
      correctIndex: 2,
      },
      {
      type: 'multiple-choice',
      text: 'Care metoda de rutare Inter-VLAN presupune un fir diferit catre router pentru fiecare VLAN?',
      options: ['Legacy',
                'ROAS',
                'Layer 3 SVI',
                'Native Routing',
                'OSPF Routing',
                'Trunking Route',
                'Access Route',
                ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care metoda de rutare Inter-VLAN presupune folosirea subinterfetelor pe router?',
      options: ['Legacy',
                'ROAS',
                'Layer 3 SVI',
                'Native Routing',
                'OSPF Routing',
                'Trunking Route',
                'Access Route',
                ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Care este un protocol de trunking proprietar?',
      options: ['Inter-Switch Link',
                'EIGRP',
                'Dot1Cisco',
                'Native Routing',
                'STP',
                'LACP',
                ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Dupa ce camp al cadrului Ethernet se va adauga tagul 802.1q?',
      options: ['Preamble', 'SFD', 'Destionation MAC', 'Source MAC', 'Ethertype', 'Data', 'CRC'],
      correctIndex: 3,
      },
      {
      type: 'multiple-choice',
      text: 'Unde se stocheaza configuratia de VLAN-uri normale?',
      options: ['ROM', 'NVRAM', 'RAM', 'Flash', 'CAM'],
      correctIndex: 3,
      },
      {
      type: 'multiple-choice',
      text: 'Unde se stocheaza configuratia de VLAN-uri extended?',
      options: ['ROM', 'NVRAM', 'RAM', 'Flash', 'CAM'],
      correctIndex: 2,
      },
      {
      type: 'multiple-choice',
      text: 'Care este functia principala a VLAN-urilor?',
      options: ['Reducerea domeniului de broadcast',
                'Reducerea domeniului de coliziune',
                'Creearea interfetelor trunk',
                'Redundanta',
                'Fiabilitate',
                'Securitate'
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Pe care tip de VLAN vor circula frame-urile fara tag?',
      options: ['Data',
                'Management',
                'Voice',
                'Native',
                'Default',
                'Trunking',
                'Quality',
                'Access',
                ],
      correctIndex: 3,
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care dintre urmatoarele VLAN-uri nu pot fi sterse de pe un switch?',
      options: ['1',
                '1002',
                '1003',
                '1004',
                '1005',
                '0',
                '1001',
                '4095',
                '1000'],
      correctIndices: [0, 1, 2, 3, 4],
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care dintre urmatoarele VLAN-uri sunt rezervate si nu pot fi folosite?',
      options: ['1',
                '1002',
                '1003',
                '1004',
                '1005',
                '0',
                '1001',
                '4095',
                '1000'],
      correctIndices: [5, 7],
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care dintre urmatoarele reprezinta tipuri de VLAN?',
      options: ['Data',
                'Management',
                'Voice',
                'Native',
                'Default',
                'Trunking',
                'Quality',
                'Access',
                ],
      correctIndices: [0, 1, 2, 3],
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care sunt tipurile de rutare Inter-VLAN?',
      options: ['Legacy',
                'ROAS',
                'Layer 3 SVI',
                'Native Routing',
                'OSPF Routing',
                'Trunking Route',
                'Access Route',
                ],
      correctIndices: [0, 1, 2],
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care dintre versiunile pot folosi instante diferite pentru fiecare VLAN dot1q?',
      options: ['CST', 'PVST', 'PVST+', 'RSTP', 'RPVST+', 'MSTP'],
      correctIndices: [2, 4, 5], 
      },
      {
      type: 'matching',
      text: 'Asociati combinatia de porturi DTP cu functionalitatea rezultata',
      subQuestions: [
        { text: 'Dynamic Auto -> Dynamic Desirable', answer: 'Trunk' },
        { text: 'Dynamic Auto -> Dynamic Auto', answer: 'Access' },
        { text: 'Dynamic Auto -> Trunk', answer: 'Trunk' },
        { text: 'Dynamic Auto -> Access', answer: 'Access' },
        { text: 'Dynamic Desirable -> Dynamic Desirable', answer: 'Trunk' },
        { text: 'Dynamic Desirable -> Trunk', answer: 'Trunk' },
        { text: 'Dynamic Desirable -> Access', answer: 'Access' },
        { text: 'Trunk -> Trunk', answer: 'Trunk' },
        { text: 'Access -> Access', answer: 'Access' },
        { text: 'Trunk -> Access', answer: 'Limited Connectivity' },
      ],
      options: ['Trunk', 'Access', 'Limited Connectivity'],
      },
    ]
});