ACADOBRE_QUESTIONS.push({
  id: 'vtp',
    topic: 'VTP',
    questions: [
      {
      type: 'open-ended',
      text: 'Care este numele de domeniu VTP implicit?',
      acceptedAnswers: ['NULL', 'null'],
      },
      {
      type: 'multiple-choice',
      text: 'Dupa ce se tine cont de schimbarile in baza de date VTP?',
      options: ['Nume de domeniu',
                'Parola de domeniu',
                'Verisune VTP',
                'Informatie VLAN',
                'Numar de revizie VTP',
                'Status Trunk',
               ],
      correctIndex: 4,
      },
      {
      type: 'multiple-choice',
      text: 'Care este modul default de operare VTP?',
      options: ['Server',
                'Client',
                'Transparent',
                'Off',
                'On',
                'Trunk',
                'Native',
                'Access',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care mod de operare VTP va trimite mai departe informatia VLAN-urilor configurata local?',
      options: ['Server',
                'Client',
                'Transparent',
                'Off',
                'On',
                'Trunk',
                'Native',
                'Access',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care mod de operare VTP va adauga local informatia VLAN-urilor primita?',
      options: ['Server',
                'Client',
                'Transparent',
                'Off',
                'On',
                'Trunk',
                'Native',
                'Access',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Care mod de operare VTP va trimte mai departe informatia VLAN-urilor primita dar nu o va adauga local?',
      options: ['Server',
                'Client',
                'Transparent',
                'Off',
                'On',
                'Trunk',
                'Native',
                'Access',
               ],
      correctIndex: 2,
      },
      {
      type: 'multiple-choice',
      text: 'Ce se intampla daca in domeniul VTP se alatura un switch server cu un numar de revizie mai mare decat al celorlalte switchuri?',
      options: ['Configuratia VLAN de pe acel switch va suprascrie informatia de pe toate switch-urile din domeniul VTP',
                'Configuratia VLAN de pe acel switch va fi adaugata alaturi de informatia de pe toate switch-urile din domeniul VTP',
                'Nu se va intampla nimic',
                'Va transforma toate switch-urile din transparent in Client',
                'Va reseta numarul de revizie',
                'Configuratia VLAN de pe celelalte switchuri va fi adaugata pe acel switch',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca pentru a folosi VLAN-uri extended trebuie folosit VTPv3?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca nu se recomanda folosirea VTP?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca switchurile in modul de operare VTP Transparent vor trimite informatia mai departe chiar daca nu au parola corecta?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice-multi',
      text: 'De ce este nevoie pe mai multe switchuri pentru ca acestea sa participe in acelasi domeniu VTP?\nAlegeti 3 variante.',
      options: ['Nume de domeniu',
                'Parola de domeniu',
                'Verisune VTP',
                'Informatie VLAN',
                'Numar de revizie VTP',
                'Status Trunk',
               ],
      correctIndices: [0, 1, 2],
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care sunt modurile in care poate functiona un switch in VTP?\nAlegeti 4 variante.',
      options: ['Server',
                'Client',
                'Transparent',
                'Off',
                'On',
                'Trunk',
                'Native',
                'Access',
               ],
      correctIndices: [0, 1, 2, 3],
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care dintre urmatoarele modificari va reseta numarul de revizie VTP?\nAlegeti 2 variante.',
      options: ['Trecerea la modul Transparent',
                'Trecerea la modul Client',
                'Trecerea la modul Server',
                'Schimbarea numelui de domeniu',
                'Schimbarea parolei VTP',
                'Schimbarea versiunii VTP',
               ],
      correctIndices: [0, 3],
      },
    ]
});
