ACADOBRE_QUESTIONS.push({
  id: 'wifi_standards',
    topic: 'Wi-Fi Standards',
    questions: [
      {
      type: 'open-ended',
      text: 'Care este codul pentru standardul IEEE Wi-fi?',
      acceptedAnswers: ['802.11'],
      },
      {
      type: 'open-ended',
      text: 'Care este codul pentru standardul IEEE Wi-fi 4?',
      acceptedAnswers: ['802.11N', '802.11N'],
      },
      {
      type: 'open-ended',
      text: 'Care este codul pentru standardul IEEE Wi-fi 5?',
      acceptedAnswers: ['802.11ac', '802.1AC'],
      },
      {
      type: 'open-ended',
      text: 'Care este codul pentru standardul IEEE Wi-fi 6?',
      acceptedAnswers: ['802.11ax', '802.1AX'],
      },
      {
      type: 'open-ended',
      text: 'Care este codul pentru standardul IEEE Bluetooth?',
      acceptedAnswers: ['802.15'],
      },
      {
      type: 'multiple-choice',
      text: 'Care standard Wi-Fi suporta frecventa de 6 GHz?',
      options: ['802.11',
                '802.11b',
                '802.11a',
                '802.11g',
                '802.11n',
                '802.11ac',
                '802.11ax',
               ],
      correctIndex: 6,
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care standarde Wi-Fi suporta frecventa de 2.4 GHz?',
      options: ['802.11',
                '802.11b',
                '802.11a',
                '802.11g',
                '802.11n',
                '802.11ac',
                '802.11ax',
               ],
      correctIndices: [0, 1, 3, 4, 6],
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care standarde Wi-Fi suporta frecventa de 5 GHz?',
      options: ['802.11',
                '802.11b',
                '802.11a',
                '802.11g',
                '802.11n',
                '802.11ac',
                '802.11ax',
               ],
      correctIndices: [2, 4, 5, 6],
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care standarde Wi-Fi suporta doar frecventa de 2.4 GHz?',
      options: ['802.11',
                '802.11b',
                '802.11a',
                '802.11g',
                '802.11n',
                '802.11ac',
                '802.11ax',
               ],
      correctIndices: [0, 1, 3],
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care standarde Wi-Fi suporta doar frecventa de 5 GHz?',
      options: ['802.11',
                '802.11b',
                '802.11a',
                '802.11g',
                '802.11n',
                '802.11ac',
                '802.11ax',
               ],
      correctIndices: [2, 5],
      },
      {
      type: 'label-order',
      text: 'Puneti standardele Wi-Fi in oridnea bandwidth-ului\n(pentru cele au acelasi bandwidth, puneti-le de la frecventa mai mare la cea mai mica):',
      labels: ['802.11', '802.11b', '802.11a', '802.11g', '802.11n', '802.11ac', '802.11ax'],
      correctOrder: [0, 1, 2, 3, 4, 5, 6],
      },
      {
      type: 'matching',
      text: 'Asociati fiecare standard wireless cu viteza teoretica la care poate ajunge',
      subQuestions: [
        { text: '802.11', answer: '2 Mbps' },
        { text: '802.11b', answer: '11 Mbps' },
        { text: '802.11a', answer: '54 Mbps' },
        { text: '802.11g', answer: '54 Mbps' },
        { text: '802.11n', answer: '600 Mbps' },
        { text: '802.11ac', answer: '6.9 Mbps' },
        { text: '802.11ax', answer: '9.6 Mbps' },
      ],
      options: ['2 Mbps','11 Mbps', '54 Mbps', '600 Mbps', '6.93 Mbps', '9.6 Mbps'],
      },
    ]
});