ACADOBRE_QUESTIONS.push({
  id: 'wireless',
    topic: 'Wireless',
    questions: [
      {
        type: 'open-ended',
        text: 'Cum se numeste o retea wireless de acoperire geografica mai mica?',
        acceptedAnswers: ['WLAN','wlan'],
      },
      {
        type: 'open-ended',
        text: 'Cum se numeste o retea wireless de acoperire geografica mai mare?',
        acceptedAnswers: ['WWAN','wwan'],
      },
      {
      type: 'open-ended',
      text: 'Care este codul pentru standardul IEEE Wi-fi?',
      acceptedAnswers: ['802.11'],
      },
      {
      type: 'open-ended',
      text: 'Care este valoarea in MHz a latimii canalelor in care este impartita frecventa de 2.4 GHz?',
      acceptedAnswers: ['22'],
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca toate dispozitivele din aceeasi raza pot vedea toate cadrele wireless care circula?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca o retea wireless poate functiona Full-Duplex?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca in frecventa 2.4 GHz canalele se suprapun, formand un risc pentru interferente?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca in frecventa 5 GHz canalele se suprapun, formand un risc pentru interferente?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca fiecare Access Point delimiteaza un BSS diferit?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Ce mecanism este utilizat pentru a preveni coliziunile in cadrul unei retele wireless?',
      options: ['CSMA/CD', 'Token Ring', 'Collision Detection', 'CSMA/CA', 'Half-Duplex Collision Broadcast'],
      correctIndex: 3,
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care dispozitive sunt dedicate pentru conectivitate wireless?\nAlegeti 2 variante.',
      options: ['Switch', 'Router', 'Hub', 'MultiLayer Switch', 'Access Point', 'Wireless Router', 'Firewall'],
      correctIndices: [4, 5], 
      },
      {
      type: 'multiple-choice',
      text: 'Care banda wireless are de obicei cea mai mare raza de actionare?',
      options: ['2.4 GHz',
                '5 GHz',
                '6 GHz',
                '3 GHz',
                '4 GHz'
              ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care canale este recomandat sa fie utilizate in frecventa 2.4 GHz?',
      options: ['1, 6, 11',
                '2, 6, 11',
                '10, 11, 22',
                '3, 4, 5',
                '11, 12, 13'
              ],
      correctIndex: 0, 
      },
      {
      type: 'multiple-choice',
      text: 'Care termen descrie orice grup de dispozitive Wireless?',
      options: ['SS (Service Set)',
                'SSID (Service Set ID)',
                'BSS (Basic Service Set)',
                'BSSID (Basic Service Set ID)',
                'IBSS (Independent Basic Service Set)',
                'ESS (Extended Service Set)',
                'MBSS (Mesh Basic Service Set)',
                'DS (Distribution System)'
              ],
      correctIndex: 0, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele reprezinta "numele" unei retele wireless?',
      options: ['SS (Service Set)',
                'SSID (Service Set ID)',
                'BSS (Basic Service Set)',
                'BSSID (Basic Service Set ID)',
                'IBSS (Independent Basic Service Set)',
                'ESS (Extended Service Set)',
                'MBSS (Mesh Basic Service Set)',
                'DS (Distribution System)'
              ],
      correctIndex: 1, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele reprezinta o retea wireless unde dispozitivele nu folosesc un access point, ci se conecteaza direct unul la altul?',
      options: ['SS (Service Set)',
                'SSID (Service Set ID)',
                'BSS (Basic Service Set)',
                'BSSID (Basic Service Set ID)',
                'IBSS (Independent Basic Service Set)',
                'ESS (Extended Service Set)',
                'MBSS (Mesh Basic Service Set)',
                'DS (Distribution System)'
              ],
      correctIndex: 4, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele se mai poate numi o retea wireless ad-hoc?',
      options: ['SS (Service Set)',
                'SSID (Service Set ID)',
                'BSS (Basic Service Set)',
                'BSSID (Basic Service Set ID)',
                'IBSS (Independent Basic Service Set)',
                'ESS (Extended Service Set)',
                'MBSS (Mesh Basic Service Set)',
                'DS (Distribution System)'
              ],
      correctIndex: 4, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele reprezinta o retea wireless unde dispozitivele se conecteaza folosind un Access Point?',
      options: ['SS (Service Set)',
                'SSID (Service Set ID)',
                'BSS (Basic Service Set)',
                'BSSID (Basic Service Set ID)',
                'IBSS (Independent Basic Service Set)',
                'ESS (Extended Service Set)',
                'MBSS (Mesh Basic Service Set)',
                'DS (Distribution System)'
              ],
      correctIndex: 2, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele reprezinta adresa MAC a unui Access Point?',
      options: ['SS (Service Set)',
                'SSID (Service Set ID)',
                'BSS (Basic Service Set)',
                'BSSID (Basic Service Set ID)',
                'IBSS (Independent Basic Service Set)',
                'ESS (Extended Service Set)',
                'MBSS (Mesh Basic Service Set)',
                'DS (Distribution System)'
              ],
      correctIndex: 3, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele reprezinta o retea wireless unde dispozitivele se conecteaza folosind mai multe Access Point-uri?',
      options: ['SS (Service Set)',
                'SSID (Service Set ID)',
                'BSS (Basic Service Set)',
                'BSSID (Basic Service Set ID)',
                'IBSS (Independent Basic Service Set)',
                'ESS (Extended Service Set)',
                'MBSS (Mesh Basic Service Set)',
                'DS (Distribution System)'
              ],
      correctIndex: 5, 
      },
      {
      type: 'multiple-choice',
      text: 'Care dintre urmatoarele reprezinta o retea wireless unde dispozitivele se conecteaza folosind unul sau mai multe Access Point-uri, iar acele AP-uri sunt conectate wireless la retea, si nu prin fir?',
      options: ['SS (Service Set)',
                'SSID (Service Set ID)',
                'BSS (Basic Service Set)',
                'BSSID (Basic Service Set ID)',
                'IBSS (Independent Basic Service Set)',
                'ESS (Extended Service Set)',
                'MBSS (Mesh Basic Service Set)',
                'DS (Distribution System)'
              ],
      correctIndex: 6, 
      },
      {
      type: 'multiple-choice',
      text: 'Cum se numeste backbone-ul wired al unei retele wireless?',
      options: ['SS (Service Set)',
                'SSID (Service Set ID)',
                'BSS (Basic Service Set)',
                'BSSID (Basic Service Set ID)',
                'IBSS (Independent Basic Service Set)',
                'ESS (Extended Service Set)',
                'MBSS (Mesh Basic Service Set)',
                'DS (Distribution System)'
              ],
      correctIndex: 7, 
      },
      {
      type: 'multiple-choice-multi',
      text: 'Care variante NU reprezinta caracteristici ale mediului Wireless?\nAlegeti 3 variante.',
      options: ['Imunitate la interferente',
                'Pret ridicat',
                'Distanta redusa',
                'Mobilitate ridicata',
                'Distanta ridicata'
              ],
      correctIndices: [0, 1, 4], 
      },
      // wireless security
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca tot traficul wireless ar trebui sa fie criptat?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Este adevarat ca in WPA Personal (PSK), toti clientii au aceeasi cheie pentru criptare/decriptare?',
      options: ['Fals',
                'Adevarat',
               ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice',
      text: 'Care mod de autentificare in wireless este intalnit la Wi-Fi-ul public?',
      options: ['Open',
                'Keyless',
                'Free',
                'Unlocked',
                'Wide-use',
              ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Care mod de autentificare in wireless necesita clientii sa aibe un username si o parola?',
      options: ['Wired Equivalent Privacy',
                'Wi-Fi Equivalent Privacy',
                'Wi-Fi Protected Access',
                'Wired Protected Access',
                'Lightweight EAP',
                'Extensible Authentication Protocol',
                'WPA Personal Mode',
              ],
      correctIndex: 4,
      },
      {
      type: 'multiple-choice',
      text: 'Care mod de operare wireless ofera suport pentru serviciul AAA prin RADIUS/TACACS+?',
      options: ['WPA Enterprise Mode',
                'WPA Company Mode',
                'WEP',
                'WEP Company Mode',
                'WEP Enterprise Mode',
                'WPA Personal Mode (PSK)'
              ],
      correctIndex: 0,
      },
      {
      type: 'multiple-choice',
      text: 'Ce tip de WPA foloseste criptare TKIP?',
      options: ['WPA Enterprise Mode',
                'WPA',
                'WPA2',
                'WPA3',
                'WEP',
                'WEP Company Mode',
                'WEP Enterprise Mode',
                'WPA Personal Mode'
              ],
      correctIndex: 1,
      },
      {
      type: 'multiple-choice-multi',
      text: 'Ce tipuri de WPA folosesc criptare AES?\nAlegeti 2 variante.',
      options: ['WPA Enterprise Mode',
                'WPA',
                'WPA2(CCMP)',
                'WPA3(GCMP)',
                'WEP',
                'WEP Company Mode',
                'WEP Enterprise Mode',
                'WPA Personal Mode'
              ],
      correctIndices: [2, 3], 
      },
    ]
});
