window.ACADOBRE_ALT_QUESTIONS.push({
  id: 'judeteana_2025_9_10',
  topic: 'Judeteana 9-10 2025',
  questions: [
  {
    type: 'multiple-choice',
    text: 'Care dintre următoarele afirmații descrie corect modul în care funcționează un atac de tip DDoS?',
    options: [
      'Este un atac care implică modificarea parametrilor de rețea ai unui dispozitiv pentru a-l face invizibil pe internet.',
      'Este un atac coordonat de la multe dispozitive cu intenţia de a degrada sau opri accesul public la site-ul web.',
      'Este un atac în care computerele unei organizaţii sunt infectate cu software dăunător.',
      'Este un atac care se bazează pe criptografie avansată pentru a ascunde sursa atacului și a evita detectarea.',
      'Este un atac care folosește viruși pentru infectarea de computerele și le transformă în roboți care pot lansa atacuri simultane.',
      'Esre un atac care funcționează prin schimbarea setărilor de rețea ale serverului țintă, astfel încât serverul nu mai poate comunica cu alte dispozitive din rețea.',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Ce face scurtătura ESC+D în Cisco IOS?',
    options: [
      'Scoate utilizatorul din modul privilegiat',
      'Duce cursorul la începutul cuvântului',
      'Șterge toate caracterele de la cursor la sfârșitul cuvântului',
      'Nimic',
      'Niciun răspuns nu e corect',
      'Duce cursorul la sfârșitul cuvântului',
    ],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'Conform topologiei de mai jos, care switch va fi ales root bridge?',
    image: 'subiecte_acad/images/judeteana_2025_910/q3.png',
    options: ['Switch0', 'Switch4', 'Switch5', 'Switch1', 'Switch2', 'Switch3', 'Switch6', 'Switch7'],
    correctIndex: 6,
  },
  {
    type: 'multiple-choice',
    text: 'Care este coamanda utilizată pe un router Cisco pentru a vizualiza tabela ARP?',
    options: ['print ip arp', 'show ip arp table', 'arp -l', 'show ip arp', 'arp -a', 'show arp table'],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice',
    text: 'Ce reprezintă acronimul STP?',
    options: [
      'Secure Transport Protocol',
      'Spanning Tree Protocol',
      'Standard Transmission Protocol',
      'Subnetting Transmission Protocol',
      'Signal Transfer Protocol',
      'Storage Transfer Protocol',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care sunt caracteristicile protocolului Transmission Control Protocol (TCP)?\n(Selectați 3 răspunsuri)',
    options: [
      'Nu retrimite datele pierdute',
      'Control al fluxului',
      'Fiabilitate',
      'Best-effort',
      'Orientat pe conexiune',
      'Procesare rapidă',
    ],
    correctIndices: [1, 2, 4],
  },
  {
    type: 'multiple-choice',
    text: 'Care dintre următoarele configurații este corectă pentru a permite comunicarea inter-VLAN folosind metoda Router-on-a-Stick? Având în vedere următoarea topologie:\nHR - VLAN 11 -> 192.168.1.0/24\nIT - VLAN 22 -> 192.168.2.0/24\nAtenție! Comunicarea dintre PC-uri trebuie să fie funcțională.',
    image: 'subiecte_acad/images/judeteana_2025_910/q7.png',
    options: [
      'en\nconf t\nint Gig0/0/0.11\nencapsulation dot1q 11\nip add 192.168.1.1 255.255.255.0\nint Gig0/0/0.22\nencapsulation dot1q 22\nip add 192.168.2.1 255.255.255.0\nexit\nexit\nwr\nexit',
      'en\nconf t\nint Gig0/0/0.11\nencapsulation dot1q 11\nip add 192.168.1.1 255.255.255.0\nint Gig0/0/0.22\nencapsulation dot1q 22\nip add 192.168.2.1 255.255.254.0\nint Gig0/0/0\nno sh\nexit\nexit\nwr\nexit',
      'en\nconf t\nint Gig0/0/1.11\nencapsulation dot1q 11\nip add 192.168.1.1 255.255.255.0\nint Gig0/0/0.22\nencapsulation dot1q 22\nip add 192.168.2.1 255.255.255.0\nint Gig0/0/0\nno sh\nexit\nexit\nwr\nexit',
      'en\nconf t\nint Gig0/0/0.11\nencapsulation dot1q 11\nip add 192.168.1.1 255.255.255.0\nint Gig0/0/0.22\nencapsulation dot1q 22\nip add 192.168.2.1 255.255.255.0\nint Gig0/0/0\nno sh\nexit\nexit\nwr\nexit',
      'en\nconf t\nint Gig0/0/0.11\nip add 192.168.1.1 255.255.255.0\nint Gig0/0/0.22\nip add 192.168.2.1 255.255.255.0\nint Gig0/0/0\nno sh\nexit\nexit\nwr\nexit',
      'en\nconf t\nint Gig0/0/1.11\nencapsulation dot1q 11\nip add 192.168.1.1 255.255.255.0\nint Gig0/0/1.22\nencapsulation dot1q 22\nip add 192.168.2.1 255.255.255.0\nint Gig0/0/0\nno sh\nexit\nexit\nwr\nexit',
    ],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Ce reprezintă acronimul "AAA" în contextul rețelelor și securității? (Alegeți trei variante)',
    options: ['Accounting', 'Advanced', 'Automatization', 'Authentication', 'Authorization', 'Access'],
    correctIndices: [0, 3, 4],
  },
  {
    type: 'multiple-choice',
    text: 'Care este Root Path Cost-ul pentru protocolul RSTP (standardul IEEE 802.1w) pentru o interfață ce suportă o viteză maximă de 1Gb/s?',
    options: ['20000', '2000', 'Niciun răspuns nu este corect.', '200000', '200001', '20000000'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Care este codul unui mesaj Destination Unreachable ICMPv6 ce returnează eroarea "No route to destination"?',
    options: ['5', '3', '1', '2', '4', '0'],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'Care din variantele de mai jos reprezintă un standard pentru un protocol de autentificare și control al accesului bazat pe porturi?',
    options: ['IEEE 802.3x', 'IEEE 802.15.1', 'IEEE 802.1D', 'IEEE 802.1X', 'IEEE 802.11ax', 'IEEE 802.1Q'],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice',
    text: 'Stabiliți dacă afirmația următoare este adevărată sau falsă:\nMetodele de interconectare Router-on-a-Stick și Legacy Inter-VLAN Routing necesită o singură interfață fizică Ethernet pe router.',
    options: ['True', 'False'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Care este numărul maxim de porturi Ethernet, compatibil configurate, aflate pe un switch Catalyst 2960, ce pot forma un EtherChannel?',
    options: ['4', '16', '8', '20', '22', '10'],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care sunt cele trei flag-uri esențiale din mesajele RA ale DHCP pentru IPv6? (Selectați 3 variante)',
    options: [
      'Other Configuration flag',
      'Source Flag',
      'Timing Flag',
      'Adress Autoconfiguration flag',
      'Host Flag',
      'Managed Adress Configuration flag',
    ],
    correctIndices: [0, 3, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Conform topologiei de mai jos, ce port trebuie configurat ca default-gateway pe PC1 pentru a putea comunica cu PC4?',
    image: 'subiecte_acad/images/judeteana_2025_910/q15.png',
    options: [
      'Router2: Gig0/0',
      'Router0: Gig0/1',
      'Router2: Gig0/1',
      'Router1: Gig0/1',
      'Router0: Gig0/0',
      'Router0: Gig0/0',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Care este comportamentul unui switch, în timpul unui atac de tip "MAC Address Table Flooding" activ, atunci când acesta primește un nou frame pe o interfață? Switch-ul are tabela CAM plină.',
    options: [
      'Switch-ul își resetează tabela CAM si reține noua asociere în interiorul acesteia.',
      'Switch-ul trimite frame-ul prin ultimul port asociat în tabela CAM.',
      'Switch-ul șterge cele mai vechi intrări din tabela CAM și adaugă o noua asociere, astfel tabela rămânând plină și ocupând, în același timp, spațiu.',
      'Switch-ul așteaptă golirea tabelei CAM, adaugă o nouă intrare în interiorul acesteia și trimite mai departe pachetul.',
      'Switch-ul tratează frame-ul ca pe un unicast necunoscut și face flooding, la tot traficul primit, către toate porturile asociate aceluiași VLAN, fără a mai consulta tabela CAM.',
      'Switch-ul verifică tabela CAM, iar dacă adresa MAC destinație nu se află în interiorul acesteia pachetul nu se trimite mai departe.',
    ],
    correctIndex: 4,
  },
  {
    type: 'matching',
    text: 'Ordonați pașii obținerii unei adrese IP prin DHCP. (Ordonați de sus în jos)',
    subQuestions: [
      { text: '1.', answer: 'DHCP Discover' },
      { text: '2.', answer: 'DHCP Offer' },
      { text: '3.', answer: 'DHCP Request' },
      { text: '4.', answer: 'DHCP Acknowledgment' },
    ],
    options: ['DHCP Offer', 'DHCP Renew', 'DHCP Acknowledgment', 'DHCP Accept', 'DHCP Discover', 'DHCP Request'],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre urmatoarele afirmații sunt false? (Alegeți 2 variante)',
    options: [
      'Fast port speeds este o caracteristică a unui router ce poate suporta viteze de până la 10 Gbps',
      'Tehnica store-and-forward ia o decizie abia după ce primește tot cadrul și îi verifică FCS-ul',
      'Tehnica cut-through începe să trimită cadre imediat ce determină MAC-ul destinație și portul de egress',
      'Large frame buffers sunt folosite de switch pentru a desface frame-uri primite',
      'Fast internal switching se referă la utilizarea unei memorii comune pentru a atinge viteze mai mari',
      'High port density se referă la numărul fizic de porturi ale unui switch',
    ],
    correctIndices: [0, 3],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre cele de mai jos reprezintă comenzile pentru verificarea functionalităţii unui server DHCPv4? (Alegeţi 2 variante)',
    options: [
      'show ip dhcp configurations',
      'show ip dhcp pool',
      'show dhcp configurations',
      'show ip dhcp',
      'show dhcp statistics',
      'show ip dhcp binding',
    ],
    correctIndices: [1, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Având spaţiul de adrese 105.26.78.142/22 şi următoarele cerinţe pentru departamente:\nHR - 20 hosturi\nIT - 70 hosturi\nVANZARI - 30 hosturi\nADMIN - 10 hosturi\nROUTER3 - ROUTER4: 2 hosturi\nROUTER4 - ROUTER2: 2 hosturi\nDeterminaţi adresa de reţea şi adresa de broadcast pentru departamentele: VÂNZĂRI şi ADMIN.\nAtenţie! Alocarea IP-urilor s-a făcut eficient, iar gateway-ul a fost inclus în numărul total de hosturi.',
    image: 'subiecte_acad/images/judeteana_2025_910/q20.png',
    options: [
      'VANZARI: 105.26.79.14/27 - 105.26.79.45/27\nADMIN: 105.26.79.78/28 - 105.26.79.93/28',
      'VANZARI: 105.26.0.128/27 - 105.26.0.159/27\nADMIN: 105.26.0.192/28 - 105.26.0.207/28',
      'VANZARI: 105.26.0.129/27 - 105.26.0.160/27\nADMIN: 105.26.0.193/28 - 105.26.0.208/28',
      'VANZARI: 105.26.0.0/27 - 105.26.0.35/27\nADMIN: 105.26.0.36/28 - 105.26.0.51/28',
      'VANZARI: 105.26.79.15/27 - 105.26.79.46/27\nADMIN: 105.26.79.79/28 - 105.26.79.94/28',
      'VANZARI: 105.26.0.0/27 - 105.26.0.34/27\nADMIN: 105.26.0.35/28 - 105.26.0.50/28',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Care este adresa de reţea şi adresa de broadcast a host-ului care are asignată adresa IPv4: 196.68.75.22 cu masca /22?',
    options: [
      'Adresa de reţea: 196.68.72.0\nAdresa de broadcast: 196.68.75.255',
      'Adresa de reţea: 196.68.75.255\nAdresa de broadcast: 196.68.72.0',
      'Adresa de reţea: 196.68.72.0\nAdresa de broadcast: 196.68.75.0',
      'Adresa de reţea: 196.68.75.0\nAdresa de broadcast: 196.68.72.0',
      'Adresa de reţea: 196.68.72.1\nAdresa de broadcast: 196.68.75.254',
      'Adresa de reţea: 196.68.75.0\nAdresa de broadcast: 196.68.75.255',
    ],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre următoarele VLAN-uri sunt create automat? (Alegeți 3 variante)',
    options: ['VLAN 1003', 'VLAN 3', 'VLAN 1', 'VLAN 1001', 'VLAN 5', 'VLAN 1005'],
    correctIndices: [0, 2, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Care este numărul maxim de adrese IP asignabile în rețeaua 192.168.0.0/16?',
    options: ['65.532 adrese', '32768', '32766 adrese', '65.536 adrese', '65.534 adrese', '32770'],
    correctIndex: 4,
  },
  {
    type: 'matching',
    text: 'Asociați fiecare element din comanda următoare cu termenul corect care îl definește:',
    subQuestions: [
      { text: 'Switch>', answer: 'Prompt' },
      { text: 'ping', answer: 'Command' },
      { text: '192.168.10.5', answer: 'Keyword(s) or Argument(s)' },
    ],
    options: ['Prompt', 'Command', 'Keyword(s) or Argument(s)'],
  },
  {
    type: 'matching',
    text: 'Asociaţi fiecare definiţie cu termenul corespunzător:',
    subQuestions: [
      { text: 'Stochează câte 64 de biţi, apoi îi trimite pe toţi o dată.', answer: 'Cut-through: Fragment-free' },
      { text: 'Fiecare port are alocată propria coadă, unde pot fi stocate cadrele.', answer: 'Port-based memory' },
      { text: 'Toate porturile au în comun aceelaşi spaţiu de memorie pentru a stoca cadrele.', answer: 'Shared memory' },
      { text: 'Imediat ce primeşte adresa destinaţie, trimite pachetul mai departe.', answer: 'Cut-through: Fast-forward' },
      { text: 'Primeşte tot cadrul iar apoi îl trimite mai departe dacă nu prezintă erori.', answer: 'Store and forward' },
    ],
    options: ['Cut-through: Fragment-free', 'Port-based memory', 'Shared memory', 'Cut-through: Fast-forward', 'Store and forward'],
  },
  {
    type: 'multiple-choice',
    text: 'Împotriva cărui tip de atac de securitate este utilizat mecanismul Dynamic ARP Inspection (DAI)?',
    options: ['CDP Reconnaissance', 'ARP attack', 'STP attack', 'DHCP attack', 'VLAN attack', 'MAC Address Table attack'],
    correctIndex: 1,
  },
  {
    type: 'matching',
    text: 'Completați corect header-ul UDP de mai jos, plasând câmpurile acestuia în zonele corespunzatoare.\nCadran stânga-sus: biții 0-15\nCadran dreapta-sus: biții 16-31\nCadran stânga-jos: biții 32-47\nCadran dreapta-jos: biții 47-63',
    subQuestions: [
      { text: 'Cadran stânga-sus (biții 0-15)',   answer: 'Source Port' },
      { text: 'Cadran dreapta-sus (biții 16-31)', answer: 'Destination Port' },
      { text: 'Cadran stânga-jos (biții 32-47)',  answer: 'Length' },
      { text: 'Cadran dreapta-jos (biții 47-63)', answer: 'Checksum' },
    ],
    options: ['Source Port', 'Destination Port', 'Length', 'Checksum'],
  },
  {
    type: 'multiple-choice',
    text: 'PC0 trimite un pachet către PC2, dar pachetul nu ajunge la destinație. Care este cauza acestei probleme?',
    image: 'subiecte_acad/images/judeteana_2025_910/q28.png',
    options: [
      'PC0 nu are adresă IP',
      'VLAN-ul nativ este diferit',
      'Portul Fa0/3 este oprit',
      'PC2 și PC0 nu fac parte din același VLAN',
      'Porturile sunt în modul trunk',
      'Porturile sunt în modul access',
    ],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice',
    text: 'Evaluați următoarea afirmație cu adevărat sau fals:\nVLAN 1 poate fi șters din configurația unui switch, daca acesta nu este necesar pentru rețea.',
    options: ['True', 'False'],
    correctIndex: 1,
  },
  {
    type: 'matching',
    text: 'Potriviți codurile pentru ICMPv4 cu descrierea lor:',
    subQuestions: [
      { text: '0', answer: 'Net unreachable' },
      { text: '1', answer: 'Host unreachable' },
      { text: '2', answer: 'Protocol unreachable' },
      { text: '3', answer: 'Port unreachable' },
    ],
    options: ['Port unreachable', 'Host unreachable', 'Net unreachable', 'Protocol unreachable'],
  },
  {
    type: 'multiple-choice',
    text: 'Ce adresa va fi folosită drept destinație pentru o ruta defaut în cazul protocolului IPv6?',
    options: ['255.255.255.0', '::1/127', '::/0', 'Niciun răspuns nu este corect.', '::/128', '0.0.0.0'],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Cum va arăta adresa de destinaţie dacă un host doreşte să testeze funcţionarea stivei TCP/IP? (Selectaţi două răspunsuri)',
    options: ['::0', '130.0.0.1', '::10', '128.0.0.1', '127.0.0.1', '::1'],
    correctIndices: [4, 5],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care sunt mesajele ICMP specifice pentru IPv6? (Alegeți 4 variante)',
    options: [
      'Router Advertisement',
      'Neighbor Advertisement',
      'Router Solicitation',
      'Neighbor Solicitation',
      'Discovery Advertisement',
      'Discovery Solicitation',
    ],
    correctIndices: [0, 1, 2, 3],
  },
  {
    type: 'multiple-choice',
    text: 'Care dintre protocoalele de mai jos ajută la identificarea adresei MAC, dacă se cunoaşte adresa IPv6 destinaţie?',
    options: ['ND', 'IP', 'DN', 'MACP', 'ARP', 'TFTP'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Care dintre următoarele adrese MAC este o adresa de tip multicast:',
    options: [
      'FFFF:FFFF:FFFF',
      'Niciun răspuns nu este corect',
      '0110:5E00:00C8',
      '9869:1251:1252',
      '0100:5E00:00C8',
      'FFFF:FFFF:EEEE',
    ],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care sunt părțile corespunzătoare unei adrese IPv6 Unicast Globală (GUA)?\n(Selectați 3 răspunsuri)',
    options: ['Subnet ID', 'Prefix ID', 'Global Routing Prefix', 'Subnet Prefix', 'Local ID', 'Interface ID'],
    correctIndices: [0, 2, 5],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Selectați care din următoarele adrese IPv4 sunt private.\n(Selectați 3 răspunsuri)',
    options: [
      '172.16.0.0/12',
      '172.16.0.0/16',
      '10.0.0.0/16',
      '192.168.0.0/16',
      '172.0.0.1/8',
      '10.0.0.0/8',
    ],
    correctIndices: [0, 3, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Care este numărul minim de rute statice pentru a asigura conectivitatea completă între toate dispozitivele, fără utilizarea rutelor default sau sumarizate?',
    image: 'subiecte_acad/images/judeteana_2025_910/q38.png',
    options: ['14', '15', '13', '12', '17', '16'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Stabiliți valoarea de adevăr a urmatoarei afirmații:\nAdresa MAC poate fi schimbată din software.',
    options: ['Adevărat', 'Fals'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Ce metodă de livrare este folosită pentru a transmite informaţii către un grup specific de dispozitive dintr-o reţea?',
    options: ['Morecast', 'Unicast', 'Somecast', 'Manycast', 'Multicast', 'Broadcast'],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Care sunt comenzile necesare pentru a configura portul Fa0/3 al switch-ului astfel încât să aibă acces exclusiv la VLAN-ul 10?',
    image: 'subiecte_acad/images/judeteana_2025_910/q41.png',
    options: [
      'Switch>en\nSwitch#configure terminal\nSwitch(config)#vlan 20\nSwitch(config-vlan)#exit\nSwitch(config)#interface Fa0/3\nSwitch(config-if)#switch access vlan 20',
      'Switch>configure terminal\nSwitch#vlan 10\nSwitch(config)#exit\nSwitch(config-vlan)#interface Fa0/3\nSwitch(config)#switch mode access\nSwitch(config-if)#switch access vlan 10',
      'Switch>en\nSwitch#configure terminal\nSwitch(config)#switch mode access\nSwitch(config)#switch access vlan 10',
      'Switch>en\nSwitch#configure terminal\nSwitch(config)#interface Fa0/4\nSwitch(config-if)#switch mode access\nSwitch(config-if)#switch access vlan 10',
      'Switch>en\nSwitch#configure terminal\nSwitch(config)#vlan 10\nSwitch(config-vlan)#exit\nSwitch(config)#interface Fa0/3\nSwitch(config-if)#switch mode access\nSwitch(config-if)#switch access vlan 10',
      'Switch#configure terminal\nSwitch(config)#vlan 10\nSwitch(config-vlan)#exit\nSwitch(config-if)#switch mode access\nSwitch(config-if)#switch access vlan 10',
    ],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Cum se prescurtează corect adresa IPv6 fd00:0498:0000:acad:0000:0000:0000:0010 ?',
    options: [
      'fd00:498:0:acad:0:10',
      'fd00:0498:0:acad::11',
      'fd00:498:0:acad::10',
      'fd:498:0:acad::1',
      'fd00:498::acad::10',
      'fd:498:0:acad::10',
    ],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'Pe baza cărui principiu se stabilește ruta unui pachet într-un router?',
    options: [
      'Principiul "first come, first served"',
      'Algoritmul de tip "shortest path first"',
      'Algoritmul de tip "random path selection"',
      'Algoritmul de tip "path vector"',
      'Principiul "best path equals longest match"',
      'Algoritmul de tip "least cost path"',
    ],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care din urmatoarele protocoale sunt de nivel 3? (Alegeți 3 variante)',
    options: ['TFTP', 'TCP', 'IP', 'ARP', 'UDP', 'ICMP'],
    correctIndices: [2, 3, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Care este portul standard utilizat de serviciul HTTP?',
    options: ['22', '69', '23', '20', '443', '80'],
    correctIndex: 5,
  },
  {
    type: 'matching',
    text: 'Alegeţi care vor fi valorile flag-urilor dintr-un mesaj RA, pentru cazul stateless DHCP: ( x înseamnă "orice valoare")',
    subQuestions: [
      { text: 'A =', answer: '1' },
      { text: 'O =', answer: '1' },
      { text: 'M =', answer: '0' },
    ],
    options: ['2', 'x', '4', '1', '0', '3'],
  },
  {
    type: 'multiple-choice',
    text: 'Care din următoarele comenzi ne ajută să configurăm în CLI un switch virtual interface ?',
    options: [
      'Switch>en\nSwitch#configure terminal\nSwitch(config)#interface vlan 10\nSwitch(config-if)#ipv6 address 123.213.12.19 255.255.255.0\nSwitch(config-if)#no shutdown\nSwitch(config-if)#exit\nSwitch(config)#ip default-gateway 123.123.12.1\nSwitch(config)#write',
      'Switch>configure terminal\nSwitch#en\nSwitch(config)#interface vlan 10\nSwitch(config-if)#ipv5 address 123.213.12.19 255.255.256.0\nSwitch(config-if)#no shutdown\nSwitch(config-if)#exit\nSwitch(config)#ip default-gateway 123.213.12.1\nSwitch(config)#write',
      'Switch>en\nSwitch#configure terminal\nSwitch(config)#ip address 123.213.12.19 255.255.255.0\nSwitch(config)#no shutdown\nSwitch(config)#exit\nSwitch#ip default-gateway 123.213.12.1\nSwitch#write',
      'Switch>en\nSwitch#configure terminal\nSwitch(config)#interface vlan 10\nSwitch(config-if)#ip address 123.213.12.19 255.255.255.0\nSwitch(config-if)#no shutdown\nSwitch(config-if)#exit\nSwitch(config)#ip default-gateway 123.213.12.1 255.255.255.0\nSwitch(config)#write',
      'Switch>interface vlan 10\nSwitch(config-if)#ip address 123.213.12.19 255.255.255.0\nSwitch(config-if)#no shutdown\nSwitch(config-if)#exit\nSwitch(config)#ip default-gateway 123.213.12.1\nSwitch(config)#do write',
      'Switch>en\nSwitch#configure terminal\nSwitch(config)#interface vlan 10\nSwitch(config-if)#ip address 123.213.12.19 255.255.255.0\nSwitch(config-if)#no shutdown\nSwitch(config-if)#exit\nSwitch(config)#ip default-gateway 123.213.12.1\nSwitch(config)#do write',
    ],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'Un client are adresa IP 183.105.27.3 și dorește să se conecteze la un server web prin protocolul HTTP. Portul sursă dinamic asignat host-ului este 52025, iar adresa serverului este 183.105.27.10. Cum va arăta perechea socket?',
    options: [
      '52025:183.105.27.3, 80:183.105.27.10',
      '183.105.27.3:52025, 183.105.27.10:80',
      '183.105.27.3:52025, 183.105.27.10:800',
      '183.105.27.3:52025, 183.105.27.10:88',
      '183.105.27.3:80, 183.105.27.10:52025',
      '52025:183.105.27.3, 443:183.105.27.10',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'La ce se referă un atac de tip DHCP spoofing?',
    options: [
      'Interceptarea și modificarea pachetelor de date între două puncte de comunicație.',
      'Compromiterea unui router pentru a redirecționa traficul către un server neautorizat.',
      'Deschiderea neautorizată a porturilor de rețea pentru a permite accesul necontrolat.',
      'Atacul asupra sistemului de operare al unui server DHCP pentru a-l opri temporar.',
      'Oferirea de informații false clienților despre default gateway, adrese IP și server DNS.',
      'Modificarea adreselor IP atribuite de un server DHCP într-o rețea locală.',
    ],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care sunt 2 metode prin care putem verifica strict conectivitatea dintre echipamente? (Alegeți două variante)',
    options: ['Telnet', 'Traceroute', 'POP3', 'SSH', 'Ping', 'HTTP'],
    correctIndices: [1, 4],
  },
]
});
