window.ACADOBRE_ALT_QUESTIONS.push({
  id: 'judeteana_2025_11_12',
  topic: 'Judeteana 11-12 2025',
  questions: [
  {
    type: 'matching',
    text: 'Care sunt pașii pentru a configura un Cisco Zone-Based Policy Firewalls?',
    subQuestions: [
      { text: '1', answer: 'Crearea zonelor' },
      { text: '2', answer: 'Identificarea traficului folosind un class-map' },
      { text: '3', answer: 'Definirea unei acțiuni folosind un policy-map' },
      { text: '4', answer: 'Identificarea unei perechi de zone și asignarea unui policy-map' },
      { text: '5', answer: 'Asignarea zonelor interfețelor potrivite' },
    ],
    options: [
      'Definirea unei acțiuni folosind un policy-map',
      'Crearea zonelor',
      'Identificarea traficului folosind un class-map',
      'Identificarea unei perechi de zone și asignarea unui policy-map',
      'Asignarea zonelor interfețelor potrivite',
    ],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre următoarele echipamente separă domeniile de coliziune?(Alegeți 2 variante)',
    options: ['ruterul', 'cablul coaxial', 'repeter-ul', 'hub-ul', 'cablu UTP', 'switchul'],
    correctIndices: [0, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Care este valoarea (în format hexazecimal) setată în câmpul "Type", din interiorul VLAN Tag-ului, pentru un cadru Ethernet?',
    options: ['0x8100', '0x86DD', '0x8006', '0x8000', '0x0800', '0x8809'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Observam prezenta a 4 zone (Database, Management, IT, R0-R1).\nIn fiecare zona avem nevoie de urmatorul numar de host-uri:\nIT - 20 host-uri;\nManagement - 10 host-uri;\nDatabase - 30 host-uri;\nR0 - R1 - 2 host-uri.\nSpatiul de adrese care trebuie subnetat este: 142.138.102.22/23.\nSubnetați în mod optim și determinați spațiul de adresare corespunzător pentru zona IT.',
    image: 'subiecte_acad/images/judeteana_2025_1112/q4.png',
    options: [
      '142.138.102.16/28 - 142.138.102.37/28',
      '142.138.102.0/27 - 142.138.102.21/27',
      '142.138.102.0/27 - 142.138.102.31/27',
      '142.138.102.32/27 - 142.138.102.63/27',
      '142.138.102.64/28 - 142.138.102.79/28',
    ],
    correctIndex: 3,
  },
  {
    type: 'matching',
    text: 'Asociați fiecărui scenariu, cel mai potrivit protocol de transport.',
    subQuestions: [
      { text: 'Maria vrea să configureze un serviciu de internet banking. Ce protocol de transport ar trebui să utilizeze?', answer: 'TCP' },
      { text: 'Ana vrea să configureze un serviciu de video-conferință. Ce protocol de transport ar trebui să utilizeze?', answer: 'UDP' },
      { text: 'Alex vrea să configureze un server de media-streaming, în cadrul căruia conținutul este deja stocat pe server. Ce protocol de transport ar trebui să utilizeze?', answer: 'TCP' },
      { text: 'George vrea să dezvolte un joc online multiplayer. Ce protocol de transport ar trebui să utilizeze?', answer: 'UDP' },
      { text: 'Marius vrea să creeze un serviciu de streaming live. Ce protocol de transport ar trebui să utilizeze?', answer: 'UDP' },
    ],
    options: ['TCP', 'UDP'],
  },
  {
    type: 'multiple-choice',
    text: 'Care dintre protocoalele de mai jos ajută la identificarea adresei MAC, dacă se cunoaşte adresa IPv4 destinaţie?',
    options: ['ARP', 'FTP', 'MACP', 'ND', 'IP', 'SMTP'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Care este funcția protocolului Hot Standby Router Protocol (HSRP)?',
    options: [
      'Acesta este folosit pentru a modifica starea router-ului din "active" în "standby".',
      'Acesta este folosit pentru a bloca porturile router-ului în cazul unui atac de securitate.',
      'Acesta este utilizat pentru a alege un router activ și unul în starea de standby dintre două routere.',
      'Acesta este folosit pentru a determina adresa default gateway-ului dintr-o subrețea în care sunt configurate cel puțin două routere.',
      'Acesta este folosit pentru a face asocierea dintre o adresa MAC și o adresă IP într-o subrețea.',
      'Acesta este folosit pentru a asigna automat adrese IPv6 host-urilor din rețea.',
    ],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre metodele de mai jos sunt folosite pentru a iniția un password attack?\n(Selectați 3 răspunsuri)',
    options: [
      'Port Redirection attack',
      'Packet Sniffer',
      'Distributed Denial of Service (DDoS) attack',
      'Trojan horse attack',
      'Brute-force attack',
      'Denial of Service (DoS) attack',
    ],
    correctIndices: [1, 3, 4],
  },
  {
    type: 'multiple-choice',
    text: 'Stabiliţi dacă următoarea propoziţie este adevărată sau falsă:\nÎn tabela de rutare, rutele de tipul "direct conectate" sunt notate cu D.',
    options: ['True', 'False'],
    correctIndex: 1,
  },
  {
    type: 'matching',
    text: 'Ordonați în ordinea corectă pașii pe care îi urmează un host pentru a-și obține adresa IPv6 prin DHCPv6.\nATENȚIE! Completați de sus în jos.',
    subQuestions: [
      { text: '1', answer: 'Calculatorul (hostul) trimite mesaj RS' },
      { text: '2', answer: 'Ruterul răspunde cu un mesaj RA' },
      { text: '3', answer: 'Host-ul trimite un mesaj de solicitare DHCP' },
      { text: '4', answer: 'Serverul DHCPv6 răspunde cu un mesaj acceptare a cererii DHCP.' },
      { text: '5', answer: 'Host-ul răspunde serverului DHCPv6' },
      { text: '6', answer: 'Serverul trimite hostului adresa IPv6 negociată' },
    ],
    options: [
      'Hostul trimite un mesaj NA',
      'Host-ul trimite un mesaj de solicitare DHCP',
      'Ruterul răspunde cu un mesaj RA',
      'Host-ul răspunde serverului DHCPv6',
      'Calculatorul (hostul) trimite mesaj RS',
      'Serverul trimite hostului adresa IPv6 negociată',
      'Serverul DHCPv6 răspunde cu un mesaj acceptare a cererii DHCP.',
    ],
  },
  {
    type: 'multiple-choice',
    text: 'Ce switch din tabelul de mai jos va fi ales Root Bridge în cadrul protocolului STP?',
    image: 'subiecte_acad/images/judeteana_2025_1112/q11.png',
    options: ['B', 'D', 'A', 'E', 'C', 'F'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Care este comanda pentru a verifica translațiile făcute cu ajutorul metodei Port Address Translation (PAT) pe un router Cisco?',
    options: [
      'show switch port translations',
      'show nat pat translations',
      'show port translations',
      'show pat translations',
      'show ip nat translations',
      'show ip pat translations',
    ],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Ce reprezintă un socket?',
    options: [
      'O combinație doar între adresa IP sursă și portul sursă.',
      'Un număr pe 16 biți ce identifică doar portul sursă.',
      'Un număr pe 32 de biți ce identifică adresa IP a unui host în rețea.',
      'O combinație între adresa IP sursă și portul sursă sau între adresa IP destinație și portul destinație.',
      'O combinație doar între adresa IP destinație și portul destinație.',
      'Un număr pe 16 biți ce identifică un port destinație sau un port sursă.',
    ],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice',
    text: 'Care ar putea fi potențialele probleme ale ARP-ului într-o rețea:',
    options: [
      'Îngreunează trimiterea PDU-urilor din cauza căutării secvențiale în tabelă.',
      'Niciun răspuns nu este corect',
      'Posibilitatea pierderii unui pachet din cauza mărimi lor',
      'Broadcast-urile care pot încarca rețeaua',
      'Permite circulația pachetelor compromise',
      'Complexitatea maparii între adresele MAC și IP consumă resurse ale dispozitivelor',
    ],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice',
    text: 'Un host cu adresa MAC B6:2A:F5:01:20:25, dorește să își genereze o adresa IPv6, în urma primiri prefixului 2053:601B:0001:C6ED::/64 printr-un Router Advertisement (RA). Care va fi adresa IPv6 finală, dacă acesta folosește metoda EUI-64?',
    options: [
      '2053:601B:0001:C6ED:B42A:F5FF:FE01:2025',
      '2053:601B:0001:C6ED:B42A:F5FF:FF01:2025',
      'B62A:F5FF:FF01:2025:2053:601B:0001:C6ED',
      '2053:601B:0001:C6ED:B62A:F5FF:FE01:2025',
      '2053:601B:0001:C6ED:B62A:F5FE:FE01:2025',
      '2053:601B:0001:C6ED:B42A:F501:FFFE:2025',
    ],
    correctIndex: 0,
  },
  {
    type: 'label-order',
    text: 'Așezați în ordine etapele atingerii convergenței a DR-ului în cadrul protocolului OSPF. (Ordinea etapelor trebuie sa fie de sus în jos.)',
    labels: ['Init State', 'Full State', 'Two-way State', 'Exchange State', 'Down state', 'Loading State', 'ExStart State'],
    correctOrder: [4, 0, 2, 6, 3, 5, 1],
  },
  {
    type: 'matching',
    text: 'Selectați masca wildcard/forma prescurtată corespunzătoare.',
    subQuestions: [
      { text: '/19 -', answer: '0.0.31.255' },
      { text: '0.0.1.255 -', answer: '/23' },
      { text: '/29 -', answer: '0.0.0.7' },
      { text: '0.7.255.255 -', answer: '/13' },
      { text: '/31 -', answer: '0.0.0.1' },
    ],
    options: ['/21', '0.0.31.255', '/20', '/13', '/14', '/23', '0.0.255.255', '0.0.0.1', '0.0.0.7', '1.127.255.255'],
  },
  {
    type: 'multiple-choice',
    text: 'Ce conține un certificat Public Key Infrastructure (PKI)?',
    options: [
      'Algoritmul utilizat pentru a crea semnătura',
      'Cheia publică a unei entități sau a unei persoane',
      'Autoritatea de certificare (CA) care a validat și eliberat certificatul',
      'Niciuna nu e corectă',
      'Scopul certificatului',
      'Toate răspunsurile sunt corecte',
    ],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'După ce intervale de numere este identificat un ACL standard?',
    options: [
      '200-299 și 3000-3999',
      '100-199 și 2000-2999',
      '300-399 și 1000-1999',
      '1-99 și 1300-1999',
      '400-499 și 1500-1999',
      '600-699 și 2500-2999',
    ],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice',
    text: 'Stabiliți dacă afirmația următoare este adevărată sau falsă:\nUn server stateful DHCPv6 oferă atât o adresă IPv6 pentru host, cât și adresa default gateway-ului, în mod automat.',
    options: ['True', 'False'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care este comanda corectă pentru a configura banner-ul "ACADNET-2025" pe un router cisco?\n(Alegeți 2 raspunsuri)',
    options: [
      'banner set "ACADNET-2025"',
      'set banner ACADNET-2025',
      'banner motd *ACADNET-2025',
      'banner display ACADNET-2025',
      'banner motd $ACADNET-2025$',
      'banner motd #ACADNET-2025#',
    ],
    correctIndices: [4, 5],
  },
  {
    type: 'open-ended',
    text: 'Ce distanță administrativă are protocolul de rutare internal BGP?(Atenție! Scrieți doar valoarea numerică.)',
    acceptedAnswers: ['200'],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Folosind SLAAC, care sunt metodele prin care un host poate genera restul identificatorului de interfață pe 64 de biţi (ID)? (Alegeţi 2 variante)',
    options: [
      'Utilizând un server DHCP pentru a obține ID-ul interfeței',
      'Generare aleatoare',
      'Folosind adresa IP a routerului',
      'Prin configurare manuală',
      'EUI-64',
      'Utilizând adresa IP a unui alt dispozitiv din rețea',
    ],
    correctIndices: [1, 4],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre comenzile menţionate mai jos ajută la verificarea configurării unui EtherChannel? (Alegeţi două variante)',
    options: [
      'show interfaces portchannel',
      'show interface brief',
      'show configuration etherchannel',
      'show etherchannel port-channel',
      'show summary etherchannel',
      'show etherchannel summary',
    ],
    correctIndices: [3, 5],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Pe ce principii de funcționare este bazat modelul Cisco Borderless Network? (Selectați trei opțiuni corecte)',
    options: ['Modularitate', 'Gestionarea dinamică a lățimii de bandă', 'Structură ierarhică', 'Gestionarea costului pachetelor', 'Segmentare a rețelei', 'Reziliență'],
    correctIndices: [0, 2, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Ce câmp din cadrul header-ului Transmission Control Protocol (TCP) indică faptul că datele au fost primite și specifică, totodată, următorul octet așteptat de la sursă.',
    options: ['Acknowledgment Number', 'Header Length', 'Window size', 'Control bits', 'Checksum', 'Sequence Number'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Care este denumirea mesajului OSPF de tip 3?',
    options: ['Hello', 'Link-Static Update', 'Link-State Acknowledgment', 'Database Description', 'Link-State Update', 'Link-State Request'],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'Care este metoda corectă de calcul al unei măști wildcard?',
    options: [
      'Se calculează media octeților măștii de subrețea.',
      'Toți biții care sunt setați pe 1 devin pe 0, iar cei setați pe 0 devin pe 1.',
      'Se scad octeții adresei IP de la 255.',
      'Se adună adresa IP și masca de subrețea.',
      'Se multiplică fiecare octet al adresei IP cu masca de subrețea.',
      'Se adună octeții măștii de subrețea la 255.',
    ],
    correctIndex: 1,
  },
  {
    type: 'label-order',
    text: 'Selectați ordinea secvențelor de boot ale unui switch.',
    labels: [
      'Inițializarea flash file system-ului',
      'Încărcarea bootloader-ului',
      'Încărcarea IOS-ului',
      'Power On Self Test',
      'Inițializarea low-level a CPU-ului',
    ],
    correctOrder: [3, 1, 4, 0, 2],
  },
  {
    type: 'multiple-choice-multi',
    text: 'În ce situații este adecvat să se utilizeze cablul de tip straight-through? (Selectați două opțiuni)',
    options: ['Host <-> Host', 'Host <-> Switch', 'Switch <-> Switch', 'Switch <-> Router', 'Router <-> Router', 'Host <-> Router'],
    correctIndices: [1, 3],
  },
  {
    type: 'matching',
    text: 'Potriviți fiecare descriere cu criteriile be baza cărora se creează regulile de validare.',
    subQuestions: [
      { text: 'Reprezintă un grup de instrucțiuni SQL precompilate stocate într-o bază de date care execută o sarcină.', answer: 'Stored procedure' },
      { text: 'Reprezintă utilizarea software-ului existent pentru a construi software nou, economisind timp și costuri de dezvoltare.', answer: 'Code Reuse' },
      { text: 'Înlocuiește datele sensibile cu date fictive realiste.', answer: 'Camouflage' },
      { text: 'Este folosit pentru a organiza date într-o bază de date și pentru a ajuta la menținerea integrității datelor.', answer: 'Normalization' },
      { text: 'Reprezintă biblioteci third-party și kituri de dezvoltare software ce ajută la o dezvoltare a aplicațiilor mai rapidă și mai ieftină.', answer: 'SDKs' },
      { text: 'Ajută la ascunderea datelor originale folosind caractere sau date aleatorii.', answer: 'Obfuscation' },
    ],
    options: ['Stored procedure', 'Code Reuse', 'Camouflage', 'Normalization', 'SDKs', 'Obfuscation'],
  },
  {
    type: 'open-ended',
    text: 'Câți octeți (bytes) are câmpul "VLAN Tag" adăugat în header-ul IEEE 802.1Q? Scrieți numărul de octeți în caseta de mai jos.',
    acceptedAnswers: ['4'],
  },
  {
    type: 'multiple-choice',
    text: 'Câte tabele CAM există pe router-ul din topologia de mai jos?',
    image: 'subiecte_acad/images/judeteana_2025_1112/q33.png',
    options: ['9', '0', '3', '1', '6', '4'],
    correctIndex: 1,
  },
  {
    type: 'matching',
    text: 'Asociați fiecare serviciu de mai jos cu tipul de transport utilizat:',
    subQuestions: [
      { text: 'DHCP', answer: 'UDP' },
      { text: 'HTTPS', answer: 'TCP' },
      { text: 'FTP', answer: 'TCP' },
      { text: 'SMTP', answer: 'TCP' },
      { text: 'HTTP', answer: 'TCP' },
      { text: 'Telnet', answer: 'TCP' },
    ],
    options: ['UDP', 'TCP'],
  },
  {
    type: 'multiple-choice',
    text: 'Care este prioritatea implicită a protocolului HSRP?',
    options: ['255', '100', '150', '50', '70', '128'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care din variantele de mai jos sunt algoritmi folosiţi pentru QoS? (Alegeţi 3 variange)',
    options: ['IPsec', 'WFQ', 'LLQ', 'OSPF', 'RSA', 'FIFO'],
    correctIndices: [1, 2, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Ce reprezintă IPv6 LLA?',
    options: [
      'Este o adresă multicast care se foloseşte la nivel global.',
      'Este o adresă de rutare care se foloseşte într-o reţea locală.',
      'Este o adresă unicast care se foloseşte la nivel global.',
      'Este o adresă care se foloseşte pentru a comunica doar cu echipamente IPv6 din acelaşi segment de reţea.',
      'Niciuna dintre variante nu este corectă.',
      'Este o adresă care se foloseşte pentru a comunica cu echipamentele IPv6 din toate reţelele.',
    ],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Ce tipuri de adrese MAC sunt utilizate pentru trimiterea pachetelor în rețea? (Selectați trei răspunsuri)',
    options: ['Logice', 'Fizice', 'Multicast', 'Statice', 'Unicast', 'Broadcast'],
    correctIndices: [2, 4, 5],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Selectați porturile RSTP corespunzătoare porturilor STP blocate. (Alegeți 2 variante)',
    options: ['Designated port', 'Backup port', 'Assigned port', 'Blocked port', 'Root port', 'Alternate port'],
    correctIndices: [1, 5],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre cele de mai jos sunt blocurile de adrese private? (Alegeţi trei variante)',
    options: [
      '172.16.0.0 - 172.40.255.255',
      '20.0.0.0 - 20.255.255.255',
      '10.0.0.0 - 10.255.255.255',
      '172.16.0.0 - 172.31.255.255',
      '192.170.0.0 - 192.188.255.255',
      '192.168.0.0 - 192.168.255.255',
    ],
    correctIndices: [2, 3, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Care este comanda corectă pentru a configura pe Router1 o rută statică de la PC strict către Server?',
    image: 'subiecte_acad/images/judeteana_2025_1112/q41.png',
    options: [
      'ip route 183.45.287.2 255.255.255.255\n225.101.223.1',
      'ip route 156.203.24.4 255.255.255.255\n225.101.223.1',
      'ip route 225.101.223.2 255.255.255.0\n225.101.223.1',
      'ip route 183.45.287.2 255.255.255.0\n225.101.223.1',
      'ip route 183.45.287.2 255.255.255.0\n225.101.223.2',
      'ip route 183.45.287.2 255.255.255.255 225.101.223.2',
    ],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre următoarele sunt protocoale FHRP dezvoltate de Cisco? (Alegeți două variante)',
    options: ['OSPF', 'LACP', 'VRRP', 'HSRP', 'NAT', 'GLBP'],
    correctIndices: [3, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Care dintre tehnicile de autentificare cu chei partajate nu modifică niciodată cheia utilizată?',
    options: [
      'Wired Shared Key (WSK)',
      'Wi-Fi Protected Access 3 (WPA3)',
      'Wired Equivalent Privacy (WEP)',
      'Wi-Fi Protected Access (WPA)',
      'Wired Local Authentication (WLA)',
      'Wi-Fi Protected Access 2 (WPA2)',
    ],
    correctIndex: 2,
  },
  {
    type: 'matching',
    text: 'Între două switch-uri se configurează următoarele moduri switch-uri. Ce tip de legătură se va stabili între ele în fiecare caz?',
    subQuestions: [
      { text: '1. Trunk + Dynamic Auto =', answer: 'Trunk' },
      { text: '2. Dynamic Auto + Dynamic Auto =', answer: 'Access' },
      { text: '3. Dynamic Auto + Dynamic Desirable =', answer: 'Trunk' },
      { text: '4. Dynamic Desirable + Dynamic Desirable =', answer: 'Trunk' },
    ],
    options: ['Dynamic Desirable', 'Trunk', 'Dynamic Auto', 'Access'],
  },
  {
    type: 'multiple-choice',
    text: 'Ce reprezintă conceptul de throughput?',
    options: [
      'Toate variantele sunt corecte',
      'Viteza maximă teoretică a rețelei',
      'Numărul de biți fară erori trimiși într-o anumită perioadă de timp',
      'Nicio variantă nu este corectă',
      'Numărul efectiv de biți care circulă prin rețea',
      'Durata totală de timp pentru ca datele să ajungă de la sursă la destinație',
    ],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Ce semnifică culoarea amber (chihlimbar) a LED-ului RPS al switch-ului?',
    options: [
      'RPS standby/fault',
      'RPS conectat, dar nu este disponibil',
      'RPS on/ready',
      'RPS oferă alimentare',
      'RPS off/nu este conectat',
      'Temperatura internă a switch-ului este peste limită.',
    ],
    correctIndex: 0,
  },
  {
    type: 'label-order',
    text: 'Ordonați, de sus în jos, în funcție de CoS Value (Class of Service Value), tipul de pachete.',
    labels: [
      'Videoconferencing',
      'Best-Effort Data',
      'Call Signaling',
      'Reserved',
      'Medium-Priority Data',
      'Reserved',
      'High-Priority Data',
      'Voice bearer (voice traffic)',
    ],
    correctOrder: [1, 4, 6, 2, 0, 7, 3, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Când se returnează un mesaj ICMPv6 de tip Time Excedeed?',
    options: [
      'Când ajunge la destinație',
      'Când este nevoie de fragmentare',
      'Nicio variantă nu este corectă',
      'Când Hop Limit-ul ajunge la 0',
      'Când Time To Live-ul ajunge la 0',
      'Toate variantele sunt corecte',
    ],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care din variantele de mai jos reprezintă un tip de adresă NAT (Network Address Translation)?\n(Selectați 2 răspunsuri)',
    options: [
      'Inside global address',
      'Outside local address',
      'Inside-Outside address',
      'Network Translation address',
      'Translated address',
      'Forward global address',
    ],
    correctIndices: [0, 1],
  },
  {
    type: 'matching',
    text: 'Ordonați pașii necesari protocolului OSPF.',
    subQuestions: [
      { text: '1', answer: 'Stabilirea adiacenței cu vecinii' },
      { text: '2', answer: 'Schimbul de LSA-uri' },
      { text: '3', answer: 'Construcția bazei de date Link State' },
      { text: '4', answer: 'Aplicarea algoritmului SPF' },
      { text: '5', answer: 'Alegerea celor mai bune rute' },
    ],
    options: [
      'Construcția bazei de date Link State',
      'Blocarea porturilor',
      'Stabilirea adiacenței cu vecinii',
      'Aplicarea algoritmului SPF',
      'Alegerea celor mai bune rute',
      'Schimbul de LSA-uri',
    ],
  },
]
});
