window.ACADOBRE_ALT_QUESTIONS.push({
  id: 'judeteana_2023_2_11_12',
  topic: 'Judeteana (2) 11-12 2023',
  questions: [
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre următoarele seturi de comenzi nu realizează configurarea PAgP-ului? (Alegeți 3 răspunsuri)',
    image: 'subiecte_acad/images/judeteana_2023_2_1112/q1.png',
    options: [
      'SW1:\nint range fa0/1-4\nchannel-group 1 mode on\nSW2:\nint range fa0/1-4\nchannel-group 1 mode auto',
      'SW1:\nint range fa0/1-4\nchannel-group 1 mode active\nSW2:\nint range fa0/1-4\nchannel-group 1 mode active',
      'SW1:\nint range fa0/1-4\nchannel-group 1 mode desirable\nSW2:\nint range fa0/1-4\nchannel-group 1 mode auto',
      'SW1:\nint range fa0/1-4\nchannel-group 1 mode on\nSW2:\nint range fa0/1-4\nchannel-group 1 mode desirable',
      'SW1:\nint range fa0/1-4\nchannel-group 1 mode desirable\nSW2:\nint range fa0/1-4\nchannel-group 1 mode desirable',
      'SW1:\nint range fa0/1-4\nchannel-group 1 mode auto\nSW2:\nint range fa0/1-4\nchannel-group 1 mode desirable',
    ],
    correctIndices: [0, 1, 3],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Ce putem deduce din următoarea imagine ?',
    image: 'subiecte_acad/images/judeteana_2023_2_1112/q2.png',
    options: [
      'Toate porturile sunt pe default',
      'LACP are channel-group 3',
      'Port-channel 2 este up',
      'Comenzile se realizează pe switch de Layer 3',
      'Port-channel 3 este în folosință',
      'Numărul maxim de adrese MAC permise pe interfața FastEthernet0/3 este 50',
    ],
    correctIndices: [1, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Ce Wildcard Mask are următorul IP: 101.111.11.2/15?',
    options: ['0.0.127.255', '0.1.255.255', '0.3.255.255', '0.0.0.3', '0.0.255.255', '0.7.255.255'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care din următoarele reguli permit accesul tuturor IP-urilor din rețea? (Alegeți 2 răspunsuri)',
    options: [
      'access-list 10 permit 0.0.0.0 255.255.255.255',
      'access-list 10 permit 132.128.1.1 0.0.0.0',
      'access-list 11 permit 192.148.11.11 0.0.0.255',
      'access-list 10 permit 20.20.16.20 0.0.15.255',
      'access-list 11 permit any',
      'access-list 11 permit host 111.124.23.1',
    ],
    correctIndices: [0, 4],
  },
  {
    type: 'multiple-choice',
    text: 'În imaginea de mai jos este prezentată tabela de rutare a unui ruter. Către care next-hop va fi trimis un pachet de date cu adresa IP destinație 200.20.14.22?',
    image: 'subiecte_acad/images/judeteana_2023_2_1112/q5.png',
    options: ['172.168.0.2', '101.107.0.1', '168.172.0.2', '182.192.0.2', 'Nu există next-hop', '192.168.0.2'],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Ce putem spune în cazul configurației de mai jos despre securitatea switch-ului atunci când este incalcată? (Alegeți 3 răspunsuri)',
    image: 'subiecte_acad/images/judeteana_2023_2_1112/q6.png',
    options: [
      'Nu forwardează traficul',
      'Forwardează traficul',
      'Crește counterul de încălcări',
      'Închide portul',
      'Afisează un mesaj de eroare',
      'Trimite mesaje de log',
    ],
    correctIndices: [0, 2, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Un utilizator încearcă să transmită un mesaj de la stația PC2 către PC6, însă acest mesaj nu ajunge la destinație. Care ar putea fi cauza acestei probleme?',
    image: 'subiecte_acad/images/judeteana_2023_2_1112/q7.png',
    options: [
      'Vlan-urile nu sunt create corect pe SW1',
      'Portul Se0/1/1 pe R2 se află în modul shutdown',
      'Router-on-a-Stick este configurat greșit pe R0',
      'Portul Se0/2/0 pe R0 este în modul shutdown',
      'SW2 are modurile pe port configurate greșit',
      'Rutele statice nu sunt configurate corect pe R0',
    ],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'Un utilizator încearcă să transmită un mesaj de la stația PC1 la PC4, însă acest mesaj nu ajunge la destinație. Care ar putea fi cauza acestei probleme?',
    image: 'subiecte_acad/images/judeteana_2023_2_1112/q8.png',
    options: [
      'SW1 nu este configurat corect',
      'SW3 nu este configurat corect',
      'SW2 nu este configurat corect',
      'R0 are portul Se0/2/0 shutdown',
      'R1 are portul Se0/2/0 shutdown',
      'R0 nu are rutele statice configurate corect',
    ],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Un utilizator încearcă să transmită un mesaj de la stația PC2 la PC1. Ce putem să spunem despre transmiterea pachetului?',
    image: 'subiecte_acad/images/judeteana_2023_2_1112/q9.png',
    options: [
      'SW3 nu are porturile configurate în modul corespunzător',
      'Router-on-a-Stick nu este configurat corect pe R0',
      'Nu se poate realiza deoarece R0 nu are rutele statice configurate corect',
      'SW1 nu este configurat corect',
      'Nu se poate realiza deoarece ruta statică configurata pe R0 are next-hop portul Se0/2/0 de pe router R1',
      'Se realizează cu succes',
    ],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'În cazul topologiei următoare se poate realiza transmiterea un mesaj de la PC0 la PC6. Dacă oprim toate porturile Ruterului R1, se mai poate transmite un mesaj de la PC0 la PC6 ?',
    image: 'subiecte_acad/images/judeteana_2023_2_1112/q10.png',
    options: [
      'Nu, deoarece rutele statice de pe R4 au ca next-hop portul oprit de pe R1',
      'Nu, deoarece rutele statice de pe R0 au ca next-hop portul oprit de pe R1',
      'Nu, deoarece ruta R3-R1-R2 nu se mai poate realiza',
      'Nu, deoarece rutele statice de pe R2 au ca next-hop portul oprit de pe R1',
      'Nu, deoarece rutele statice de pe R3 au ca next-hop portul oprit de pe R1',
      'Da, deoarece nu influențează cu nimic',
    ],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'Conform comenzii următoare ne dăm seama că:',
    image: 'subiecte_acad/images/judeteana_2023_2_1112/q11.png',
    options: [
      'Pe Fa0/5-8 avem PAgP',
      'Portul Fa0/6 este oprit',
      'Pe Fa0/1-5 avem PAgP',
      'Portul Fa0/2 și Fa0/3 sunt oprite',
      'Pe Fa0/4-8 avem LAcP',
      'Pe Fa0/1-3 avem LAcP',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Un utilizator încearcă să transmită un mesaj de la PC9 la PC4, însă acest mesaj nu ajunge la destinație. Care ar putea fi cauza acestei probleme?\nSpațiul de adrese care trebuie subnetat este: 174.140.0.0/16.\nVLAN 10 - PR001 - 100H\nVLAN 20 - PR208 - 70H\nVLAN 30 - EG202 - 64H\nVLAN 40 - ED011 - 64H\nVLAN 50 - PR703 - 64H\nVLAN 60 - EG405 - 64H\nVLAN 70 - EG102 - 44H\nVLAN 80 - EC105 - 30H\nR0-R1 - 4H (primul IP din rețea este pentru R0 și al doilea pentru R1)\nR1-R4 - 4H (primul IP din rețea este pentru R1 și al doilea pentru R4)\nR1-R2 - 4H (primul IP din rețea este pentru R1 și al doilea pentru R2)\nR1-R5 - 4H (primul IP din rețea este pentru R1 și al doilea pentru R5)',
    image: 'subiecte_acad/images/judeteana_2023_2_1112/q12.png',
    options: [
      'R1 nu cunoaște unde e rețeaua 174.140.1.128',
      'R0 nu cunoaște unde e rețeaua 174.140.1.128',
      'SW5 nu are configurat vlan-ul 50',
      'SW3 nu configurat vlan-ul 10',
      'R2 nu cunoaște unde e rețeaua 174.140.1.128',
      'SW6 nu are porturile configurate în modul corect',
    ],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Un utilizator încearcă să transmită un mesaj de la PC8 la PC12, însă acest mesaj nu ajunge la destinație. Care ar putea fi cauza acestei probleme?',
    image: 'subiecte_acad/images/judeteana_2023_2_1112/q13.png',
    options: [
      'SW5 nu are porturile configurate în modul corect',
      'SW5 nu are configurat vlan-ul 70',
      'SW4 nu are configurat vlan-ul 70',
      'SW6 nu are porturile configurate în modul corect',
      'SW5 nu permite transmiterea de mesaje către PC9',
      'SW4 nu permite transmiterea de mesaje către PC12',
    ],
    correctIndex: 5,
  },
]
});
