window.ACADOBRE_ALT_QUESTIONS.push({
  id: 'locala_2026_11_12',
  topic: 'Locala 11-12 2026',
  questions: [
  {
    type: 'matching',
    text: 'Ordonați stările pe care le ia un router activ în procesul HSRP.',
    subQuestions: [
      { text: '1', answer: 'Initial' },
      { text: '2', answer: 'Learn' },
      { text: '3', answer: 'Listen' },
      { text: '4', answer: 'Speak' },
      { text: '5', answer: 'Standby' },
      { text: '6', answer: 'Active' },
    ],
    options: ['Active', 'Forwarding', 'Ex-Start', 'Learn', 'Listen', 'Standby', 'Speak', 'Initial', 'Blocking'],
  },
  {
    type: 'label-order',
    text: 'Care este structura unei intrări a unui tabel de rutare IPv6?',
    labels: ['[110/50]', 'O', '2026:ACAD:437::/64', 'Serial0/1/1', 'via FE80::2:C'],
    correctOrder: [1, 2, 0, 4, 3],
  },
  {
    type: 'matching',
    text: 'Asociați distanța administrativă corespunzătoare fiecărei rute:',
    subQuestions: [
      { text: 'EIGRP extern =', answer: '170' },
      { text: 'OSPF =', answer: '110' },
      { text: 'IS-IS =', answer: '115' },
      { text: 'BGP extern =', answer: '20' },
      { text: 'Rută statică =', answer: '1' },
    ],
    options: ['170', '110', '115', '20', '1'],
  },
  {
    type: 'matching',
    text: 'Cum sunt configurate flag-urile A, M, și O ale unui mesaj ICMPv6 RA, dacă router-ul răspunde cu detaliile necesare unei configurări Stateful?',
    subQuestions: [
      { text: 'A=', answer: '0' },
      { text: 'O=', answer: '1 sau 0' },
      { text: 'M=', answer: '1' },
    ],
    options: ['0', '1 sau 0', '1'],
  },
  {
    type: 'label-order',
    text: 'Ordonați pașii necesari obținerii unei adrese IP folosind un server DHCPv4.',
    labels: ['DHCP Discover', 'DHCP Offer', 'DHCP Request', 'DHCP Acknowledgment'],
    correctOrder: [0, 1, 2, 3],
  },
  {
    type: 'multiple-choice',
    text: 'Care este combinația maximă de liste de control al accesului (ACL) ce pot fi aplicate simultan pe o interfață de router dual‑stack (IPv4 și IPv6)?',
    options: [
      'O ACL inbound pentru IPv4 și două ACL-uri outbound pentru IPv6',
      'Două ACL-uri IPv4 (una inbound și una outbound) și două ACL-uri IPv6 (una inbound și una outbound)',
      'Patru ACL-uri, toate de tip IPv4',
      'Două ACL-uri IPv4 și una IPv6 (oricare direcție)',
      'O singură ACL (indiferent de tip sau direcție)',
      'O ACL inbound și una outbound, ambele pentru IPv4, fără suport IPv6',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Care este rolul principal al unui DR într-o rețea OSPF?',
    options: [
      'Are rolul de a determina următorul hop pentru tot traficul rețelei.',
      'Să configureze automat interfețele tuturor routerelor OSPF.',
      'Să reasigneze Router ID-uri pentru routerele din rețea.',
      'Are rolul unui nod central de colectare și distribuire al LSA-urilor.',
      'Să reducă dimensiunea LSDB-ului fiecărui router.',
      'Să verifice integritatea fiecărui LSA.',
    ],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice',
    text: 'Câte hosturi asignabile sunt disponibile într-o rețea cu masca /25?',
    options: ['124', '125', '256', '254', '128', '126'],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care din modurile protocolului LACP de mai jos stabilesc un canal EtherChannel. (Alegeți 2 variante)',
    options: ['Active + Passive', 'On + Pasive', 'Active + Active', 'Desirable + Desirable', 'On + Active', 'Auto + Desirable'],
    correctIndices: [0, 2],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Selectează caracteristicile modului de securitate al porturilor "restrict". (Alegeți 2 variante)',
    options: [
      'Aruncă traficul cu adrese MAC necunoscute.',
      'Trimite mesaje syslog.',
      'Este modul implicit de securitate',
      'Închide portul în cazul traficului cu adrese MAC necunoscute.',
      'Nu incrementează contorul de încălcări de securitate.',
      'Nu necesită intervenție manuală pentru recuperare',
    ],
    correctIndices: [0, 1],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre următoarele sunt considerate dispozitive de rețea intermediare ? (Alege 3 variante)',
    options: ['Firewall', 'Laptop', 'Ruter', 'Imprimanta', 'Server FTP', 'Switch'],
    correctIndices: [0, 2, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Care dintre următoarele combinații de taste poate fi folosiă în loc de comanda end?',
    options: ['Ctrl+6', 'Ctrl+Z', 'Shift+S', 'Shift+6', 'Ctrl+S', 'Shift+X'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre afirmațiile de mai jos nu sunt adevărate, având în vedere protocolul LACP (Alegeți 2 variante):',
    options: [
      'Ordinea în care sunt configurate porturile într-un EtherChannel cu LACP nu afectează funcționarea acestuia, atât timp cât parametrii esențiali sunt compatibili.',
      'Pentru a se crea un canal EtherChannel, LACP trebuie configurat la ambele capete ale canalului.',
      'Modurile pe care le pot lua porturile atunci când se configurează LACP sunt: Active și Passive însă pentru ca legătura EtherChannel să se formeze, la un capăt trebuie să avem On iar la celălalt active sau passive',
      'Protocolul LACP este un protocol proprietar CISCO și este protocolul care ajută la formarea unei legături EtherChannel, trimițând pachete LACP la fiecare 30 de secunde',
      'LACP este un protocol standardizat de IEEE, cunoscut sub numele de IEEE 802.3ad.',
      'LACP oferă redundanță – dacă un port din canal eșuează, traficul este redirecționat automat pe celelalte porturi active.',
    ],
    correctIndices: [2, 3],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Selectați care dintre variantele de adrese de mai jos fac parte din clasa de adrese corespunzătoare. (Alegeți 2 variante):',
    options: [
      '224.0.0.1 - clasa C',
      '127.0.0.1 - clasa A',
      '191.255.100.200 - clasa B',
      '172.16.0.1 - clasa C',
      '130.0.0.1 - clasa A',
      '192.0.0.1 - clasa B',
    ],
    correctIndices: [1, 2],
  },
  {
    type: 'multiple-choice',
    text: 'Care este lungimea unei adrese IPv4?',
    options: ['64 biți', '256 biți', '48 biți', '16 biți', '32 biți', '128 biți'],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Alegeți din variantele de mai jos care este formatul scurt, după ce s-au aplicat cele două reguli de compresie, pe adresa IPv6: 2025:0CAD:0000:0000:4300:0020:ABC0:0000',
    options: [
      '2025:CAD:0000::4300:20:ABC0:0000',
      '2025::0CAD:4300:20:ABC0:0',
      '2025:CAD::4300:20:ABC0:0',
      '2025:0CAD:0:0:43:20:ABC::',
      '2025:CAD::43:2:ABC::',
      '2025:0CAD::4300:0020:ABC0::',
    ],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care sunt cele două substraturi ale nivelului 2 al stivei OSI? (Alegeți 2 variante)',
    options: [
      'Media Address Control',
      'Link Access Control',
      'Media Link Control',
      'Logical Access Control',
      'Logical Link Control',
      'Media Access Control',
    ],
    correctIndices: [4, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Care este comanda ce trebuie folosită pentru a afișa doar configurarea rutelor statice IPv4?',
    options: [
      'show ip route',
      'show ip route static | section ip route',
      'show startup-config | filter static route',
      'show ip route static',
      'show running-config | section ip route',
      'show running-config | filter static route',
    ],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Care este distanța administrativă a protocolului EIGRP?',
    options: ['80', '120', '125', '130', '110', '90'],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'Ce informații stochează tabela CAM a unui switch de rețea?',
    options: [
      'Asociere între IP și VLAN',
      'Asociere între adrese MAC și IP-uri',
      'Informații despre rețele cunoscute de switch',
      'Asociere între adrese MAC și portul switch-ului',
      'Asociere între adresa rețelei și portul rutarului',
      'Asocierea între portului de next-hop și rețeaua locală',
    ],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice',
    text: 'O companie are nevoie să conecteze birourile din București, Pitești și Constanța pentru a transmite date și a accesa fișiere comune. Având în vedere că aceste orașe sunt situate la distanțe considerabile unul de celălalt, ce tip de rețea ar fi cel mai potrivit?',
    options: [
      'Rețea personală (PAN)',
      'Rețea wireless locală (WLAN)',
      'Rețea locală (LAN)',
      'Rețea metropolitană (MAN)',
      'Rețea de Arie de Stocare (SAN)',
      'Rețea extinsă (WAN)',
    ],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'Ce tip de atac implică un actor malițios care se interpune într-o conversație între două părți pentru a intercepta sau modifica datele fără ca acestea să știe?',
    options: ['SQL Injection', 'Brute Force', 'Denial-of-Service', 'Social Engineering', 'Man-in-the-Middle', 'Phishing'],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Care este numărul de domenii de Coliziune și de Broadcast din topolgia de mai jos?',
    image: 'subiecte_acad/images/locala_2026_1112/q23.png',
    options: [
      'Coliziune: 17\nBroadcast: 4',
      'Coliziune: 17\nBroadcast: 3',
      'Coliziune: 11\nBroadcast: 4',
      'Coliziune: 11\nBroadcast: 3',
      'Coliziune: 11\nBroadcast: 7',
      'Coliziune: 17\nBroadcast: 7',
    ],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice',
    text: 'Cum îmbunătățește algoritmul 3DES securitatea față de DES?',
    options: [
      'Folosește exclusiv chei de 1536 biți.',
      'Este de 3 ori mai rapid decât DES, fiind mai eficient pentru blocuri mari de date.',
      'Repetă procesul DES de trei ori.',
      'Utilizează criptografie asimetrică pentru autentificare.',
      'Folosește o cheie de criptare de 3 ori mai mare.',
      'Folosește exclusiv chei de 512 biți.',
    ],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'O companie dorește să implementeze o schemă de adresare IP folosind metoda de subnetare VLSM, alocând eficient spațiul de adrese IP în funcție de necesarul fiecărui departament. Care este setul corect de măști de subrețea pentru fiecare departament? (Fără rețea si broadcast)\nIT: 1002 hosturi\nHR:422 hosturi\nMarketing:512 hosturi\nNotă: Default Gateway-ul nu este inclus în numărul de hosturi.',
    options: [
      'IT: 255.255.248.0\nHR: 255.255.254.0\nMARKETING: 255.255.254.0',
      'IT: 255.255.252.0\nHR: 255.255.254.0\nMARKETING: 255.255.252.0',
      'IT: 255.255.252.0\nHR: 255.255.254.0\nMarketing: 255.255.254.0',
      'IT: 255.255.252.0\nHR: 255.255.255.0\nMarketing: 255.255.254.0',
      'IT: 255.255.248.0\nHR: 255.255.254.0\nMARKETING: 255.255.254.0',
      'IT: 255.255.252.0\nHR: 255.255.255.128\nMARKETING: 255.255.254.0',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Ce lungimi de chei suportă algoritmul AES? (Alegeți 3 variante)',
    options: ['64 biți', '192 biți', '1028 biți', '128 biți', '32 biți', '256 biți'],
    correctIndices: [1, 3, 5],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre afirmațiile de mai jos sunt adevărate despre nivelul legătură de date? (Alegeți 2 variante).',
    options: [
      'Permite straturilor superioare să aibă acces la mediu.',
      'Efectuează multiplexarea și demultiplexarea datelor.',
      'Primește date de la stratul rețea, le încapsulează în cadre și le transmite prin mediu către destinație.',
      'Nivelul legătură de date este un nivel prezent în stiva TCP/IP.',
      'Stabilește conexiunea între două echipamente atunci când datele se trimit de la un echipament la altul.',
      'Nu efectuează detectarea erorilor.',
    ],
    correctIndices: [0, 2],
  },
  {
    type: 'multiple-choice',
    text: 'Ce adresă de broadcast va avea subrețeaua "A" după realizarea unei subnetări optime (VLSM) a spațiului de adrese 179.24.39.11/23, având următoarele specificații:\nsubrețeaua "A" - 31 adrese\nsubrețeaua "B" - 40 adrese\nsubrețeaua "C" - 64 adrese\nsubrețeaua "D" - 2 adrese\nAdresele default gateway-urilor din fiecare rețea sunt incluse în numărul de adrese.',
    options: [
      '179.24.39.255/26',
      '179.24.38.31/27',
      '179.24.38.63/26',
      '179.24.39.31/27',
      '179.24.39.63/26',
      '179.24.38.255/26',
    ],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre următoarele aplicații și servicii utilizează în mod tipic UDP? (Alegeți 3 variante)',
    options: ['SMTP', 'VoIP', 'DHCP', 'FTP', 'DNS', 'HTTP'],
    correctIndices: [1, 2, 4],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre afirmațiile de mai jos nu sunt adevărate având în vedere protocolul TCP? (Alegeți 2 variante.)',
    options: [
      'TCP nu garantează că toate datele trimise ajung la destinație.',
      'TCP împarte datele în segmente.',
      'TCP include câmpurile care asigură trimiterea datelor.',
      'TCP este considerat un protocol de transport care stabilește o conexiune între destinatar și expeditor.',
      'TCP-ul oferă fiabilitate, însă nu poate controla fluxul datelor.',
    ],
    correctIndices: [0, 4],
  },
  {
    type: 'multiple-choice',
    text: 'Ştiind că tabelele ARP ale dispozitivelor sunt complet populate şi că toate dispozitivele din ambele reţele au configurate drept default gateway interfeţele router-ului aflat între ele, iar tabelele CAM ale switch-urilor sunt goale, ce va conţine tabela CAM a switch-urilor SW3 şi SW5 după trimiterea următoarelor pachete în aceeaşi ordine ca cea menţionată, fără a include şi pachetele de răspuns:\nPC1->PC5, PC6->PC1, PC0->PC1?',
    image: 'subiecte_acad/images/locala_2026_1112/q31.png',
    options: [
      'SW3: MAC_PC1-FA0/1, MAC_Router0_Gig/0/0/0-FA0/3, MAC_PC0-FA0/1\nSW5: MAC_Router0_Gig/0/0/1-FA0/1',
      'SW3: MAC_PC1-FA0/1, MAC_Router0_Gig/0/0/0-FA0/3\nSW5: MAC_Router0_Gig/0/0/1-FA0/1',
      'SW3: MAC_PC1-FA0/1, MAC_PC6-FA0/3, MAC_PC0-FA0/1\nSW5: MAC_Router0_Gig/0/0/1-FA0/1',
      'SW3: MAC_PC1-FA0/1, MAC_Router0_Gig/0/0/0-FA0/3\nSW5: MAC_PC1-FA0/1',
      'SW3: MAC_PC1-FA0/1, MAC_PC6-FA0/3, MAC_PC0-FA0/1\nSW5: MAC_PC1-FA0/1',
      'SW3: MAC_PC1-FA0/1, MAC_PC6-FA0/3\nSW5: MAC_PC1-FA0/1',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Care din variantele de mai jos reprezintă prima adresă asignabilă din spațiul de adrese 203.47.153.13/21?',
    options: [
      '203.47.153.13/21',
      '203.47.152.1/21',
      '203.47.153.14/21',
      '203.47.153.0/21',
      '203.47.152.0/21',
      '203.47.153.1/21',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Care dintre următoarele tipuri de înregistrări dintr-un server DNS reprezintă un end device cu o adresa IPv4?',
    options: ['A', 'AAAA', 'NS', 'Quad-A', 'MX', 'Six-A'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Care din variantele de mai jos reprezintă codul "Destination Unreachable" pentru "Port unreachable" în cadrul protocolului ICMPv6?',
    options: ['5', '2', '1', '4', '3', '0'],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice',
    text: 'Ce dispozitiv este necesar pentru a permite comunicarea între două VLAN-uri diferite?',
    options: ['Router sau switch Layer 3', 'Access Point', 'Repeater', 'Switch Layer 2', 'Hub', 'Bridge'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Dacă PC1 trimite un packet către PC3, cum v-a arăta tabela CAM a Switch-ului 3, știind că înaintea trimiterii pachetului tabela CAM a Switch-ului 3 era goală?',
    image: 'subiecte_acad/images/locala_2026_1112/q36.png',
    options: [
      'PC1 - Fa0/3',
      'PC3 - Fa0/3',
      'PC1 - Fa0/1\nPC3 - Fa0/1',
      'PC1 - Fa0/1',
      'PC1 - Fa0/1\nPC3 - Fa0/3',
      'PC2 - Fa0/1',
    ],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice',
    text: 'Care set de timere este implicit pentru HSRP (hello/hold)? (Alegeți 1 variantă)',
    options: ['10s / 3s', '3s / 10s', '5s / 15s', '3s / 4s', '2s / 8s', '1s / 4s'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Care este rolul Area 0 într-o rețea OSPF multi-area?',
    options: [
      'Este zona în care nu se trimit update-uri OSPF',
      'Este zona în care sunt configurate doar hosturile',
      'Este o zonă opțională folosită doar pentru testare',
      'Este zona backbone care interconectează toate celelalte arii',
      'Este o zonă rezervată exclusiv pentru rute externe',
      'Este zona folosită doar pentru rețele wireless',
    ],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care din variantele de mai jos reprezintă o valoare corectă, pe care componenta Bridge Priority, din BID-ul unui switch, o poate avea în cadrul procesului de STP? (Alegeți 2 variante)',
    options: ['36864', '64536', '2048', '1', '20480', '1024'],
    correctIndices: [0, 4],
  },
  {
    type: 'multiple-choice',
    text: 'Switch-urile dintr-o rețea au următoarele adrese MAC și Bridge Priority, conform tabelului. Ce switch va fi ales drept Root Bridge în procesul protocolului STP?',
    image: 'subiecte_acad/images/locala_2026_1112/q40.png',
    options: ['SW_F', 'SW_A', 'SW_D', 'SW_E', 'SW_H', 'SW_B'],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Ce înseamnă prescurtarea VPN?',
    options: [
      'Virtual Private Network',
      'Virtual Public Network',
      'Variable Packet Network',
      'Verified Private Node',
      'Visual Private Network',
      'Very Protected Network',
    ],
    correctIndex: 0,
  },
  {
    type: 'open-ended',
    text: 'Știind că porturile valabile pentru PAT sunt 1024-65535, câte sesiuni poate susține o singură adresă IP publică?\nRăspunsul trebuie introdus drept un număr în bază 10.',
    acceptedAnswers: ['64512'],
  },
  {
    type: 'open-ended',
    text: 'Câte rețele pot fi adresate în clasa A?\nRăspunsul trebuie să fie introdus drept un număr.',
    acceptedAnswers: ['128'],
  },
  {
    type: 'open-ended',
    text: 'Care este numărul domeniilor de broadcast al rețelei de mai sus?\nRăspunsul trebuie să fie introdus drept un număr.',
    image: 'subiecte_acad/images/locala_2026_1112/q44.png',
    acceptedAnswers: ['1'],
  },
  {
    type: 'multiple-choice',
    text: 'Alegeți dacă afirmația următoare este adevărată sau falsă:\nUn socket este format doar din adresa IP a serverului și portul serviciului (ex: 192.168.1.7:80).',
    options: ['True', 'False'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Selectați valoarea de adevăr a următoarei afirmații:\nEtherChannel-ul oferă redundanță și nu necesită recalcularea STP atunci când una dintre legăturile din agregare este întreruptă.',
    options: ['True', 'False'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Alegeți dacă afirmația următoare este adevărată sau falsă:\nComanda no vlan <vlan-id> în modul de configurare globală șterge VLAN-ul specificat doar temporar și nu îl elimină din fișierul vlan.dat al switch-ului.',
    options: ['True', 'False'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Stabiliți dacă următoarea afirmație este adevărată sau falsă: În cazul unei modificări într-o rețea ce folosește rute statice, acestea nu se actualizează automat.',
    options: ['True', 'False'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Stabiliți dacă următoarea afirmație este adevărată sau falsă: O adresă anycast este o adresă IPv6 folosită pentru a trimite un singur pachet IPv6 către mai multe destinații simultan.',
    options: ['True', 'False'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Alegeți dacă afirmația următoare este adevărată sau falsă:\nLayer-ul fizic din modelul OSI transformă cadrele primite de la layer-ul de legătură de date în semnale electrice, optice sau unde radio care pot fi transmise prin mediul fizic',
    options: ['True', 'False'],
    correctIndex: 0,
  },
]
});
