window.ACADOBRE_ALT_QUESTIONS.push({
  id: 'locala_2025_9_10',
    topic: 'Locala 9-10 2025',
    questions: [
    {
    type: 'multiple-choice',
    text: 'Care dintre următoarele câmpuri din header-ul UDP nu este prezent în header-ul TCP?',
    options: ['Urgent', 'Length', 'Destination Port', 'Source Port', 'Header Length', 'Checksum'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Având spațiul de adrese 203.175.43.18/24 și următoarele cerințe pentru departamente:\nAdmin - 30 hosturi\nContabilitate - 7 hosturi\nHR - 10 hosturi\nIT - 50 hosturi\nDeterminați adresa de rețea și adresa de broadcast pentru departamentul HR, folosind subnetare optimă.',
    options: [
      'Adresa de rețea: 203.175.1.18/29\nAdresa de broadcast: 203.175.1.33/29',
      'Adresa de rețea: 203.175.43.96/28\nAdresa de broadcast: 203.175.43.111/28',
      'Adresa de rețea: 203.175.43.160/28\nAdresa de broadcast: 203.175.43.175/28',
      'Adresa de rețea: 203.175.43.96/29\nAdresa de broadcast: 203.175.43.103/29',
      'Adresa de rețea: 203.175.43.178/28\nAdresa de broadcast: 203.175.43.193/28',
      'Adresa de rețea: 203.175.43.114/29\nAdresa de broadcast: 203.175.43.121/29',
      'Adresa de rețea: 203.175.43.176/28\nAdresa de broadcast: 203.175.43.191/28',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Ce port destinaţie UDP se utilizează pentru mesajele DHCPv6 trimise de la server la client?',
    options: ['548', '54', '547', '68', '546', '53'],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care din variantele de mai jos reprezintă tipuri de rute statice? (Alegeţi 3 variante)',
    options: ['Ruta Flotantă', 'Ruta Administrativă', 'Metric-Based Route', 'Ruta Sumarizată', 'Ruta Default', 'Interface-Based Route'],
    correctIndices: [0, 3, 4],
  },
  {
    type: 'multiple-choice',
    text: 'Pe ce VLAN este trimis traficul fără etichetă (untagged traffic)?',
    options: ['VLAN-ul de management', 'VLAN-ul 1', 'VLAN-ul de date', 'Voice VLAN-ul', 'VLAN-ul nativ', 'VLAN-ul default'],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Selectează doua caracteristici ale metodei de Inter-VLAN routing Router-on-a-Stick. (Alegeți 2 variante)',
    options: [
      'Crește lățimea de bandă a rețelei',
      'Nu izolează traficul dintre VLAN-uri',
      'Ușor de adăugat VLAN-uri noi fără a schimba topologia',
      'Optimizat pentru rețele cu trafic foarte mare',
      'Scade costuri prin reducerea numarului de porturi necesare',
      'Conferă redundanță',
    ],
    correctIndices: [2, 4],
  },
  {
    type: 'multiple-choice',
    text: 'Stabiliți valoarea de adevăr a următoarei afirmații:\nProtocolul ICMP descoperă erorile care pot exista în comunicarea dintre 2 echipamente?',
    options: ['Fals', 'Adevărat'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Care este portul standard utilizat de serviciul Telnet?',
    options: ['23', '22', '80', '44', '60', '24', '20'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre următoarele protocoale sunt proprietare CISCO? (Alegeți 3 variante)',
    options: ['VRRP', 'HSRP', 'CDP', 'Niciun răspuns nu e corect.', 'LACP', 'PAgP'],
    correctIndices: [1, 2, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Ce comenzi trebuie introduse in CLI pentru a asigna o adresa ip pe portul Gig0/0/1 si pentru a porni interfata?',
    options: [
      'Router>en\nRouter# configure terminal\nRouter(config)# interface Gig0/0/1\nRouter(config-if)# ip address 192.168.0.1 255.255.255.0\nRouter(config-if)# no shutdown',
      'Router# configure terminal\nRouter(config)# ip address 192.168.0.1 255.255.255.0 Gig0/0/1\nRouter(config)# status up',
      'Router>en\nRouter# interface Gig0/0/1\nRouter(config-if)# ip address 192.168.0.1 255.255.255.0\nRouter(config-if)# status up',
      'Router>en\nRouter# configure terminal\nRouter(config)# interface Gig0/0/1\nRouter(config-if)# ip address 192.168.0.1 256.256.256.0\nRouter(config-if)# status up',
      'Router# interface Gig0/0/1\nRouter(config-if)# ip address 192.168.0.1 255.255.255.0\nRouter(config-if)# interface start',
      'Router>en\nRouter# interface Gig0/0/1\nRouter(config-if)# ip address 192.168.0.1 255.255.255.0\nRouter(config-if)# interface start',
    ],
    correctIndex: 0,
  },
  {
    type: 'matching',
    text: 'Ordonati etapele intializarii unui switch.',
    subQuestions: [
      { text: '1.', answer: 'POST' },
      { text: '2.', answer: 'Boot Loader' },
      { text: '3.', answer: 'Initializare CPU' },
      { text: '4.', answer: 'Flash' },
      { text: '5.', answer: 'IOS' },
    ],
    options: ['Flash', 'Activarea Wi-Fi', 'IOS', 'POST', 'Initializare CPU', 'Boot Loader', 'Instalarea Driverelor'],
  },
  {
    type: 'multiple-choice',
    text: 'Ce indică caracterul "*" în tabela de rutare a unui router?',
    options: [
      'Indică faptul că acea rută este obținută dinamic, folosind protocolul EIGRP.',
      'Indică faptul că acea rută este obținută dinamică, folosind protocolul OSPF.',
      'Indică faptul că acea rută este obținută static.',
      'Indică faptul că acea rută este obținută de la un server dedicat.',
      'Indică faptul că acea rută este candidat pentru o rută default.',
      'Niciun răspuns nu este corect.',
    ],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Ce tipuri de rute pot fi configurate pe un router? (Selectați trei opțiuni corecte)',
    options: [
      'Rute de tip BGP (Border Gateway Protocol)',
      'Rute dinamice',
      'Rute statice',
      'Rute de tip OSPF (Open Shortest Path First)',
      'Rute de tip RARP (Reverse Address Resolution Protocol)',
      'Rute direct conectate',
    ],
    correctIndices: [1, 2, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Cât este distanţa adiministrativă pentru o rută statică?',
    options: ['20', '115', '1', '5', '110', '0'],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'Când se returnează un mesaj ICMPv4 de tip Time Excedeed?',
    options: [
      'Toate variantele sunt corecte',
      'Când Hop Limit-ul ajunge la 0',
      'Când este nevoie de fragmentare',
      'Nicio variantă nu este corectă',
      'Când ajunge la destinație',
      'Când Time To Live-ul ajunge la 0',
    ],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'Care este adresa de rețea și cea de broadcast pentru adresa 213.129.255.19/18?',
    options: [
      'Adresa de rețea: 213.129.0.192\nAdresa de broadcast: 213.129.255.253',
      'Adresa de rețea: 223.139.192.0\nAdresa de broadcast: 213.129.255.0',
      'Adresa de rețea: 213.129.255.0\nAdresa de broadcast: 213.129.255.244',
      'Adresa de rețea: 213.129.192.0\nAdresa de broadcast: 213.129.0.255',
      'Adresa de rețea: 213.129.192.0\nAdresa de broadcast: 213.129.255.255',
      'Adresa de rețea: 213.129.192.0\nAdresa de broadcast: 213.131.255.255',
    ],
    correctIndex: 4,
  },
  {
    type: 'open-ended',
    text: 'Cum se numește procesul prin care un PDU trece de la un nivel la altul?\nAtenție! Toate literele din acest proces sunt mici!',
    acceptedAnswers: ['encapsulare'],
  },
  {
    type: 'multiple-choice',
    text: 'Stabiliți valoarea de adevăr a următoarei afirmații:\nFiecare port al unui switch delimitează un domeniu de coliziune separat.',
    options: ['Fals', 'Adevărat'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Selectează câte câmpuri și câți octeți are un header TCP. (Alegeți 2 variante)',
    options: ['20 octeți', '15 octeți', '20 câmpuri', '10 octeți', '15 câmpuri', '10 câmpuri'],
    correctIndices: [0, 5],
  },
  {
    type: 'matching',
    text: 'Asociați nivelurile modelului OSI cu nivelurile echivalente din stiva TCP/IP.',
    subQuestions: [
      { text: 'Prezentare', answer: 'Aplicație (TCP/IP)' },
      { text: 'Rețea', answer: 'Internet (TCP/IP)' },
      { text: 'Sesiune', answer: 'Aplicație (TCP/IP)' },
      { text: 'Legătură de date', answer: 'Acces la rețea (TCP/IP)' },
      { text: 'Fizic', answer: 'Acces la rețea (TCP/IP)' },
      { text: 'Aplicație', answer: 'Aplicație (TCP/IP)' },
      { text: 'Transport', answer: 'Transport (TCP/IP)' },
    ],
    options: ['Aplicație (TCP/IP)', 'Transport (TCP/IP)', 'Internet (TCP/IP)', 'Acces la rețea (TCP/IP)'],
  },
  {
    type: 'open-ended',
    text: 'Câte domenii de brodcast sunt în această topologie?',
    image: 'subiecte_acad/images/locala_2025_910/q21.png',
    acceptedAnswers: ['7'],
  },
  {
    type: 'open-ended',
    text: 'Câte domenii de broadcast sunt în topologia de mai jos?',
    image: 'subiecte_acad/images/locala_2025_910/q22.png',
    acceptedAnswers: ['4'],
  },
  {
    type: 'image-order',
    text: 'Ordonați de la stânga la dreapta culorile firelor pentru standardul T568A de cablare.',
    images: [
      { src: 'subiecte_acad/images/locala_2025_910/RJ_45/wire_white_green.png',  label: 'Alb-Verde' },
      { src: 'subiecte_acad/images/locala_2025_910/RJ_45/RJ_45/wire_green.png',        label: 'Verde' },
      { src: 'subiecte_acad/images/locala_2025_910/RJ_45/RJ_45/wire_white_orange.png', label: 'Alb-Porto' },
      { src: 'subiecte_acad/images/locala_2025_910/RJ_45/RJ_45/wire_blue.png',         label: 'Albastru' },
      { src: 'subiecte_acad/images/locala_2025_910/RJ_45/RJ_45/wire_white_blue.png',   label: 'Alb-Albastru' },
      { src: 'subiecte_acad/images/locala_2025_910/RJ_45/RJ_45/wire_orange.png',       label: 'Porto' },
      { src: 'subiecte_acad/images/locala_2025_910/RJ_45/RJ_45/wire_white_brown.png',  label: 'Alb-Maro' },
      { src: 'subiecte_acad/images/locala_2025_910/RJ_45/RJ_45/wire_brown.png',        label: 'Maro' },
    ],
    correctOrder: [0, 1, 2, 3, 4, 5, 6, 7],
  },
  {
    type: 'multiple-choice',
    text: 'Care sunt paşii pentru a configura şi salva pe interfaţa Fa0/1 de pe switch-ul 0 modul full duplex, cu viteza de 200/Mbps?',
    options: [
      'S1# configure terminal\nS1(config)# interface Fa0/1\nS1(config-if)# duplex full\nS1(config-if)# speed 200\nS1(config-if)# end',
      'S1# configure terminal\nS1(config)# interface Fa0/1\nS1(config-if)# full duplex\nS1(config-if)# speed 200\nS1(config-if)# end\nS1# copy running-config startup-config',
      'S1# configure terminal\nS1(config)# interface Fa0/1\nS1(config-if)# full duplex\nS1(config-if)# speed 200/Mbps\nS1(config-if)# end\nS1# copy running-config startup-config',
      'S1# configure terminal\nS1(config)# interface Fa0/1\nS1(config-if)# duplex full\nS1(config-if)# speed 200\nS1(config-if)# end\nS1# copy running-config startup-config',
      'S1# configure terminal\nS1(config)# interface Fa0/1\nS1(config-if)# duplex full\nS1(config-if)# speed 200/Mbps\nS1(config-if)# end\nS1# copy running-config startup-config',
      'S1# configure terminal\nS1(config)# interface Fa0/1\nS1(config-if)# full duplex\nS1(config-if)# speed 200\nS1(config-if)# end',
    ],
    correctIndex: 3,
  },
  {
    type: 'matching',
    text: 'Ce tip de protocol de transport folosește fiecare protocol?',
    subQuestions: [
      { text: 'FTP',  answer: 'TCP' },
      { text: 'DHCP', answer: 'UDP' },
      { text: 'SSH',  answer: 'TCP' },
      { text: 'POP3', answer: 'TCP' },
    ],
    options: ['TCP', 'UDP'],
  },
  {
    type: 'multiple-choice',
    text: 'Care este diferența dintre protocoalele de Email POP3 și SMTP:',
    options: [
      'Niciunul dintre răspunsuri',
      'SMTP salvează automat după citire mail-urile primite de destinatar, iar POP3 le șterge imediat după citire.',
      'SMTP este un protocol de mail de la nivelul aplicație, în timp ce POP3 este un protocol la nivelul fizic.',
      'Nu există diferențe între cele două protocoale.',
      'SMTP trimite emailul de pe dispozitivul expeditorului la emailul destinatarului, iar POP3 preia și organizează e-mailurile de la serverul de e-mail al destinatarului la computerul destinatarului.',
      'SMTP este un protocol de comunicație la nivelul legătură de date, în timp ce POP3 este un protocol de mail de la nivelul aplicație',
    ],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Care este intervalul de timp la care PAgP-ul trimite pachete de verificare a configurării?',
    options: ['10', '15', '25', '20', 'Niciun răspuns nu este corect.', '30'],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'Care este numărul maxim de porturi ce pot face parte dintr-un EtherChannel?',
    options: ['16', '4', '8', '2', '20', '18'],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'Bob doreşte să se conecteze printr-un mod sigur la un switch, dar acesta nu are acces fizic la el. Cum va realiza conectarea?',
    options: ['Nu are cum să se conecteze de la distanţă.', 'Prin TCP', 'Prin SSH', 'Prin portul de consolă', 'Prin portul auxiliar', 'Prin Telnet'],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre protocoalele din lista de mai jos ajută la configurarea unei legături de EtherChannel? (Alegeţi 2 variante)',
    options: ['PAgP', 'CLAP', 'AgpP', 'LACP', 'Pggp', 'LLDP'],
    correctIndices: [0, 3],
  },
  {
    type: 'label-order',
    text: 'Care sunt pașii procesului de boot al unui router? (ordonează de sus în jos)',
    labels: ['Power-On Self-Test', 'Încarcarea Bootstrap-ului', 'Încarcarea imaginii IOS', 'Încarcarea fișierului de configurare'],
    correctOrder: [0, 1, 2, 3],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Selectați sistemele de operare dezvoltate de Cisco. (Selectați 3 răspunsuri)',
    options: ['Junos OS', 'iOS', 'IOS XR', 'IOS XE', 'NX-OS', 'OpenWrt'],
    correctIndices: [2, 3, 4],
  },
  {
    type: 'matching',
    text: 'În ce ordine trebuie introduse comenzile în CLI-ul unui switch de nivel 3 pentru a crea un SVI pentru VLAN? (Ordonați de sus în jos).',
    subQuestions: [
      { text: '1.', answer: 'vlan 10' },
      { text: '2.', answer: 'interface vlan 10' },
      { text: '3.', answer: 'ip add 192.168.1.1 255.255.255.0' },
      { text: '4.', answer: 'no shut' },
    ],
    options: ['switchport mode access', 'vlan 10', 'ip add 192.168.1.1 255.255.255.0', 'ip routing', 'no shut', 'interface vlan 10'],
  },
  {
    type: 'matching',
    text: 'Asociati fiecare nivel al stivei OSI cu unitatea de date corespunzatoare.',
    subQuestions: [
      { text: 'Legatura de date', answer: 'Cadre' },
      { text: 'Aplicatie',       answer: 'Date' },
      { text: 'Sesiune',         answer: 'Date' },
      { text: 'Retea',           answer: 'Pachete' },
      { text: 'Transport',       answer: 'Segmente' },
      { text: 'Prezentare',      answer: 'Date' },
      { text: 'Fizic',           answer: 'Biti' },
    ],
    options: ['Cadre', 'Date', 'Pachete', 'Segmente', 'Biti'],
  },
  {
    type: 'multiple-choice',
    text: 'Care este reprezentarea în biţi a adresei IPv4 115.249.52.78?',
    options: [
      '01110011 11111001 01110100 01001110',
      '01110011 11111001 00110100 01001110',
      '01110011 11100001 00110100 01001110',
      '01110011 11011001 00110100 0100111',
      '01110011 01111001 00110100 01001110',
      '01110011 11111001 00110100 01001010',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Ce echipament este folosit pentru filtrarea mail-urilor cu conținut malițios?',
    options: ['Switch', 'End-device', 'Niciun răspuns nu este corect.', 'Firewall', 'ESA', 'Router'],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Ce reprezintă câmpul "type" dintr-un VLAN tag?',
    options: [
      'O valoare de 4 octeți numită VLAN ID',
      'O valoare de 2 octeți numită VLAN ID',
      'O valoare de 4 octeți numită tag protocol ID',
      'O valoare de 2 octeți numită tag protocol ID',
      'O valoare de un octet numită tag protocol ID',
      'O valoare de un octet numită VLAN ID',
    ],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice',
    text: 'Care este culoarea LED-ului Port Speed atunci când portul funcționează la o viteză de 100 Mbps?',
    options: ['Blinking green', 'Blinking amber', 'Rosu', 'Portocaliu', 'Verde', 'Amber (chihlimbar)'],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Ce fel de conectori se folosesc pentru a cabla un cablu UTP, astfel încât acesta să funcţioneze corect?',
    options: ['tip N', 'RJ-45', 'RJ-11', 'tip F', 'RJ-25', 'BNC'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Care este range-ul de porturi "Well-Known"?',
    options: ['1 - 1024', '1025 - 49152', '49152 - 65535', '0 - 1023', '1024 - 49151', '49153 - 65536'],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice',
    text: 'Care este portul standard utilizat de protocolul POP3?',
    options: ['110', '67', '142', '69', '25', '143'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care din variantele de mai jos reprezintă un tip de VLAN? (Selectați 3 răspunsuri)',
    options: ['Broadcast VLAN', 'Management VLAN', 'Data VLAN', 'Default VLAN', 'Multicast VLAN', 'Admin VLAN'],
    correctIndices: [1, 2, 3],
  },
  {
    type: 'multiple-choice',
    text: 'Stabiliți valoarea de adevăr a urmatoarei afirmații:\nRutarea statică este mai sigură decât rutarea dinamică.',
    options: ['Fals', 'Adevărat'],
    correctIndex: 1,
  },
  {
    type: 'matching',
    text: 'Asociați fiecare caracteristică cu tipul de VLAN corespunzător:',
    subQuestions: [
      { text: 'Mai multe VLAN-uri pot circula pe legătură',      answer: 'Trunk' },
      { text: 'Folosită pentru conexiuni între echipamente de rețea', answer: 'Trunk' },
      { text: 'Legătură folosită între switch și un nod final',  answer: 'Acces' },
      { text: 'Un singur VLAN poate circula pe legătură',        answer: 'Acces' },
    ],
    options: ['Trunk', 'Acces'],
  },
  {
    type: 'multiple-choice',
    text: 'Ce mască de rețea corespunde prefixului /29?',
    options: ['255.255.255.240', '255.255.255.248', '255.255.255.224', '255.255.225.240', '255.255.225.248', '255.255.255.242'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Se dă următoarea topologie. Dacă PC2 trimite un ping către PC1, câte intrari în tabela CAM va avea Switch0?',
    image: 'subiecte_acad/images/locala_2025_910/q46.png',
    options: ['2', '1', '3', '5', '0', '4'],
    correctIndex: 0,
  },
  {
    type: 'matching',
    text: 'Alegeți pentru fiecare rețea din stânga IP-ul corespunzător astfel încât, la trimiterea unui pachet, acesta să ajungă în rețeaua asociată. (Atenție! Folosiți regula Best Path Equals Longest Match)',
    subQuestions: [
      { text: '192.168.0.0/16',    answer: '192.168.1.245' },
      { text: '192.168.0.0/24',    answer: '192.168.0.3' },
      { text: '192.168.0.0/25',    answer: '192.168.0.126' },
      { text: '192.168.0.128/27',  answer: '192.168.0.131' },
    ],
    options: ['192.168.1.245', '192.169.25.1', '192.168.0.126', '193.168.0.1', '192.168.0.3', '192.168.0.131'],
  },
  {
    type: 'multiple-choice',
    text: 'Care va fi rezultatul în urma apăsării tastei ENTER?',
    image: 'subiecte_acad/images/locala_2025_910/q48.png',
    options: [
      'Se configurează, pe router, o parolă criptată pentru a intra în modul user EXEC.',
      'Se configurează, pe router, o parolă criptată pentru a intra în modul privileged EXEC.',
      'Se configurează, pe router, o parolă necriptată pentru a intra în modul user EXEC.',
      'Se configurează, pe router, o parolă criptată pentru a intra în modul de configurare al liniei de consolă.',
      'Se afișează un text de eroare.',
      'Se configurează, pe router, o parolă necriptată pentru a intra în modul privileged EXEC.',
    ],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Fie urmatoarea adresă IPv4 destinaţie: 105.26.72.0/24. Considerând următorele rute:\n1. 105.26.72.0/12\n2. 104.26.72.0/19\n3. 103.26.72.0/18\n4. 104.26.72.0/24\n5. 103.26.72.0/25\n6. 105.26.72.0/18\nCare va fi ruta pe care o va alege ruter-ul pentru a trimite un pachet la destinaţia dorită?',
    options: ['Ruta 4', 'Ruta 6', 'Ruta 1', 'Ruta 2', 'Ruta 3', 'Ruta 5'],
    correctIndex: 1,
  },
]
});