window.ACADOBRE_ALT_QUESTIONS.push({
  id: 'locala_2025_11_12',
  topic: 'Locala 11-12 2025',
  questions: [
  {
    type: 'multiple-choice',
    text: 'Pe cați biți se află router-id-ul?',
    options: ['32', '48', '2', 'Niciun răspuns nu este corect.', '64', '128'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Ce comandă trebuie utilizată pentru a afișa un mesaj banner la conectarea la un echipament?',
    options: ['banner motd', 'configure banner', 'set banner', 'show banner', 'display banner', 'banner message'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Care dintre următoarele comenzi este utilizată pentru a salva configurațiile?',
    options: ['upload config', 'copy running-config startup-config', 'backup', 'save config', 'store configuration', 'save'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Dacă PC0 trimite un ping către PC5, câte intrari în tabela CAM va avea Router0?',
    image: 'subiecte_acad/images/locala_2025_1112/q4.png',
    options: ['0', '2', '5', '4', '3', '1'],
    correctIndex: 0,
  },
  {
    type: 'open-ended',
    text: 'Câte domenii de coliziune sunt în topologia de mai jos?',
    image: 'subiecte_acad/images/locala_2025_1112/q5.png',
    acceptedAnswers: ['10'],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care din variantele de mai jos reprezintă o metodă de rutare inter-VLAN?\n(Selectați două răspunsuri)',
    options: [
      'Border Inter-VLAN routing',
      'Dynamic VLAN routing',
      'Access-Path routing',
      'Legacy Inter-VLAN routing',
      'Trunk-Access routing',
      'Router-on-a-Stick',
    ],
    correctIndices: [3, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Care este semnificaţia acronimului VPN?',
    options: [
      'Virtual Protocol Network',
      'Virtual Private Network',
      'Very Private Network',
      'Virtual Private Node',
      'Virtual Protected Network',
      'Virtual Public Network',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'De la ce vine acronimul HSRP?',
    options: [
      'Host Standby Routing Protocol',
      'High Security Routing Process',
      'Hybrid System Routing Protocol',
      'High-Speed Routing Protocol',
      'Host Security and Redundancy Protocol',
      'Hot Standby Router Protocol',
    ],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'La ce interval de timp, exprimat în secunde, sunt trimise în mod implicit mesajele CDP?',
    options: ['30', '180', '60', '50', '120', '10'],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'Alegeți varianta în care toate combinațiile de perechi de porturi formează un EtherChannel.',
    options: [
      'On - On\nDesirable - Desirable\nActive - Active',
      'On - Desirable\nDesirable - Passive\nAuto - On',
      'On - On\nDesirable - Desirable\nAuto - On',
      'On - On\nDesirable - On\nAuto - Active',
      'Passive - On\nDesirable - Active\nAuto - Auto',
      'Passive - Auto\nOn - Active\nOn - On',
    ],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Câți octeți are antetul protocolului UDP?',
    options: ['10', '8', '64', '16', '28', '20'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Ce mască de rețea corespunde prefixului /19?',
    options: ['255.255.224.0', '255.255.255.192', '255.255.192.0', '255.192.0.0', '255.255.128.0', '255.255.240.0'],
    correctIndex: 0,
  },
  {
    type: 'open-ended',
    text: 'Care este numărul portului pentru Simple Mail Transfer Protocol (SMTP)?',
    acceptedAnswers: ['25'],
  },
  {
    type: 'multiple-choice',
    text: 'Câți biți sunt utilizați pentru stocarea BridgeID-ului într-un frame STP?',
    options: ['12', '64', 'Niciun răspuns nu este corect', '8', '4', '48'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Care este comanda corectă pentru a genera o cheie RSA pe un dispozitiv Cisco?',
    options: [
      'generate key rsa',
      'generate rsa-key',
      'rsa key fetch',
      'crypto key generate rsa',
      'key generate rsa',
      'generate crypto key rsa',
    ],
    correctIndex: 3,
  },
  {
    type: 'matching',
    text: 'Potriviți fiecare element al tabelei de rutare din imagine cu denumirea sa corectă.',
    image: 'subiecte_acad/images/locala_2025_1112/q16.png',
    subQuestions: [
      { text: '00:16:22',          answer: 'Timpul trecut de la învățarea rutei' },
      { text: '192.168.3.2',       answer: 'Next hop' },
      { text: '110',               answer: 'Distanța administrativă' },
      { text: 'O',                 answer: 'Sursa rutei' },
      { text: '192.168.10.0/24',   answer: 'Adresa destinației' },
      { text: 'Gig0/0',            answer: 'Interfața de ieșire' },
      { text: '50',                answer: 'Metrica' },
    ],
    options: ['Timpul trecut de la învățarea rutei', 'Next hop', 'Distanța administrativă', 'Sursa rutei', 'Adresa destinației', 'Interfața de ieșire', 'Metrica'],
  },
  {
    type: 'matching',
    text: 'Ordonaţi în ordinea corectă paşii pentru realizarea algoritmului STP:',
    subQuestions: [
      { text: '1.', answer: 'Alegerea root bridge-ului' },
      { text: '2.', answer: 'Alegerea root porturilor' },
      { text: '3.', answer: 'Alegerea designated porturilor' },
      { text: '4.', answer: 'Alegerea blocked porturilor' },
    ],
    options: ['Alegerea root porturilor', 'Alegerea designated porturilor', 'Setarea protocolului SSH pe porturi', 'Crearea regulilor de firewall', 'Alegerea root bridge-ului', 'Alegerea blocked porturilor'],
  },
  {
    type: 'multiple-choice',
    text: 'Care este numărul minim de rute statice vor fi configurate în următoarea topologie astfel încât să existe conectivitate end-to-end? (Atenție! Nu se iau în considerare rutele default!)',
    image: 'subiecte_acad/images/locala_2025_1112/q18.png',
    options: ['12', '4', '2', '1', '3', '46'],
    correctIndex: 0,
  },
  {
    type: 'open-ended',
    text: 'Câte subrețele cu masca /30 egale putem formă dintr-o clasa de ip-uri cu masca /24?',
    acceptedAnswers: ['64'],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care sunt metodele de forwarding folosite de un switch?(Alegeți 2 variante)',
    options: [
      'Mono-alternate-forward',
      'Fragmented transmission',
      'Cut-and-forward',
      'Compress-and-forward',
      'Store-and-forward',
      'Cut-through',
    ],
    correctIndices: [4, 5],
  },
  {
    type: 'matching',
    text: 'Potriviți numele fiecărui LED ale unui switch Catalyst cu funcționalitățile sale.',
    subQuestions: [
      { text: 'STAT', answer: 'Arată starea de funcționare a portului' },
      { text: 'SYST', answer: 'Arată dacă switch-ul este alimentat și nu are nicio eroare' },
      { text: 'RPS',  answer: 'Arată dacă sistemul de alimetare funcționează în mod redundant sau nu' },
    ],
    options: ['Arată starea de funcționare a portului', 'Arată dacă switch-ul este alimentat și nu are nicio eroare', 'Arată dacă sistemul de alimetare funcționează în mod redundant sau nu'],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre următoarele hostname-uri nu sunt valide (Alegeți 2 variante):',
    options: ['1R', 'Router 1', 'Router!?7', 'Router~1', 'R1', 'Router_1'],
    correctIndices: [1, 2],
  },
  {
    type: 'multiple-choice',
    text: 'Care este denumirea alternativă pentru Aria 0 în cadrul protocolului OSPF?',
    options: ['Aria de control', 'Zona de distribuție', 'Zona de colaps', 'Backbone area', 'Zona secundară', 'Aria de securitate'],
    correctIndex: 3,
  },
  {
    type: 'matching',
    text: 'Orodonaţi etapele protocolului DHCPv4 de sus in jos:',
    subQuestions: [
      { text: '1.', answer: 'DHCP Discover' },
      { text: '2.', answer: 'DHCP Offer' },
      { text: '3.', answer: 'DHCP Request' },
      { text: '4.', answer: 'DHCP Acknowledgment' },
    ],
    options: ['DHCP Search', 'DHCP Receive', 'DHCP Request', 'DHCP Send', 'DHCP Acknowledgment', 'DHCP Offer', 'DHCP Discover', 'DHCP Claim'],
  },
  {
    type: 'multiple-choice',
    text: 'Se dă următoarea topologie. Câte domenii de coliziune sunt în topologia de mai jos?',
    image: 'subiecte_acad/images/locala_2025_1112/q25.png',
    options: ['4', '6', '9', '8', '5', '7'],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'Care este comanda pentru a configura o interfață a switch-ului, astfel încât aceasta să accepte un număr maxim de 50 de adrese MAC pe un port.',
    options: [
      'enable port-security maximum 50',
      'enable switchport-security mac 50',
      'switchport maximum mac 50',
      'switchport port-security maximum 50',
      'switchport maximum mac allowed 50',
      'switchport port-security maximum mac 50',
    ],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Ce elemente constituie un protocol de rutare? (Selectați 3 variante)',
    options: ['Masca de subrețea', 'Mesaje de rutare', 'Adresă IP', 'Interfață de rețea', 'Algoritm', 'Structuri de date'],
    correctIndices: [1, 4, 5],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care sunt rutere direct conectate ale router-ului 1, conform topologiei de mai jos? (Alegeţi 3 variante)',
    image: 'subiecte_acad/images/locala_2025_1112/q28.png',
    options: ['105.26.30.0/24', '105.26.20.0/24', '105.26.50.0/24', '105.26.60.0/24', '105.26.10.0/24', '105.26.40.0/24'],
    correctIndices: [2, 3, 5],
  },
  {
    type: 'multiple-choice',
    text: 'La ce se refera aplicația VoIP?',
    options: [
      'Un standard pentru transferul de date între calculatoare prin cablu USB.',
      'Distribuie conținutul media pe platforme de streaming.',
      'Un protocol de securitate utilizat pentru protejarea comunicațiilor prin e-mail.',
      'O tehnologie care permite efectuarea apelurilor telefonice prin internet.',
      'Un tip de procesor grafic utilizat în calculatoare.',
      'Un sistem de operare pentru dispozitive mobile.',
    ],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice',
    text: 'Ce echipament specializat este utilizat pentru filtrarea traficului web și blocarea site-urilor cu conținut malițios?',
    options: ['WSA', 'Firewall', 'Switch', 'End-device', 'Router', 'Niciun răspuns nu este corect.'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Ce reprezintă termenul de vulnerabilitate?',
    options: [
      'Orice valoare pentru organizație, incluzând oameni, echipamente, resurse și date.',
      'Un pericol potențial pentru datele sau funcționalitățile rețelei unei companii.',
      'Un mecanism care profită de o vulnerabilitate.',
      'Probabilitatea ca o amenințare să exploateze vulnerabilitatea unei rețele, cu scopul de a afecta negativ o organizație.',
      'O contra-măsura care reduce probabilitatea sau severitatea unei amenințări sau riscuri potențiale.',
      'O slăbiciune a unui sistem sau a designului acestuia, care ar putea fi exploatată de către un atacator.',
    ],
    correctIndex: 5,
  },
  {
    type: 'open-ended',
    text: 'Fie adresa de subreţea: 205.26.87.25/24, care este numărul maxim de adrese IPv4 asignabile în această subreţea?',
    acceptedAnswers: ['254'],
  },
  {
    type: 'multiple-choice',
    text: 'Care este numărul maxim de VLAN-uri, inclusiv cele rezervate, ce pot exista pe un switch Cisco Catalyst?',
    options: ['4096', '65535', '1023', '4094', '1024', '2048'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Care este prioriatea default pentru protocolul HSRP?',
    options: ['110', '900', '120', '130', 'Niciun răspuns nu este corect.', '80'],
    correctIndex: 4,
  },
  {
    type: 'matching',
    text: 'Asociaţi următoarele definiţii cu câmpurile semnificative din antetul IPv4:',
    subQuestions: [
      { text: 'Reprezintă durata de viaţă a pachetului.',                                                          answer: 'TTL' },
      { text: 'Conţine o valoare binară de 4 biţi, prin care se identifică existenţa unei adrese IPv4.',           answer: 'Version' },
      { text: 'Ajută la verificarea integrităţii header-ului IPv4.',                                               answer: 'Checksum' },
      { text: 'Câmp de 8 biţi pentru a determina prioritatea unui pachet.',                                        answer: 'DiffServ' },
    ],
    options: ['TTL', 'Version', 'Checksum', 'DiffServ'],
  },
  {
    type: 'label-order',
    text: 'Așezați în ordine, de sus în jos, pașii Spanning Tree Algorithm.',
    labels: ['Alegerea unui root port pe fiecare bridge (cu excepția root bridge)', 'Alegerea root bridge', 'Alegerea designated ports', 'Alegerea și închiderea blocked ports'],
    correctOrder: [1, 0, 2, 3],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre stările unui port de switch poate actualiza tabela de asocieri MAC?',
    options: ['Forwarding', 'Listening', 'Toate variantele sunt corecte', 'Blocking', 'Disabled', 'Learning'],
    correctIndices: [0, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Care este termenul care determină dacă un packet este expirat în IPv6 ?',
    options: ['traceroute', 'ip', 'ping', 'TTL', 'Niciun raspuns', 'hop limit'],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'Stabiliți valoarea de adevăr a urmatoarei afirmații:\nProtocolul HTTP aparține nivelului Transport al stivei OSI.',
    options: ['Adevărat', 'Fals'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Care este prefixul unei adrese link-local IPv6?',
    options: ['FE80::/10', 'FF80::/16', '2001::/16', 'FDFF::/7', 'FC00::/7', '2000::/8'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'În cadrul cărui standard IEEE este specificată prima versiune a protocolului STP (Spanning Tree Protocol)?',
    options: ['802.3', '802.1d', '802.1q', '802.1x', '802.15', '802.11'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Stabiliți valoarea de adevăr a următoarei afirmații:\nProtocolul CDP poate fi considerat un risc de securitate.',
    options: ['Fals', 'Adevărat'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Care este intervalul implicit, în secunde, la care sunt trimise pachetele PAgP?',
    options: ['200', '60', '50', '10', '120', '30'],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'Ana işi doreşte să trimită un pachet către toate dispozitivele din reţea. Care va fi adresa MAC destinaţie?',
    options: [
      'FF:FF:FF:FF:XX:XX',
      '00:1A:2B:3C:4D:5E',
      'FF:FF:FF:FF:FF:FF',
      '01:00:5E:03:08:2E',
      '00:1B:63:84:45:E6',
      'FF:FF:FF:FF:FF:XX',
    ],
    correctIndex: 2,
  },
  {
    type: 'matching',
    text: 'Potriviți nivelele stivei TCP/IP cu protocoalele aferente fiecărui nivel.',
    subQuestions: [
      { text: 'Internet Layer',        answer: 'NAT' },
      { text: 'Network Access Layer',  answer: 'ARP' },
      { text: 'Transport Layer',       answer: 'UDP' },
      { text: 'Application Layer',     answer: 'DHCPv4' },
    ],
    options: ['NAT', 'ARP', 'UDP', 'DHCPv4'],
  },
  {
    type: 'multiple-choice',
    text: 'Câți octeți are antetul protocolului TCP?',
    options: ['16', '20', '24', '10', '8', '32'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Conform topologiei de mai jos, care switch va fi ales root bridge?',
    image: 'subiecte_acad/images/locala_2025_1112/q47.png',
    options: ['Switch3', 'Switch1', 'Switch0', 'Switch6', 'Switch4', 'Switch2', 'Switch5'],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'Ce protocol de la nivelul transport folosește protocolul DNS (Domain name system).',
    options: ['Depinde din ce punct de vedere', 'TCP', 'UDP', 'TCP pentru pachete mai mari de 512 bytes, UDP pentru mai mici', 'UDP pentru pachete mai mari de 512 bytes, TCP pentru mai mici'],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre cele din lista de mai jos reprezintă modurile de negociere pentru PAgP? (Alegeţi 2 variante)',
    options: ['Active', 'Desirable', 'On', 'Auto', 'Pasive', 'Start'],
    correctIndices: [1, 3],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre stările unui port de switch nu pot trimite mesaje BPDU?',
    options: ['Learning', 'Forwarding', 'Listening', 'Blocking', 'Disabled', 'Toate variantele sunt corecte'],
    correctIndices: [3, 4],
  },
]
});
