window.ACADOBRE_ALT_QUESTIONS.push({
  id: 'locala_2026_9_10',
  topic: 'Locală 9-10 2026',
  questions: [
  {
    type: 'matching',
    text: 'Selectează notația corespunzătoare pentru fiecare tip de rută statică.',
    subQuestions: [
      { text: 'Static Route',   answer: 'S' },
      { text: 'Default Route',  answer: 'S*' },
      { text: 'Host Route',     answer: 'S/L' },
      { text: 'Floating Route', answer: 'S' },
      { text: 'Connected Route', answer: 'C' },
      { text: 'Local Route',    answer: 'L' },
    ],
    options: ['S*', 'L', 'S', 'R', 'B', 'C', 'O', 'S/L'],
  },
  {
    type: 'matching',
    text: 'Ordonează pașii procesului DHCPv6.',
    subQuestions: [
      { text: '1.', answer: 'Host-ul trimite un mesaj RS' },
      { text: '2.', answer: 'Router-ul raspunde cu un mesaj RA' },
      { text: '3.', answer: 'Host-ul trimite un mesaj DHCPv6 SOLICIT' },
      { text: '4.', answer: 'Serverul DHCPv6 trimite un mesaj ADVERTISE' },
      { text: '5.', answer: 'Host-ul răspunde serverului DHCPv6' },
      { text: '6.', answer: 'Serverul DHCPv6 trimite un mesaj REPLY' },
    ],
    options: ['Host-ul trimite un mesaj DHCPv6 SOLICIT', 'Host-ul răspunde serverului DHCPv6', 'Serverul DHCPv6 trimite un mesaj ADVERTISE', 'Serverul DHCPv6 trimite un mesaj REPLY', 'Router-ul trimite cu un mesaj RA', 'Host-ul trimite un mesaj RS'],
  },
  {
    type: 'label-order',
    text: 'Care este structura unei intrări a unui tabel de rutare IPv4?',
    labels: ['192.168.1.0/24', 'via 1.0.0.1,', '0:12:1,', 'Serial0/1/1,', '[110/50],', 'O'],
    correctOrder: [5, 0, 4, 1, 2, 3],
  },
  {
    type: 'open-ended',
    text: 'Spațiul 192.168.125.54/22 este subnetat în două subspații de câte 23 de host-uri fiecare folosind metoda VLSM. Completează următoarea comandă pentru a stabili o ruta sumarizată către cele două subspații.',
    acceptedAnswers: ['192.168.124.0 255.255.255.192'],
    hint: 'Porțiunea introdusă trebuie sa aibă formatul "x.x.x.x y.y.y.y" (fără ghilimele).\nip route ___ gig0/0/1".',
  },
  {
    type: 'multiple-choice',
    text: 'Care dintre următoarele este o mască de rețea validă?',
    options: ['255.0.255.0', '256.255.255.0', '255.255.255.1', '255.255.0.255', '254.255.255.0', '255.255.255.0'],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'Care câmp din antetul IPv4 este actualizat și recalculat la fiecare trecere printr-un router?',
    options: ['Checksum', 'Protocol', 'TTL', 'Optiuni', 'Flaguri', 'Versiune'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Ce metodă de generare a Interface ID este bazată pe adresa MAC a dispozitivului în IPv6?',
    options: ['DHCPv6 Stateful', 'Manual', 'MAC-Based Hashing', 'DHCPv6 Stateless', 'EUI-64', 'SLAAC'],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Care este valoarea distanței administrative (AD) pentru protocolul de rutare OSPF?',
    options: ['100', '1', '130', '0', '120', '110'],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care este rolul mesajelor DHCPv4 DHCPREQUEST? (Alegeți 2 variante)',
    options: [
      'Confirmă că adresa IP este liberă.',
      'Transformă comunicarea DHCP în unicast.',
      'Acceptă oferta de la serverul ales și respinge ofertele altor servere.',
      'În cazul reînnoirii, trimite cererea către serverul care a oferit inițial adresa.',
      'Resetează timerul de expirare al lease-ului fără implicarea serverului DHCP.',
      'Solicită tuturor serverelor DHCPv4 o nouă, indiferent de statusul lease-ului.',
    ],
    correctIndices: [2, 3],
  },
  {
    type: 'multiple-choice',
    text: 'Care este rolul mesajelor DHCPv4 DHCPREQUEST trimis drept broadcast?',
    options: [
      'Are rolul de a permite tuturor clienților să vadă configurația IP.',
      'Are rolul de a respinge toate ofertele primite.',
      'Are rolul de a căuta în rețea un server DHCP.',
      'Are rolul de a permite unui server secundar să preia lease-ul.',
      'Are rolul de a reseta timerul de expirare al lease-ului fără implicarea serverului DHCP.',
      'Are rolul de a informa toate serverele de oferta acceptată.',
    ],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Ce rol are procesul Three-Way Handshake în stabilirea conexiunii TCP? (alegeți 2 variante)',
    options: [
      'Transmite parolele de autentificare ale clientului',
      'Sincronizează ambele părți pentru o comunicare fiabilă',
      'În timpul handshake-ului se transmite și prima parte din datele aplicației',
      'Are rolul principal de a închide conexiunea în siguranță',
      'Inițiază conexiunea tcp, fără a transfera date de aplicație',
      'Se folosește doar în rețele wireless',
    ],
    correctIndices: [1, 4],
  },
  {
    type: 'multiple-choice-multi',
    text: 'De ce NU este recomandat să folosești VLAN 1 în rețelele moderne? (Alegeți 2 variante)',
    options: [
      'VLAN 1 este VLAN-ul implicit utilizat de protocoalele de control, ceea ce îl face o țintă comună pentru atacuri',
      'VLAN 1 are latență mai mare decât alte VLAN-uri',
      'VLAN 1 nu poate fi modificat sau redenumit în niciun switch Cisco',
      'VLAN 1 este utilizat pentru toate porturile în mod implicit, ceea ce poate crea conflicte și probleme de securitate',
      'VLAN 1 nu permite alocarea unei adrese IP de management',
      'VLAN 1 nu este compatibil cu porturile trunk',
    ],
    correctIndices: [0, 3],
  },
  {
    type: 'multiple-choice',
    text: 'Care este funcția comenzii "standby 10 preempt"?',
    options: [
      'Setează prioritatea routerului drept 10.',
      'Permite unui router să devină activ dacă are prioritatea mai mare timp de 10 secunde.',
      'Permite unui router din grupul 10 să devină activ dacă are prioritatea mai mare.',
      'Asteapta 10 secunde pentru a devenii noul router activ.',
      'Setează router-ul drept al 10-lea candidat pentru funcția de router activ.',
      'Forțează întotdeauna routerul sa devină activ.',
    ],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'În ce tip de memorie este stocată adresa MAC reținută prin metoda "sticky", în urma salvării configurărilor?',
    options: ['CAM', 'ROM', 'RAM', 'Memoria Flash', 'DRAM', 'NVRAM'],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Selectați din variantele de mai jos adresele IPv4 care se află în rețeaua 125.78.40.0/21. (Alegeți 2 variante):',
    options: ['125.78.44.10', '125.78.63.192', '125.78.92.12', '125.78.73.0', '125.78.200.2', '125.78.42.0'],
    correctIndices: [0, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Care este cea mai mică mască de subrețea care permite alocarea a exact 32 de adrese IP utilizabile pentru hosturi?',
    options: ['255.255.255.0', '255.255.255.240', '255.255.255.224', '255.255.255.128', '255.255.255.192', '255.255.255.248'],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care sunt două organizații principale care au rolul de a menține și standardiza procesele și protocoalele online? (Alegeți două opțiuni)',
    options: ['FDA', 'IAFNS', 'IKE', 'ICANN', 'IAB', 'FSIS'],
    correctIndices: [3, 4],
  },
  {
    type: 'multiple-choice',
    text: 'Care este lungimea unei adrese IPv6?',
    options: ['1024 biți', '128 biți', '256 biți', '96 biți', '64 biți', '32 biți'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Care este scopul principal al multiplexării în rețelele de date?',
    options: [
      'Să gestioneze adresele IP ale dispozitivelor din rețea',
      'Să monitorizeze traficul de rețea pentru detectarea erorilor',
      'Să controleze accesul fizic la mediul de transmisie',
      'Să asigure criptarea datelor pentru securitate sporită',
      'Să permită trimiterea simultană a mai multor fluxuri de date prin același canal de comunicație',
      'Să împartă un flux mare de date în pachete mai mici pentru a putea fi transmise separat',
    ],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Care este masca de rețea în notație CIDR pentru un subnet de 200 de hosturi din rețeaua 172.20.0.0/22?',
    options: ['/22', '/24', '/23', '0.0.0.255', '255.255.252.0', '0.0.15.255'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Ce comandă se folosește pentru a vizualiza configurația stocată în NVRAM pe un echipament Cisco?',
    options: ['show memory', 'show running-config', 'show flash', 'show interfaces', 'show startup-config', 'show version'],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Cum trebuie configurate subinterfețele unui router într-un scenariu Router-on-a-Stick pentru a asigura conectivitatea între VLAN-uri? (Alegeți 3 variante)',
    options: [
      'Subinterfețele trebuie configurate cu adrese MAC diferite manual',
      'Se configurează intefața fizică în mod trunk folosind switchport mode trunk',
      'Interfața fizică a routerului trebuie să fie activată (no shutdown)',
      'Este necesar să se atribuie un IP diferit fiecărui port de pe switch',
      'Fiecare subinterfață trebuie să aibă un IP în aceeași rețea cu VLAN-ul asociat',
      'Se folosește comanda encapsulation dot1Q [ID_VLAN] pe fiecare subinterfață',
    ],
    correctIndices: [2, 4, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Câți biți ai unei adrese MAC pot fi modificați de către vendor?',
    options: ['24 biți', '16 biți', '20 biți', '32 biți', '18 biți', '8 biți'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Conform standardului IEEE 802.1D, care este costul STP pentru un link cu viteza de 1 Gbps?',
    options: ['4', '2', '1', '100', '19', '20000'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Care din variantele de mai jos este reprezentarea corectă a adresei IPv6 acad:2026:0000:ff00:0000:0000:00e9:1000 după ce au fost aplicate toate regulile de comprimare?',
    options: [
      'acad:2026:0:ff00::e9:1000',
      'acad:2026::ff::e9:1',
      'acad:2026::ff00::e9:1000',
      '2026:acad::ff::e9::1',
      'acad:2026:0000:ff::00e9:1',
      '2026:acad:0:ff::e900:1',
    ],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Care este principalul rol al aplicației Wireshark în contextul administrării și analizei rețelelor de calculatoare?',
    options: [
      'Pentru criptarea traficului de rețea între două stații',
      'Pentru monitorizarea consumului de energie al echipamentelor de rețea',
      'Pentru capturarea și analiza pachetelor de rețea în timp real',
      'Pentru testarea vitezei conexiunii la internet',
      'Pentru detectarea automată a virușilor și malware-ului din rețea',
      'Pentru configurarea adreselor IP pe routere și switch-uri',
    ],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care din variantele de mai jos reprezintă o adresă privată IPv4? (Alegeți 3 variante)',
    options: [
      '172.32.10.1/12',
      '172.21.101.65/12',
      '11.0.0.3/8',
      '192.16.0.1/12',
      '10.234.45.5/8',
      '192.168.63.7/16',
    ],
    correctIndices: [1, 4, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Ce tip de cablu trebuie folosit pentru conectarea unui hub la un calculator?',
    options: ['Serial RS-232', 'USB', 'Straight-through', 'Crossover', 'Rollover', 'HDMI'],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'Câte grupuri (blocuri) sunt într-o adresă IPv6 completă?',
    options: ['4', '32', '12', '16', '6', '8'],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'Care stare este singura în care portul nu trimite și nu primește deloc BPDUs?',
    options: ['Err-disabled', 'Blocking', 'Disabled', 'Learning', 'Listening', 'Forwarding'],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'Considerând că tabelele ARP ale dispozitivelor din rețea sunt populate complet, iar tabelele CAM ale switch-urilor sunt goale, ce va conține tabela CAM a switch-urilor SW3 și SW4 după trimiterea următoarelor pachete în aceeași ordine ca cea menționată, fără a include și pachetele de răspuns:\nE→D, B→D, C→E?',
    image: 'subiecte_acad/images/locala_2026_910/q31.png',
    options: [
      'SW3: MAC_E-Fa0/1, MAC_B-Fa0/2\nSW4: MAC_E-Fa0/1, MAC_B-Fa0/1, MAC_C-Fa0/2',
      'SW3: MAC_B-Fa0/2\nSW4: MAC_E-Fa0/1, MAC_C-Fa0/2',
      'SW3: MAC_E-Fa0/1, MAC_B-Fa0/2, MAC_C-Fa0/1\nSW4: MAC_E-Fa0/1, MAC_B-Fa0/1, MAC_C-Fa0/2',
      'SW3: MAC_E-Fa0/2, MAC_B-Fa0/1, MAC_C-Fa0/2\nSW4: MAC_E-Fa0/2, MAC_B-Fa0/3, MAC_C-Fa0/1',
      'SW3: MAC_B-Fa0/1\nSW4: MAC_E-Fa0/2, MAC_C-Fa0/1',
      'SW3: MAC_E-Fa0/2, MAC_B-Fa0/1\nSW4: MAC_E-Fa0/2, MAC_B-Fa0/2, MAC_C-Fa0/1',
    ],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Care este viteza maximă teoretică ce poate fi atinsă de un Etherchannel, full-duplex, format din porturi Fast Ethernet?',
    options: ['400 MBps', '800 Mbps', '800 MBps', '1200 MBps', '400 Mbps', '1200 Mbps'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care comenzi pot fi folosite pentru a afișa tabelul cu adrese MAC al unui switch? (Alegeți 2 variante)',
    options: [
      'show mac address-table',
      'show mac-address-table',
      'show mac adress table',
      'show address-table mac',
      'show address-table-mac',
      'show mac-address table',
    ],
    correctIndices: [0, 1],
  },
  {
    type: 'multiple-choice',
    text: 'Analizând topologia de rețea prezentată, câte domenii de coliziune și câte domenii de broadcast există?',
    image: 'subiecte_acad/images/locala_2026_910/q34.png',
    options: [
      '7 domenii de coliziune, 3 domenii de broadcast',
      '8 domenii de coliziune, 1 domeniu de broadcast',
      '7 domenii de coliziune, 2 domenii de broadcast',
      '7 domenii de coliziune, 1 domeniu de broadcast',
      '12 domenii de coliziune, 2 domenii de broadcast',
      '12 domenii de coliziune, 1 domeniu de broadcast',
    ],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Ce termen descrie numărul efectiv de biți care circulă prin rețea într-un anumit interval de timp și este mai mic decât lățimea de bandă teoretică (bandwidth)?',
    options: ['Ping', 'Goodput', 'Throughput', 'Bandwidth utilization', 'Baud rate', 'Latency'],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'Ce tip de port de switch este folosit pentru a conecta un calculator într-un singur VLAN?',
    options: ['Port trunk', 'Port access', 'Port routed', 'Port mirror', 'Port loopback', 'Port aggregated'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'În ce parte a memoriei este stocat tabelul de adrese MAC al unui switch?',
    options: ['Memoria Flash', 'Memoria NVRAM', 'Memoria RAM', 'Memoria DRAM', 'Memoria ROM', 'Memoria adresabilă prin conținut'],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Selectați toți parametrii comenzii "ip route". (Alegeți 3 variante)',
    options: ['Metrică', 'Port de ingress', 'Distanța administrativă', 'Adresă de rețea IPv6', 'Adresă de rețea IPv4', 'Mască de rețea'],
    correctIndices: [2, 4, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Care este nivelul din modelul TCP/IP care prezintă datele utilizatorului, le codifică și gestionează dialogul?',
    options: ['Nivelul 2', 'Nivelul 6', 'Nivelul 3', 'Nivelul 4', 'Nivelul 5', 'Nivelul 7'],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice',
    text: 'Ce nivel al stivei OSI este responsabil pentru standardizarea formatelor de fișiere și criptarea datelor, fără a gestiona dialogurile dintre aplicații?',
    options: ['Nivelul 5', 'Nivelul 2', 'Nivelul 4', 'Nivelul 7', 'Nivelul 6', 'Nivelul 3'],
    correctIndex: 4,
  },
  {
    type: 'open-ended',
    text: 'Folosind metoda VLSM, spațiul 249.223.112.1/11 este împărțit în numărul maxim de rețele, având fiecare 57 host-uri. Care este adresa de rețea și masca a celui de-al 159-ulea subspațiu creat?',
    acceptedAnswers: ['249.192.39.128/26'],
    hint: 'Răspunsul trebuie să aibă structura următoare: "196.168.0.0/24".',
  },
  {
    type: 'multiple-choice',
    text: 'Stabiliți dacă următoarea propoziție este adevărată sau falsă:\nAtunci când o legătură EtherChannel este configurată folosind protocolul PAgP, toate legăturile fizice sunt grupate și tratate ca o singură conexiune logică. Din perspectiva STP, această agregare apare ca un singur port.',
    options: ['True', 'False'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Alegeți dacă afirmația următoare este adevărată sau falsă:\nUn server care găzduiește un site web este considerat un end device într-o rețea de calculatoare.',
    options: ['True', 'False'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Stabiliți dacă următoarea afirmație este adevărată sau falsă: Un cadru Ethernet care conține un tag IEEE 802.1Q, ce indică apartenența la VLAN-ul cu ID-ul 1, va circula etichetat pe o legătură de tip trunk, configurată default.',
    options: ['True', 'False'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Alegeți dacă afirmația următoare este adevărată sau falsă:\nIMAP descarcă o copie a mesajelor de email pe client, păstrând originalele pe server până când sunt șterse manual.',
    options: ['True', 'False'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Alegeți dacă afirmația următoare este adevărată sau falsă:\nUn asterisc (*) în rezultatul comenzii traceroute indică un pachet pierdut sau la care nu s-a primit un răspuns',
    options: ['True', 'False'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Alegeți dacă afirmația următoare este adevărată sau falsă:\nRouterele pot schimba dinamic traseul pachetelor în funcție de condiția rețelei în timp real.',
    options: ['True', 'False'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Alegeți dacă afirmația următoare este adevărată sau falsă: Full-duplex connections sunt obligatorii pentru viteze Ethernet de 1 Gbps și mai mari și contribuie semnificativ la creșterea performanței rețelelor LAN.',
    options: ['True', 'False'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Alegeți dacă afirmația următoare este adevărată sau falsă:\nUn "local host" este un dispozitiv care se află în aceeași rețea locală ca și dispozitivul sursă, având aceeași adresă de rețea.',
    options: ['True', 'False'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Alegeți dacă afirmația următoare este adevărată sau falsă:\nÎntr-o subrețea /26, adresa de broadcast are ultimii 6 biți egali cu 0.',
    options: ['True', 'False'],
    correctIndex: 1,
  },
]
});
