window.ACADOBRE_ALT_QUESTIONS.push({
  id: 'nationala_2025_11_12',
  topic: 'Naționala 11-12 2025',
  questions: [
  {
    type: 'multiple-choice',
    text: 'Care din variantele de mai jos reprezintă o tehnologie WAN care este utilizată pentru interconectarea reţelelor LAN ale unei firme?',
    options: ['ISDN', 'Frame Relay', 'Wi-Fi', 'Bluetooth', 'ATD', 'PSTN'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care sunt cele 3 criterii de conectare a unui switch la un domeniu VTP? (Alegeți 3 variante)',
    options: [
      'Parola de pe interfața virtuală',
      'Hostname-ul',
      'Versiunea de VTP pe care o are server-ul',
      'Switch-ul trebuie să fie configurat cu o adresă IP pentru a se conecta la domeniul VTP.',
      'Numele domeniului',
      'Parola domeniului',
    ],
    correctIndices: [2, 4, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Stabiliţi dacă următoarea propoziţie este adevărată sau falsă:\nLa SSL autentificarea este doar two-way folosind chei sau certificate digitale.',
    options: ['True', 'False'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Care dintre cele de mai jos reprezintă definiţia corectă pentru conceptul "Security Onion"?',
    options: [
      'Security Onion este un serviciu de cloud computing care oferă stocare sigură pentru datele sensibile ale companiilor.',
      'Security Onion este un sistem de operare special creat pentru programatori în domeniul securității cibernetice.',
      'Security Onion este o platformă de monitorizare a securității rețelei care oferă context, informații și cunoaștere situațională a rețelei tale.',
      'Security Onion este un software de protecție antivirus pentru calculatoare personale.',
      'Security Onion este o aplicație mobilă destinată protecției datelor personale pe dispozitivele mobile.',
      'Security Onion este o metodă de criptare a datelor bazată pe algoritmi onion routing.',
    ],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care din următoarele variante reprezintă un algoritm de criptare simetrică (algeţi 2 variante):',
    options: ['AES', 'DH', '3DES', 'DSA', 'DSS', 'RSA'],
    correctIndices: [0, 2],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care din topologiile din lista de mai jos reprezintă topologii WAN? (Selectaţi 2 variante)',
    options: ['Hub-and-Spoke Topology', 'Cell Topology', 'Star Topology', 'Fully Meshed Topology', 'Ring Topology', 'Tree Topology'],
    correctIndices: [0, 3],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre următoarele afirmații este adevărată în ceea ce privește cablarea cu fibră optică în comparație cu cablarea UTP? (Selectați 2 variante corecte)',
    options: [
      'Cablarea UTP suportă o lățime de bandă mai mare decât fibra optică.',
      'Instalarea cablurilor UTP necesită mai multă experiență decât instalarea fibrei optice.',
      'Cablarea UTP este mai costisitoare decât fibra optică.',
      'Fibra optică poate atinge distanțe de până la 100.000 de metri.',
      'Cablarea UTP oferă cea mai mare protecție împotriva pericolelor electrice.',
      'Fibra optică este complet imună la interferențe electromagnetice (EMI) și radio (RFI).',
    ],
    correctIndices: [3, 5],
  },
  {
    type: 'matching',
    text: 'Care este ordinea corectă a tipurilor de mesaje OSPF în procesul de schimb de informații și menținere a relațiilor de vecinătate? (Ordonați de sus în jos)',
    subQuestions: [
      { text: '1', answer: 'Hello' },
      { text: '2', answer: 'DBD' },
      { text: '3', answer: 'LSR' },
      { text: '4', answer: 'LSU' },
      { text: '5', answer: 'LSAck' },
    ],
    options: ['Hello', 'LSP', 'DBD', 'LSU', 'LSR', 'LSAck'],
  },
  {
    type: 'multiple-choice',
    text: 'Care este denumirea completă a acronimului DMZ?',
    options: [
      'Dynamic Management Zone',
      'Domain Management Zone',
      'Distributed Monitoring Zone',
      'Distributed Zone',
      'Demilitarized Zone',
      'Distributed Memory Zone',
    ],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Ce rol îndeplinește următorul ACL aplicat pe portul Gig0/0/1?',
    image: 'subiecte_acad/images/nationala_2025_1112/q10.png',
    options: [
      'Permite primirea traficului de tip FTP și HTTP de la spațiul de adresare 192.168.1.0/24 și blochează orice alt tip de trafic',
      'Permite trimiterea traficului de tip HTTPS și Telnet de la spațiul de adresare 192.168.1.0/24 și blochează orice alt tip de trafic.',
      'Permite trimiterea traficului de tip FTP și HTTP de la spațiul de adresare 192.168.1.0/24 și blochează orice alt tip de trafic.',
      'Permite primirea traficului de tip HTTPS și Telnet de la spațiul de adresare 192.168.1.0/24 și blochează orice alt tip de trafic.',
      'Blochează primirea de tip SSH de la spațiul de adresare 192.168.1.0/24 și permite orice alt tip de trafic al spațiului de adresare 192.168.1.0/24.',
      'Blochează traficul de tip SSH de la spațiul de adresare 192.168.1.0/24 și permite orice alt tip de trafic al spațiului de adresare 192.168.1.0/24.',
    ],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care din următoarele variante reprezintă un model de acces (alegeţi 3 variante) :',
    options: ['RABC', 'DAC', 'CAT', 'ABAC', 'RBAC', 'SAC'],
    correctIndices: [1, 3, 4],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Selectați caracteristicile specifice protocolului PAT. (Alegeți 3 variante)',
    options: [
      'Folosește adrese IPv4 și porturi sursă TCP sau UDP în procesul de traducere',
      'Mapare one-to-one între Inside Local și Inside Global',
      'Este necesară o adresă Inside Global unică pentru fiecare stație ce accesează rețeaua externă',
      'O adresă Inside Global poate fi mapată la mai multe adrese Inside Local',
      'Folosește doar adrese IPv4 în procesul de translație',
      'O singură adresă Inside Global poate să fie impărțită de mai multe stații ce trebuie să acceseze rețeaua externă',
    ],
    correctIndices: [0, 3, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Stabiliţi dacă următoarea propoziţie este adevărată sau falsă:\nFie următorul EtherChannel configurat cu LACP. Dacă un port este setat în modul "pasive" iar celalat port este setat în modul "on", atunci conexiuna va fi stabilă.',
    image:'subiecte_acad/images/nationala_2025_1112/q13.png',
    options: ['True', 'False'],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Care din variantele de mai jos este un instrument de linie de comandă care afişează capturi de pachete în timp real?',
    options: ['NetFlow', 'AVC', 'TCPDUMP', 'WSA', 'ESA', 'DLP'],
    correctIndex: 2,
  },
  {
    type: 'label-order',
    text: 'Ordonaţi de sus in jos, etapele unui sistem de citire a unei cartele de acces:',
    labels: [
      'O cartelă de acces este glisată',
      'Sistemul înregistrează detaliile acestei tranzacții pentru recuperarea ulterioară',
      'Computerul ia decizii de control al accesului pe baza acreditării furnizate',
      'Cititorul de carduri citește un număr de pe cartela de acces',
      'Sistemul trimite numărul către un computer',
    ],
    correctOrder: [0, 3, 4, 2, 1],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care sunt cele trei modele ale QoS? (Alegeți 3 variante)',
    options: [
      'Modelul Resource Management',
      'Modelul Integrated Services',
      'Modelul Policy-Based Services',
      'Modelul Differentiated Services',
      'Modelul Best-Effort',
      'Modelul Flow Prioritization',
    ],
    correctIndices: [1, 3, 4],
  },
  {
    type: 'multiple-choice',
    text: 'Un pachet IPv4 este capturat în rețea cu următoarele detalii:\nVersion = 0100\nTTL = 2\nProtocol = 1\nHeader Checksum este invalid\nAdresa destinație = 255.255.255.255\nCe se întâmplă cu acest pachet atunci când ajunge la un router?',
    options: [
      'Routerul resetează checksum-ul și transmite pachetul către adresa broadcast.',
      'Pachetul este aruncat de router din cauza checksum-ului invalid, fără a trimite răspuns ICMP.',
      'Routerul ignoră câmpul checksum și transmite pachetul mai departe.',
      'Pachetul este aruncat din cauza valorii TTL și routerul trimite un mesaj ICMP Time Exceeded către adresa sursă.',
      'Pachetul este redirecționat către toate interfețele, deoarece este broadcast și TTL este suficient.',
      'Pachetul este respins imediat deoarece adresa de destinație este o adresă unicast invalidă.',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Presupunând că tabelele CAM ale tuturor switch-urilor sunt inițial goale, cum va arăta tabela CAM a switch-ului „Sw5" după transmiterea a două cadre Ethernet – unul de la hostul A către hostul E, urmat de unul de la hostul F către hostul A – în această ordine?\nAtenție: Nu există răspunsuri din partea destinațiilor.',
    image: 'subiecte_acad/images/nationala_2025_1112/q18.png',
    options: [
      'MacA - Fa0/3',
      'MacA - Fa0/1',
      'MacE - Fa0/2, MacA - Fa0/1',
      'MacF - Fa0/1',
      'MacA - Fa0/1, MacF - Fa0/1',
      'MacA - Fa0/3, MacF - Fa0/3',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care din variantele de mai jos reprezintă un câmp găsit în formatul complet al unui mesaj Syslog?\n(Selectați 3 răspunsuri)',
    options: ['Length', 'FCS (frame check sequence)', 'Flags', 'PRI (priority)', 'MSG (message text)', 'Header'],
    correctIndices: [3, 4, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Pe ce port UDP (User Datagram Protocol) funcționează protocolul Network Time Protocol (NTP)?',
    options: ['23', '454', '123', '156', '144', '205'],
    correctIndex: 2,
  },
  {
    type: 'open-ended',
    text: 'Care va fi adresa de destinație a unei rute statice care își propune să trimită pachetele către un LAN al cărui gateway implicit este 125.23.12.29/25? (Atenție! Trebuie scrisă adresa de rețea urmată de masca de rețea – adresa de rețea se scrie prima.)\nExemplu de input: 130.30.20.0 255.255.255.0',
    acceptedAnswers: ['125.23.12.0 255.255.255.128'],
  },
  {
    type: 'multiple-choice',
    text: 'Stabiliți valoarea de adevăr a următoarei afirmații:\nPrincipalul scop al Core Layer-ului este de a oferi conexiune la viteze mari, cât și izolarea impedimentelor (erorilor).',
    options: ['Adevărat', 'Fals'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Câți biți conține câmpul folosit pentru verificarea erorilor într-un segment TCP?',
    options: ['2', '32', '64', '8', '16', '4'],
    correctIndex: 4,
  },
  {
    type: 'open-ended',
    text: 'Care este spațiul de adrese IPv4 APIPA?(Atenție! Trebuie scrisă în felul urmsător: adresă de rețea și masca, EX: 192.168.0.0 255.255.255.0)',
    acceptedAnswers: ['169.254.0.0 255.255.0.0'],
  },
  {
    type: 'matching',
    text: 'Plasați fiecare tip de alertă în căsuța corespunzătoare pentru scenariile în care politica de securitate a unui port de switch a fost încălcată!',
    subQuestions: [
      { text: 'Protect', answer: 'Respinge PDU‑ul trimis de la o adresa MAC neștiută' },
      { text: 'Restrict', answer: 'Respinge PDU‑ul trimis de la o adresa MAC neștiută, după generează loguri de eroare' },
      { text: 'Shutdown', answer: 'Dezactiveaza interfață pe care s‑a produs încălcarea de politică' },
    ],
    options: [
      'Ignoră complet politica de securitate aplicată portului.',
      'Respinge PDU‑ul trimis de la o adresa MAC neștiută',
      'Respinge PDU‑ul trimis de la o adresa MAC neștiută, după generează loguri de eroare',
      'Aplica o acțiune care nu este definită în politica de securitate.',
      'Dezactiveaza interfață pe care s‑a produs încălcarea de politică',
    ],
  },
  {
    type: 'multiple-choice',
    text: 'Ce componentă a protocolului IPsec asigură confidențialitatea datelor transmise între două dispozitive?',
    options: [
      'Authentication Header (AH)',
      'Encapsulation Security Payload (ESP)',
      'Simple Network Management Protocol (SNMP)',
      'Internet Control Message Protocol (ICMP)',
      'Datagram Transport Layer Security (DTLS)',
      'Secure Shell (SSH)',
    ],
    correctIndex: 1,
  },
  {
    type: 'multiple-choice',
    text: 'Ce interfețe vor fi în modul blocking după ce se finalizează STP (Spanning Tree Protocol)?',
    image: 'subiecte_acad/images/nationala_2025_1112/q27.png',
    options: ['Switch1 : Fa0/1', 'Switch0 : Fa0/1', 'Switch2 : Fa0/1', 'Switch3 : Fa0/2', 'Switch2 : Fa0/2', 'Switch0 : Gig0/2', 'Switch3 : Fa0/1'],
    correctIndex: 6,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Ce valori pot avea flag-urile dintr-un Router Advertisement (RA) pentru Stateful DHCPv6?\n(Selectați 2 răspunsuri)',
    options: [
      'A flag=0, O flag=0, M flag=1',
      'A flag=0, O flag=0, M flag=0',
      'A flag=0, O flag=1, M flag=1',
      'A flag=1, O flag=1, M flag=0',
      'A flag=1, O flag=1, M flag=1',
      'A flag=1, O flag=0, M flag=0',
    ],
    correctIndices: [0, 2],
  },
  {
    type: 'matching',
    text: 'Asociaţi următoarele definiţii cu termenii corespunzători:',
    subQuestions: [
      { text: 'Nu primeşte pachete de tip Hello.', answer: 'Down State' },
      { text: 'Comunicarea dintre două routere este bidirecţională. Routerele aleg DR sau BDR.', answer: 'Two-Way State' },
      { text: 'S-au primit pachete Hello de la vecini cu ID-ul routerelor.', answer: 'Init State' },
      { text: 'Se trimit mesaje DBD.', answer: 'Exchange State' },
      { text: 'Se decide cine trimite primul DBD-ul.', answer: 'ExStart State' },
    ],
    options: ['Down State', 'Two-Way State', 'Init State', 'Exchange State', 'ExStart State'],
  },
  {
    type: 'matching',
    text: 'Potriviți fiecare descriere cu starea HSRP (Hot Standby Router Protocol) corespunzătoare.',
    subQuestions: [
      { text: 'Această stare apare atunci când router-ul cunoaște adresa IP virtuală, dar acesta nu este nici router activ și nici router standby.', answer: 'Listen' },
      { text: 'Această stare apare atunci când router-ul transmite pachetele trimise către grupul HSRP în afara rețelei și, totodată, trimite mesaje de tip "hello" periodic.', answer: 'Active' },
      { text: 'Această stare apare atunci când router-ul nu a determinat încă adresa IP virtuală și nu a primit un mesaj de tip "hello" de la router-ul activ.', answer: 'Learn' },
      { text: 'Această stare apare atunci când router-ul monitorizează mesajele de tip "hello" trimise de router-ul activ și este gata să devină activ în momentul în care router-ul activ eșuează sau se defectează.', answer: 'Standby' },
      { text: 'Această stare apare atunci când router-ul trimite mesaje de tip "hello" periodic și participă în alegerea router-ului activ sau standby.', answer: 'Speak' },
      { text: 'Această stare apare atunci când se modifică o configurație sau când o interfață este pornită pentru prima dată.', answer: 'Initial' },
    ],
    options: ['Initial', 'Standby', 'Listen', 'Learn', 'Active', 'Speak'],
  },
]
});
