window.ACADOBRE_ALT_QUESTIONS.push({
  id: 'nationala_2025_9_10',
  topic: 'Naționala 9-10 2025',
  questions: [
  {
    type: 'open-ended',
    text: 'Care este spațiul de adrese IPv4 APIPA?',
    acceptedAnswers: ['169.254.0.0 255.255.0.0'],
    hint: '(Atenție! Trebuie scrisă în felul urmsător: adresă de rețea și masca, EX: 192.168.0.0 255.255.255.0)".',
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care din următoarele comenzi sunt utilizate în Windows pentru a vizualiza tabela de rutare pe un PC? (Alegeţi două variante)',
    options: ['netstat -r', 'route print', 'print route table', 'netstat -l', 'table print', 'print route'],
    correctIndices: [0, 1],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre următoarele afirmații este adevărată în ceea ce privește cablarea cu fibră optică în comparație cu cablarea UTP? (Selectați 2 variante corecte)',
    options: [
      'Fibra optică poate atinge distanțe de până la 100.000 de metri.',
      'Cablarea UTP oferă cea mai mare protecție împotriva pericolelor electrice.',
      'Cablarea UTP este mai costisitoare decât fibra optică.',
      'Instalarea cablurilor UTP necesită mai multă experiență decât instalarea fibrei optice.',
      'Cablarea UTP suportă o lățime de bandă mai mare decât fibra optică.',
      'Fibra optică este complet imună la interferențe electromagnetice (EMI) și radio (RFI).',
    ],
    correctIndices: [0, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Determinați, folosind metodă de subnetare VLSM, masca de rețea aferentă fiecărei rețele enumerate mai jos :\nGuests : 255 de hosturi\nIT: 1231 de hosturi\nSecretariat : 827 de hosturi\nAtenție! Default Gateway-ul nu este inclus în numărul de hosturi!',
    options: [
      'Guests : 255.255.240.0\nIT : 255.255.224.0\nSecretariat : 255.255.255.0',
      'Guests : 255.255.240.0\nIT : 255.255.192.0\nSecretariat : 255.192.0.0',
      'Guests : 255.255.255.0\nIT : 255.255.128.0\nSecretariat : 255.0.0.0',
      'Guests : 255.255.255.0\nIT : 255.255.255.252\nSecretariat : 255.255.248.0',
      'Guests : 255.255.254.0\nIT : 255.255.248.0\nSecretariat : 255.255.252.0',
      'Guests : 255.255.252.0\nIT : 255.255.210.0\nSecretariat : 255.0.0.0',
    ],
    correctIndex: 4,
  },
  {
    type: 'open-ended',
    text: 'Care va fi adresa de destinație a unei rute statice care își propune să trimită pachetele către un LAN al cărui gateway implicit este 125.23.12.29/25?',
    acceptedAnswers: ['125.23.12.0 255.255.255.128'],
    hint: '(Atenție! Trebuie scrisă adresa de rețea urmată de masca de rețea – adresa de rețea se scrie prima.)\nExemplu de input: 130.30.20.0 255.255.255.0".',
  },
  {
    type: 'multiple-choice-multi',
    text: 'Ce comenzi se folosesc pentru a verifica erorile porturilor de tip trunk? (Alegeți 2 variante)',
    options: [
      'show running-config interface',
      'do write',
      'show interfaces trunk',
      'show vlan',
      'show vlan brief',
      'show running-config',
    ],
    correctIndices: [2, 5],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre cele trei stări STP ale unui port formează starea discarding a RSTP-ului? (Alegeți 3 variante)',
    options: ['Blocking', 'Listening', 'Forwaring', 'Disabled', 'Learning', 'Trading'],
    correctIndices: [0, 1, 3],
  },
  {
    type: 'matching',
    text: 'Care este ordinea corectă a tipurilor de mesaje OSPF în procesul de schimb de informații și menținere a relațiilor de vecinătate? (Ordonați de sus în jos)',
    subQuestions: [
      { text: '1.', answer: 'Hello' },
      { text: '2.', answer: 'DBD' },
      { text: '3.', answer: 'LSR' },
      { text: '4.', answer: 'LSU' },
      { text: '5.', answer: 'LSAck' },
    ],
    options: ['DBD', 'LSR', 'LSU', 'LSAck', 'Hello', 'LSP'],
  },
  {
    type: 'matching',
    text: 'Asociaţi următoarele definiţii cu termenii corespunzători:',
    subQuestions: [
      { text: 'Nu primeşte pachete de tip Hello.',                                                                                       answer: 'Down State' },
      { text: 'S-au primit pachete Hello de la vecini cu ID-ul routerelor.',                                                             answer: 'Init State' },
      { text: 'Se trimit mesaje DBD.',                                                                                                   answer: 'Exchange State' },
      { text: 'Se decide cine trimite primul DBD-ul.',                                                                                   answer: 'ExStart State' },
      { text: 'Comunicarea dintre două routere este bidirecţională. Routerele aleg DR sau BDR.',                                         answer: 'Two-Way State' },
    ],
    options: ['Down State', 'Init State', 'Exchange State', 'ExStart State', 'Two-Way State'],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care sunt cele 3 criterii de conectare a unui switch la un domeniu VTP? (Alegeți 3 variante)',
    options: [
      'Parola domeniului',
      'Hostname-ul',
      'Switch-ul trebuie să fie configurat cu o adresă IP pentru a se conecta la domeniul VTP.',
      'Numele domeniului',
      'Versiunea de VTP pe care o are server-ul',
      'Parola de pe interfața virtuală',
    ],
    correctIndices: [0, 3, 4],
  },
  {
    type: 'multiple-choice-multi',
    text: 'Care dintre următoarele afirmații descriu corect rolul sub-straturilor din stratul de legătură de date IEEE 802? (Alegeți 2 variante corecte)',
    options: [
      'Substratul LLC permite utilizarea mai multor protocoale de Nivel 3 pe aceeași interfață fizică.',
      'Substratul MAC se ocupă de încapsularea datelor și controlul accesului la mediu.',
      'Substratul LLC face parte din stratul fizic.',
      'Substratul MAC determină ce protocol de Nivel 3 este utilizat.',
      'Substratul LLC oferă adrese pentru dispozitivele din rețea.',
      'Substratul MAC funcționează exclusiv în software, nu în hardware.',
    ],
    correctIndices: [0, 1],
  },
  {
    type: 'multiple-choice',
    text: 'Câți biți conține câmpul folosit pentru verificarea erorilor într-un segment TCP?',
    options: ['8', '2', '16', '4', '64', '32'],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'Evaluați următoarea afirmație cu adevărat sau fals:\nRoutingul Inter-VLAN de tip legacy constă în utilizarea unei conexiuni unice între switch și router, dedicată fiecărui VLAN.',
    options: ['True', 'False'],
    correctIndex: 0,
  },
  {
    type: 'multiple-choice',
    text: 'Care dintre variantele de mai jos reprezintă corect adresa IP 254.28.99.252 în format binar?',
    options: [
      '11111110.00011100.01101011.11111100',
      '11111110.00011100.01111111.11111100',
      '11111110.00011100.01100011.00000000',
      '11111110.00011100.01100011.10011100',
      '11111110.00111000.01100011.11111100',
      '11111110.00011100.01100011.11111100',
    ],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice-multi',
    text: 'Ce valori pot avea flag-urile dintr-un Router Advertisement (RA) pentru Stateful DHCPv6?\n(Selectați 2 răspunsuri)',
    options: [
      'A flag=1, O flag=1, M flag=1',
      'A flag=0, O flag=0, M flag=0',
      'A flag=0, O flag=0, M flag=1',
      'A flag=1, O flag=0, M flag=0',
      'A flag=1, O flag=1, M flag=0',
      'A flag=0, O flag=1, M flag=1',
    ],
    correctIndices: [2, 5],
  },
  {
    type: 'multiple-choice',
    text: 'Care este distanță administrativă pentru protocolul de rutare BGP în modul extern?',
    options: ['20', '1', 'Niciun răspuns nu este corect.', '0', '120', '90'],
    correctIndex: 0,
  },
  {
    type: 'matching',
    text: 'Potriviți fiecare descriere cu starea HSRP (Hot Standby Router Protocol) corespunzătoare.',
    subQuestions: [
      { text: 'Această stare apare atunci când se modifică o configurație sau când o interfață este pornită pentru prima dată.',                                                                                                                                         answer: 'Initial' },
      { text: 'Această stare apare atunci când router-ul monitorizează mesajele de tip "hello" trimise de router-ul activ și este gata să devină activ în momentul în care router-ul activ eșuează sau se defectează.',                                                  answer: 'Standby' },
      { text: 'Această stare apare atunci când router-ul cunoaște adresa IP virtuală, dar acesta nu este nici router activ și nici router standby.',                                                                                                                    answer: 'Listen' },
      { text: 'Această stare apare atunci când router-ul nu a determinat încă adresa IP virtuală și nu a primit un mesaj de tip "hello" de la router-ul activ.',                                                                                                        answer: 'Learn' },
      { text: 'Această stare apare atunci când router-ul trimite mesaje de tip "hello" periodic și participă în alegerea router-ului activ sau standby.',                                                                                                               answer: 'Speak' },
      { text: 'Această stare apare atunci când router-ul transmite pachetele trimise către grupul HSRP în afara rețelei și, totodată, trimite mesaje de tip "hello" periodic.',                                                                                         answer: 'Active' },
    ],
    options: ['Initial', 'Standby', 'Listen', 'Learn', 'Speak', 'Active'],
  },
  {
    type: 'matching',
    text: 'Plasați fiecare tip de alertă în căsuța corespunzătoare pentru scenariile în care politica de securitate a unui port de switch a fost încălcată!',
    subQuestions: [
      { text: 'Protect',  answer: 'Respinge PDU‑ul trimis de la o adresa MAC neștiută' },
      { text: 'Restrict', answer: 'Respinge PDU‑ul trimis de la o adresa MAC neștiută, după generează loguri de eroare' },
      { text: 'Shutdown', answer: 'Dezactiveaza interfață pe care s‑a produs încălcarea de politică' },
    ],
    options: [
      'Respinge PDU‑ul trimis de la o adresa MAC neștiută',
      'Respinge PDU‑ul trimis de la o adresa MAC neștiută, după generează loguri de eroare',
      'Dezactiveaza interfață pe care s‑a produs încălcarea de politică',
      'Ignoră complet politica de securitate aplicată portului.',
      'Aplica o acțiune care nu este definită în politica de securitate.',
    ],
  },
  {
    type: 'multiple-choice',
    text: 'Ce sufix ar trebuie să conțină numele fișierului binar al imaginii CISCO IOS pentru a suporta anumite feature-uri de securitate avansate, cum ar fi configurarea SSH-ului?',
    options: ['SPA', 'bin', 'k9', 'cis', 'mz', 'Niciun răspuns nu este corect'],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'Care este formula corectă pentru calcularea metricii în protocolul OSPF?',
    options: [
      'Delay / (1 + Bandwidth)',
      'Bandwidth * Delay',
      '(Bandwidth * Cost) / Delay',
      '(1 / Bandwidth) + Cost',
      '10^8 / Bandwidth',
      'Cost + Delay - Bandwidth',
    ],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Un pachet IPv4 este capturat în rețea cu următoarele detalii:\nVersion = 0100\nTTL = 2\nProtocol = 1\nHeader Checksum este invalid\nAdresa destinație = 255.255.255.255\nCe se întâmplă cu acest pachet atunci când ajunge la un router?',
    options: [
      'Pachetul este redirecționat către toate interfețele, deoarece este broadcast și TTL este suficient.',
      'Routerul ignoră câmpul checksum și transmite pachetul mai departe.',
      'Pachetul este aruncat din cauza valorii TTL și routerul trimite un mesaj ICMP Time Exceeded către adresa sursă.',
      'Routerul resetează checksum-ul și transmite pachetul către adresa broadcast.',
      'Pachetul este respins imediat deoarece adresa de destinație este o adresă unicast invalidă.',
      'Pachetul este aruncat de router din cauza checksum-ului invalid, fără a trimite răspuns ICMP.',
    ],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'Ce interfețe vor fi în modul blocking după ce se finalizează STP (Spanning Tree Protocol)?',
    image: 'subiecte_acad/images/nationala_2025_910/q22.png',
    options: [
      'Switch2 : Fa0/1',
      'Switch3 : Fa0/2',
      'Switch1 : Fa0/1',
      'Switch0 : Gig0/2',
      'Switch2 : Fa0/2',
      'Switch0 : Fa0/1',
      'Switch3 : Fa0/1'
    ],
    correctIndex: 6,
  },
  {
    type: 'multiple-choice',
    text: 'În cadrul cărui standard este specificat protocolul LACP?',
    options: ['802.2AX', '802.1X', '802.3ad', '802.1D', '802.1Q', '802.11'],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'Ce valoare trebuie setată în câmpul "Protocol" din header-ul de IPv4, știind că se encapsulează protocolul TCP?',
    options: ['56', '17', '41', '6', '1', '18'],
    correctIndex: 3,
  },
  {
    type: 'multiple-choice',
    text: 'Presupunând că tabelele CAM ale tuturor switch-urilor sunt inițial goale, cum va arăta tabela CAM a switch-ului „Sw5" după transmiterea a două cadre Ethernet – unul de la hostul A către hostul E, urmat de unul de la hostul F către hostul A – în această ordine?\nAtenție: Nu există răspunsuri din partea destinațiilor.',
    image: 'subiecte_acad/images/nationala_2025_910/q25.png',
    options: [
      'MacA - Fa0/1, MacF - Fa0/1',
      'MacA - Fa0/3, MacF - Fa0/3',
      'MacE - Fa0/2, MacA - Fa0/1',
      'MacA - Fa0/3',
      'MacF - Fa0/1',
      'MacA - Fa0/1',
    ],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'Ce face scurtătura Ctrl+P în cisco IOS?',
    options: [
      'Șterge comanda de la sfârșitul ei până la poziția cursorului',
      'Deschide tabela de rutare pentru editare',
      'Șterge comandă de la cursor la începutul acesteia',
      'Scoate utilizatorul din modul de configurare a unei interfețe',
      'Afișează comandă anterioară din istoric, începând cu cea mai recentă comandă',
      'Șterge comandă de la sfârșitul ei la cursor',
    ],
    correctIndex: 4,
  },
  {
    type: 'multiple-choice',
    text: 'Care este portul standard utilizat de protocolul DNS?',
    options: ['54', '55', '50', '51', '52', '53'],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'Ce eroare este reprezentată de un mesaj Destination Unreachable ICMPv4 ce returnează codul 2?',
    options: [
      'Mesajele Destination Unreachable ICPMv4 pot avea doar codul 0 sau 1',
      'Host Unreachable',
      'Net Unreachable',
      'Port Unreachable',
      'Fragmentation Needed',
      'Protocol Unreachable',
    ],
    correctIndex: 5,
  },
  {
    type: 'multiple-choice',
    text: 'În ce interval de numere se situează porturile well-known?',
    options: ['2048 - 49151', '0 - 2047', '0 - 1023', '1024 - 49151', '0 - 1024', '49152 - 65535'],
    correctIndex: 2,
  },
  {
    type: 'multiple-choice',
    text: 'Stabiliţi dacă următoarea propoziţie este adevărată sau falsă:\nFie următorul EtherChannel configurat cu LACP. Dacă un port este setat în modul "pasive" iar celalat port este setat în modul "on", atunci conexiuna va fi stabilă.',
    options: ['True', 'False'],
    correctIndex: 1,
  },
]
});
